package com.gachiguild.gachitoeic.ui

import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

/**
 * 単語帳アプリのUI文字列。日本語・英語・中国語・ヒンディー語・ベトナム語・韓国語・インドネシア語・タイ語・スペイン語をサポート。
 */
data class AppStrings(
    val isJapanese: Boolean,
    /** Translation data key used by VocabularyItem.meaningFor. */
    val languageCode: String,
    // ── 共通 ──
    val appName: String,
    val all: String,

    // ── Vocabulary ──
    val vocabulary: String,
    val vocabProgress: String,
    val vocabTotal: String,
    val vocabLearned: String,
    val vocabMastered: String,
    val vocabReviewDue: String,
    val vocabCategoryAll: String,
    val vocabCategoryLearned: String,
    val vocabCategoryMastered: String,
    val vocabCategoryReviewDue: String,
    val vocabFlashcard: String,
    val tapToShowMeaning: String,
    val vocabPrev: String,
    val frogPrevButtonHelp: String,
    val frogButtonHelpTitle: String,
    val frogStarButtonHelp: String,
    val frogButtonHelp: String,
    val history: String,
    val historyEmpty: String,
    val search: String,
    val level: String,
    val language: String,
    val languageJapanese: String,
    val languageEnglish: String,
    val languageChinese: String,
    val languageHindi: String,
    val languageVietnamese: String,
    val languageKorean: String,
    val languageIndonesian: String,
    val languageThai: String,
    val languageSpanish: String,
    val speechPlay: String,
    /** ネットワーク未接続時、ネットワーク利用機能（音声読み上げなど）の利用不可メッセージ */
    val speechNetworkUnavailable: String,
    val buttonSoundOn: String,
    val buttonSoundOff: String,
    val speechMutedTitle: String,
    val speechMutedOk: String,
    val speechMutedPronounce: String,
    val premiumLevelsPrice: String,
    val premiumLevelsTitle: String,
    val premiumLevelsDescription: String,
    val premiumLevelsPurchase: String,
    val premiumLevelsRestore: String,
    val premiumLevelsUnlocked: String,
    val premiumLevelsPending: String,
    val premiumLevelsPurchaseSuccess: String,
    val premiumLevelsPurchaseError: String,

    // ── 設定 ──
    val settings: String,
    val settingsDescription: String,
    val accent: String,
    val accentDescription: String,
    val license: String,
    val licenseDescription: String,
    val tutorial: String,
    val dataMigration: String,
    val backup: String,
    val restore: String,
    val backupRestoreDescription: String,
    val restoreConfirmationTitle: String,
    val restoreConfirmationMessage: String,
    val restoreConfirmationAction: String,
    val restoreCompletedMessage: String,
    val backupSaved: String,
    val backupSaveFailed: String,
    val backupReadFailed: String,
    val restoreFailed: String,
    val comingSoon: String,
    val close: String,

    // ── ストリーク・目標 ──
    val streakDays: String,          // "連続N日"
    val dailyGoal: String,           // "1日の目標"
    val todayLearned: String,        // "今日の学習"
    val goalReached: String,         // "目標達成！"
    val setDailyGoal: String,        // "目標を設定"
    val goalOptions: List<Int>,      // 選択肢 (5, 10, 20, 30)
    val streakAchieved: String,      // "連続〇日達成！"
    val streakModalTitle: String,    // "🔥 ストリーク達成！"
    val streakModalMessage: String,  // "素晴らしい！連続N日達成しました。"
    val streakModalOk: String,       // "続ける"
    val streakDialogTitle: String,
    val streakDialogActiveMessage: String,
    val streakDialogRecoveryMessage: String,
    val streakDialogRecoveryAction: String,
    val streakDialogRecoveredMessage: String,
    val streakRecoveryTickets: String,
    val streakTicketRecoveryAction: String,

    // ── ヒートマップ ──
    val heatmapTitle: String,        // "🌱 学習ヒートマップ"
    val heatmapTotalLabel: String,   // "合計: %d語学習"
    val heatmapDayCount: String,     // "%d件学習"
    val aiApps: String = "AI Apps",
    val aiChange: String = "Change",
    val aiLiveGuidance: String = "AIアプリを起動したらLive／音声機能をオンにしてください。Liveで発音や会話を練習すると、声に出すことで単語が記憶に残りやすく、楽しく学べます。Liveを開始したあと、最近使ったアプリ一覧からこの単語帳アプリを再選択して、学習を続けてください。",
    val aiLaunch: String = "起動する",
    val aiNoInstalledApps: String = "ChatGPT、Geminiのインストール済みアプリがありません。",
    val aiLaunchFailed: String = "このAIアプリを起動できませんでした。"
) {
    /** 21:00のストリーク危機通知。通知側からも現在の表示言語をそのまま利用する。 */
    val streakReminderTitle: String
        get() = when (languageCode) {
            "ja" -> "⚠️ ストリークが切れそう！"
            "zh" -> "⚠️ 连续学习记录快要中断了！"
            "hi" -> "⚠️ आपकी स्ट्रीक टूटने वाली है!"
            "vi" -> "⚠️ Chuỗi ngày của bạn sắp bị mất!"
            "ko" -> "⚠️ 스트릭이 끊길 위기예요!"
            "id" -> "⚠️ Streak-mu hampir putus!"
            "th" -> "⚠️ สตรีคของคุณกำลังจะขาด!"
            "es" -> "⚠️ ¡Tu racha está en peligro!"
            else -> "⚠️ Your streak is at risk!"
        }

    /** ストリーク危機通知の本文。詳細な残り数は表示せず、学習開始を促す。 */
    val streakReminderMessage: String
        get() = when (languageCode) {
            "ja" -> "今すぐ学習を始めよう。"
            "zh" -> "现在就开始学习，保持连续记录。"
            "hi" -> "अपनी स्ट्रीक बनाए रखने के लिए अभी सीखना शुरू करें।"
            "vi" -> "Hãy bắt đầu học ngay để giữ chuỗi ngày."
            "ko" -> "스트릭을 지키려면 지금 학습을 시작하세요."
            "id" -> "Mulai belajar sekarang untuk mempertahankan streak-mu."
            "th" -> "เริ่มเรียนตอนนี้เพื่อรักษาสตรีคของคุณ"
            "es" -> "Empieza a estudiar ahora para mantener tu racha."
            else -> "Start learning now to keep your streak alive."
        }

    val streakReminderChannelName: String
        get() = when (languageCode) {
            "ja" -> "ストリーク通知"
            "zh" -> "连续学习提醒"
            "hi" -> "स्ट्रीक रिमाइंडर"
            "vi" -> "Nhắc nhở chuỗi ngày"
            "ko" -> "스트릭 알림"
            "id" -> "Pengingat streak"
            "th" -> "การแจ้งเตือนสตรีค"
            "es" -> "Recordatorio de racha"
            else -> "Streak reminders"
        }

    val copyText: String
        get() = when (languageCode) {
            "ja" -> "コピー"
            "zh" -> "复制"
            "hi" -> "कॉपी"
            "vi" -> "Sao chép"
            "ko" -> "복사"
            "id" -> "Salin"
            "th" -> "คัดลอก"
            "es" -> "Copiar"
            else -> "Copy"
        }

    val copyDone: String
        get() = when (languageCode) {
            "ja" -> "コピーしました"
            "zh" -> "已复制"
            "hi" -> "कॉपी किया गया"
            "vi" -> "Đã sao chép"
            "ko" -> "복사했습니다"
            "id" -> "Disalin"
            "th" -> "คัดลอกแล้ว"
            "es" -> "Copiado"
            else -> "Copied"
        }

}

/** 日本語文字列定義（デフォルト） */
val JapaneseStrings = AppStrings(
    isJapanese = true,
    languageCode = "ja",
    appName = "単語帳",
    all = "すべて",

    vocabulary = "単語帳",
    vocabProgress = "学習進捗",
    vocabTotal = "総単語数",
    vocabLearned = "お気に入り",
    vocabMastered = "マスター済み",
    vocabReviewDue = "未マスター",
    vocabCategoryAll = "すべての単語",
    vocabCategoryLearned = "学習中の単語",
    vocabCategoryMastered = "マスター済みの単語",
    vocabCategoryReviewDue = "未マスターの単語",
    vocabFlashcard = "🃏 単語カード",
    tapToShowMeaning = "タップして意味を表示",
    vocabPrev = "◀",
    frogPrevButtonHelp = "前の単語を見る",
    frogButtonHelpTitle = "単語カードのボタン",
    frogStarButtonHelp = "お気に入り：お気に入りに追加して次へ",
    frogButtonHelp = "マスター：青カエルを済みにして次へ",
    history = "🕐 履歴",
    historyEmpty = "まだ履歴がありません。単語カードやチェックなどを試してみましょう！",
    search = "検索...",
    level = "レベル: (TOEIC score)",
    language = "🌐 言語",
    languageJapanese = "日本語",
    languageEnglish = "English",
    languageChinese = "中文",
    languageHindi = "हिन्दी",
    languageVietnamese = "Tiếng Việt",
    languageKorean = "한국어",
    languageIndonesian = "インドネシア語",
    languageThai = "タイ語",
    languageSpanish = "スペイン語",
    speechPlay = "発音を再生",
    speechNetworkUnavailable = "この端末では音声を再生できません。音声データまたはTTS設定を確認してください。",
    buttonSoundOn = "ボタン音オン",
    buttonSoundOff = "ボタン音オフ",
    speechMutedTitle = "音声はミュート中です",
    speechMutedOk = "閉じる",
    speechMutedPronounce = "発音する",
    premiumLevelsPrice = "価格",
    premiumLevelsTitle = "🔒 プレミアムレベル",
    premiumLevelsDescription = "TOEIC 800+ の単語 %d語を、買い切りで解放できます。",
    premiumLevelsPurchase = "購入する",
    premiumLevelsRestore = "購入を復元",
    premiumLevelsUnlocked = "プレミアムレベルは解放済みです。",
    premiumLevelsPending = "購入処理中です。支払い完了後にレベルが解放されます。",
    premiumLevelsPurchaseSuccess = "購入が完了しました。TOEIC 800+ が解放されました。",
    premiumLevelsPurchaseError = "購入情報を確認できませんでした。時間をおいて再試行してください。",

    settings = "⚙️ 設定",
    settingsDescription = "アプリの表示言語を設定できます。発音アクセントはメイン画面から切り替えられます。",
    accent = "🎙️ 発音アクセント",
    accentDescription = "単語の発音・スペル表示を US または UK に切り替えます。",
    license = "📄 ライセンス",
    licenseDescription = "このアプリで使用しているオープンソースライブラリのライセンス情報を表示します。",
    tutorial = "チュートリアルをみる",
    dataMigration = "💾 データ管理",
    backup = "💾 バックアップ",
    restore = "📥 レストア",
    backupRestoreDescription = "Google ドライブや USB メモリなどに保存したファイルで、学習データを移行できます。",
    restoreConfirmationTitle = "レストアの確認",
    restoreConfirmationMessage = "作成日: %1\$s\n単語: %2\$d件\n履歴: %3\$d件\nお気に入り: %4\$d件\n\n現在の学習データは置き換えられます。",
    restoreConfirmationAction = "レストアする",
    restoreCompletedMessage = "レストアが完了しました。\n単語: %1\$d件\n履歴: %2\$d件\nお気に入り: %3\$d件\n\n表示設定を反映するため、画面を再読み込みします。",
    backupSaved = "バックアップを保存しました。",
    backupSaveFailed = "バックアップの保存に失敗しました。",
    backupReadFailed = "バックアップを読み込めませんでした。",
    restoreFailed = "レストアに失敗しました。",
    comingSoon = "この機能は準備中です。",
    close = "閉じる",

    streakDays = "連続",
    dailyGoal = "1日の目標",
    todayLearned = "今日の学習",
    goalReached = "🎉 目標達成！",
    setDailyGoal = "目標を設定",
    goalOptions = listOf(5, 10, 20, 30),
    streakAchieved = "🔥 連続%d日達成！",
    streakModalTitle = "🔥 ストリーク達成！",
    streakModalMessage = "素晴らしい！連続%d日達成しました。この調子で頑張りましょう！",
    streakModalOk = "続ける",
    streakDialogTitle = "🔥 ストリークを続けよう！",
    streakDialogActiveMessage = "現在%d日連続です。今日も目標を達成して、記録を伸ばしましょう！",
    streakDialogRecoveryMessage = "昨日はお休みでした。今日、目標の2日分（%2\$d語）を学習すると、%1\$d日ストリークを救済できます。",
    streakDialogRecoveryAction = "ストリークを救済する",
    streakDialogRecoveredMessage = "救済成功！%d日ストリークを継続中です。",
    streakRecoveryTickets = "救済チケット: %d枚",
    streakTicketRecoveryAction = "チケットで救済する",

    heatmapTitle = "🌱 学習ヒートマップ",
    heatmapTotalLabel = "合計: %d語学習",
    heatmapDayCount = "%d回学習",
    aiApps = "AIアプリ",
    aiChange = "変更",
    aiLiveGuidance = "AIアプリを起動したらLive／音声機能をオンにしてください。Liveで発音や会話を練習すると、声に出すことで単語が記憶に残りやすく、楽しく学べます。Liveを開始したあと、最近使ったアプリ一覧からこの単語帳アプリを再選択して、学習を続けてください。",
    aiLaunch = "起動する",
    aiNoInstalledApps = "ChatGPT、Geminiのインストール済みアプリがありません。",
    aiLaunchFailed = "このAIアプリを起動できませんでした。"
)

/** 英語文字列定義 */
val EnglishStrings = AppStrings(
    isJapanese = false,
    languageCode = "en",
    appName = "Vocabulary",
    all = "All",

    vocabulary = "Vocabulary",
    vocabProgress = "Learning Progress",
    vocabTotal = "Total Words",
    vocabLearned = "Favorites",
    vocabMastered = "Mastered",
    vocabReviewDue = "Not Mastered",
    vocabCategoryAll = "All Words",
    vocabCategoryLearned = "Words in Progress",
    vocabCategoryMastered = "Mastered Words",
    vocabCategoryReviewDue = "Not Mastered Words",
    vocabFlashcard = "🃏 Flashcards",
    tapToShowMeaning = "Tap to reveal the meaning",
    vocabPrev = "◀",
    frogPrevButtonHelp = "View the previous word",
    frogButtonHelpTitle = "Word card buttons",
    frogStarButtonHelp = "Favorite: add it to favorites and go to the next word",
    frogButtonHelp = "Master: mark the blue frog complete and go to the next word",
    history = "🕐 History",
    historyEmpty = "No history yet. Try flashcards or mastery checks!",
    search = "Search...",
    level = "Level: (TOEIC score)",
    language = "🌐 Language",
    languageJapanese = "日本語",
    languageEnglish = "English",
    languageChinese = "中文",
    languageHindi = "हिन्दी",
    languageVietnamese = "Tiếng Việt",
    languageKorean = "한국어",
    languageIndonesian = "Indonesian",
    languageThai = "ไทย",
    languageSpanish = "Spanish",
    speechPlay = "Play pronunciation",
    speechNetworkUnavailable = "Audio playback is unavailable on this device. Check the voice data or TTS settings.",
    buttonSoundOn = "Button sounds on",
    buttonSoundOff = "Button sounds off",
    speechMutedTitle = "Sound is muted",
    speechMutedOk = "Close",
    speechMutedPronounce = "Pronounce",
    premiumLevelsPrice = "Price",
    premiumLevelsTitle = "🔒 Premium level",
    premiumLevelsDescription = "Unlock %d TOEIC 800+ words with a one-time purchase.",
    premiumLevelsPurchase = "Buy now",
    premiumLevelsRestore = "Restore purchase",
    premiumLevelsUnlocked = "The premium level is unlocked.",
    premiumLevelsPending = "Your purchase is pending. The level will unlock after payment is completed.",
    premiumLevelsPurchaseSuccess = "Purchase complete. TOEIC 800+ is unlocked.",
    premiumLevelsPurchaseError = "We could not verify the purchase. Please try again later.",

    settings = "⚙️ Settings",
    settingsDescription = "Configure the app display language and data backup/restore. Change the pronunciation accent from the main screen.",
    accent = "🎙️ Pronunciation Accent",
    accentDescription = "Switch word pronunciation and spelling between US and UK.",
    license = "📄 Licenses",
    licenseDescription = "Display license information for open-source libraries used in this app.",
    tutorial = "View tutorial",
    dataMigration = "💾 Data Management",
    backup = "💾 Backup",
    restore = "📥 Restore",
    backupRestoreDescription = "Move your study data using a backup file saved to Google Drive, USB storage, or another location.",
    restoreConfirmationTitle = "Confirm restore",
    restoreConfirmationMessage = "Created: %1\$s\nWords: %2\$d\nHistory: %3\$d\nFavorites: %4\$d\n\nCurrent study data will be replaced.",
    restoreConfirmationAction = "Restore",
    restoreCompletedMessage = "Restore completed.\nWords: %1\$d\nHistory: %2\$d\nFavorites: %3\$d\n\nThe screen will reload to apply display settings.",
    backupSaved = "Backup saved.",
    backupSaveFailed = "Failed to save the backup.",
    backupReadFailed = "Failed to read the backup.",
    restoreFailed = "Restore failed.",
    comingSoon = "This feature is coming soon.",
    close = "Close",

    streakDays = "Day",
    dailyGoal = "Daily Goal",
    todayLearned = "Today",
    goalReached = "🎉 Goal Reached!",
    setDailyGoal = "Set Goal",
    goalOptions = listOf(5, 10, 20, 30),
    streakAchieved = "🔥 %d-day streak!",
    streakModalTitle = "🔥 Streak Achieved!",
    streakModalMessage = "Amazing! You've reached a %d-day streak. Keep it up!",
    streakModalOk = "Continue",
    streakDialogTitle = "🔥 Keep your streak going!",
    streakDialogActiveMessage = "You are on a %d-day streak. Reach today's goal to make it even longer!",
    streakDialogRecoveryMessage = "You missed yesterday. Study two days' worth today (%2\$d words) to rescue your %1\$d-day streak.",
    streakDialogRecoveryAction = "Rescue streak",
    streakDialogRecoveredMessage = "Rescue successful! Your %d-day streak is continuing.",
    streakRecoveryTickets = "Recovery tickets: %d",
    streakTicketRecoveryAction = "Use a ticket to rescue",

    heatmapTitle = "🌱 Study Heatmap",
    heatmapTotalLabel = "Total: %d words studied",
    heatmapDayCount = "%d activities",
    aiApps = "AI apps",
    aiChange = "Change",
    aiLiveGuidance = "After opening the AI app, turn on Live or voice mode. Practicing pronunciation and conversation in Live helps you remember words and makes learning more fun. Once Live starts, return to this vocabulary app from your recent apps and continue studying.",
    aiLaunch = "Open",
    aiNoInstalledApps = "ChatGPT and Gemini are not installed.",
    aiLaunchFailed = "This AI app could not be opened."
)

/** 中国語UI */
val ChineseStrings = EnglishStrings.copy(
    languageCode = "zh",
    appName = "词汇本",
    all = "全部",
    vocabulary = "词汇本",
    vocabProgress = "学习进度",
    vocabTotal = "单词总数",
    vocabLearned = "收藏",
    vocabMastered = "已掌握",
    vocabReviewDue = "未掌握",
    vocabCategoryAll = "全部单词",
    vocabCategoryLearned = "学习中的单词",
    vocabCategoryMastered = "已掌握的单词",
    vocabCategoryReviewDue = "未掌握的单词",
    vocabFlashcard = "🃏 单词卡",
    tapToShowMeaning = "点击查看释义",
    vocabPrev = "◀",
    frogPrevButtonHelp = "查看上一个单词",
    frogButtonHelpTitle = "单词卡按钮",
    frogStarButtonHelp = "收藏：加入收藏并进入下一个单词",
    frogButtonHelp = "记住了：提高掌握度并进入下一个单词",
    history = "🕐 历史记录",
    historyEmpty = "还没有学习记录。试试单词卡或掌握度检查！",
    search = "搜索…",
    level = "级别： (TOEIC 分数)",
    language = "🌐 语言",
    buttonSoundOn = "按钮音效已开启",
    buttonSoundOff = "按钮音效已关闭",
    speechMutedTitle = "声音已静音",
    speechMutedOk = "关闭",
    speechMutedPronounce = "播放发音",
    premiumLevelsPrice = "价格",
    premiumLevelsTitle = "🔒 高级等级",
    premiumLevelsDescription = "一次性购买即可解锁 TOEIC 800+ 的 %d 个单词。",
    premiumLevelsPurchase = "立即购买",
    premiumLevelsRestore = "恢复购买",
    premiumLevelsUnlocked = "高级等级已解锁。",
    premiumLevelsPending = "购买正在处理中。付款完成后将解锁该等级。",
    premiumLevelsPurchaseSuccess = "购买完成。TOEIC 800+ 已解锁。",
    premiumLevelsPurchaseError = "无法验证购买信息。请稍后重试。",
    settings = "⚙️ 设置",
    settingsDescription = "设置应用语言以及数据备份/恢复。可从主界面切换发音口音。",
    accent = "🎙️ 发音口音",
    accentDescription = "在美式英语和英式英语之间切换单词发音和拼写。",
    license = "📄 许可证",
    licenseDescription = "显示此应用所使用的开源库的许可证信息。",
    tutorial = "查看教程",
    dataMigration = "💾 数据管理",
    backup = "💾 备份",
    restore = "📥 恢复",
    backupRestoreDescription = "使用保存在 Google 云端硬盘、USB 存储或其他位置的备份文件迁移学习数据。",
    restoreConfirmationTitle = "确认恢复",
    restoreConfirmationMessage = "创建时间：%1\$s\n单词：%2\$d个\n历史记录：%3\$d条\n收藏：%4\$d个\n\n当前学习数据将被替换。",
    restoreConfirmationAction = "恢复",
    restoreCompletedMessage = "恢复完成。\n单词：%1\$d个\n历史记录：%2\$d条\n收藏：%3\$d个\n\n将重新加载页面以应用显示设置。",
    speechPlay = "播放发音",
    speechNetworkUnavailable = "此设备无法播放语音。请检查语音数据或 TTS 设置。",
    backupSaved = "备份已保存。",
    backupSaveFailed = "保存备份失败。",
    backupReadFailed = "无法读取备份。",
    restoreFailed = "恢复失败。",
    comingSoon = "此功能即将推出。",
    close = "关闭",
    dailyGoal = "每日目标",
    todayLearned = "今日学习",
    goalReached = "🎉 达成目标！",
    setDailyGoal = "设置目标",
    streakAchieved = "🔥 连续%d天！",
    streakModalTitle = "🔥 达成连续学习！",
    streakModalMessage = "太棒了！你已连续学习%d天。继续保持！",
    streakModalOk = "继续",
    streakDialogTitle = "🔥 继续保持连续学习！",
    streakDialogActiveMessage = "你已连续学习%d天。今天达成目标，就能继续刷新纪录！",
    streakDialogRecoveryMessage = "昨天没有完成学习。今天学习两天的量（%2\$d个单词），即可挽救%1\$d天的连续学习。",
    streakDialogRecoveryAction = "挽救连续学习",
    streakDialogRecoveredMessage = "挽救成功！%d天连续学习正在继续。",
    streakRecoveryTickets = "救援券：%d张",
    streakTicketRecoveryAction = "使用救援券",
    heatmapTitle = "🌱 学习热力图",
    heatmapTotalLabel = "合计：已学习%d个单词",
    heatmapDayCount = "学习%d次",
    aiChange = "更改",
    aiLiveGuidance = "打开 AI 应用后，请开启 Live 或语音功能。在 Live 中练习发音和对话，开口练习能帮助你更容易记住单词，也让学习更有趣。启动 Live 后，请从最近使用的应用列表中重新打开这个单词本，继续学习。",
    aiLaunch = "打开"
)

/** ヒンディー語UI */
val HindiStrings = EnglishStrings.copy(
    languageCode = "hi",
    appName = "शब्दावली",
    all = "सभी",
    vocabulary = "शब्दावली",
    vocabProgress = "सीखने की प्रगति",
    vocabTotal = "कुल शब्द",
    vocabLearned = "पसंदीदा",
    vocabMastered = "महारत हासिल किए गए शब्द",
    vocabReviewDue = "अभी तक नहीं सीखे",
    vocabCategoryAll = "सभी शब्द",
    vocabCategoryLearned = "सीखे जा रहे शब्द",
    vocabCategoryMastered = "महारत हासिल किए गए शब्द",
    vocabCategoryReviewDue = "अभी तक नहीं सीखे शब्द",
    vocabFlashcard = "🃏 फ्लैशकार्ड",
    tapToShowMeaning = "अर्थ देखने के लिए टैप करें",
    vocabPrev = "◀",
    frogPrevButtonHelp = "पिछला शब्द देखें",
    frogButtonHelpTitle = "शब्द कार्ड के बटन",
    frogStarButtonHelp = "पसंदीदा: पसंदीदा में जोड़कर अगले शब्द पर जाएँ",
    frogButtonHelp = "याद रहा: महारत बढ़ाकर अगले शब्द पर जाएँ",
    history = "🕐 इतिहास",
    historyEmpty = "अभी कोई इतिहास नहीं है। फ्लैशकार्ड या महारत की जाँच आज़माएँ!",
    search = "खोजें…",
    level = "स्तर: (TOEIC score)",
    language = "🌐 भाषा",
    buttonSoundOn = "बटन ध्वनि चालू",
    buttonSoundOff = "बटन ध्वनि बंद",
    speechMutedTitle = "ध्वनि म्यूट है",
    speechMutedOk = "बंद करें",
    speechMutedPronounce = "उच्चारण चलाएँ",
    premiumLevelsPrice = "कीमत",
    premiumLevelsTitle = "🔒 प्रीमियम स्तर",
    premiumLevelsDescription = "एक बार की खरीदारी से TOEIC 800+ के %d शब्द अनलॉक करें।",
    premiumLevelsPurchase = "अभी खरीदें",
    premiumLevelsRestore = "खरीदारी पुनर्स्थापित करें",
    premiumLevelsUnlocked = "प्रीमियम स्तर अनलॉक है।",
    premiumLevelsPending = "आपकी खरीदारी लंबित है। भुगतान पूरा होने के बाद यह स्तर अनलॉक हो जाएगा।",
    premiumLevelsPurchaseSuccess = "खरीदारी पूरी हुई। TOEIC 800+ अनलॉक हो गया है।",
    premiumLevelsPurchaseError = "हम खरीदारी सत्यापित नहीं कर सके। कृपया बाद में फिर कोशिश करें।",
    settings = "⚙️ सेटिंग्स",
    settingsDescription = "ऐप की भाषा और डेटा बैकअप/पुनर्स्थापना सेट करें। उच्चारण ऐक्सेंट मुख्य स्क्रीन से बदलें।",
    accent = "🎙️ उच्चारण ऐक्सेंट",
    accentDescription = "शब्दों के उच्चारण और वर्तनी को US या UK में बदलें।",
    license = "📄 लाइसेंस",
    licenseDescription = "इस ऐप में उपयोग की गई ओपन-सोर्स लाइब्रेरी की लाइसेंस जानकारी दिखाएँ।",
    tutorial = "ट्यूटोरियल देखें",
    dataMigration = "💾 डेटा प्रबंधन",
    backup = "💾 बैकअप",
    restore = "📥 पुनर्स्थापित करें",
    backupRestoreDescription = "Google Drive, USB स्टोरेज या किसी अन्य स्थान पर सहेजी गई बैकअप फ़ाइल का उपयोग करके अपना अध्ययन डेटा स्थानांतरित करें।",
    restoreConfirmationTitle = "पुनर्स्थापना की पुष्टि करें",
    restoreConfirmationMessage = "बनाने का समय: %1\$s\nशब्द: %2\$d\nइतिहास: %3\$d\nपसंदीदा: %4\$d\n\nवर्तमान अध्ययन डेटा बदल दिया जाएगा।",
    restoreConfirmationAction = "पुनर्स्थापित करें",
    restoreCompletedMessage = "पुनर्स्थापना पूरी हुई।\nशब्द: %1\$d\nइतिहास: %2\$d\nपसंदीदा: %3\$d\n\nप्रदर्शन सेटिंग लागू करने के लिए स्क्रीन फिर से लोड होगी।",
    speechPlay = "उच्चारण चलाएँ",
    speechNetworkUnavailable = "इस डिवाइस पर ऑडियो नहीं चलाया जा सकता। वॉइस डेटा या TTS सेटिंग जाँचें।",
    backupSaved = "बैकअप सहेजा गया।",
    backupSaveFailed = "बैकअप सहेजने में विफल।",
    backupReadFailed = "बैकअप पढ़ने में विफल।",
    restoreFailed = "पुनर्स्थापना विफल।",
    comingSoon = "यह सुविधा जल्द उपलब्ध होगी।",
    close = "बंद करें",
    dailyGoal = "दैनिक लक्ष्य",
    todayLearned = "आज सीखे",
    goalReached = "🎉 लक्ष्य पूरा!",
    setDailyGoal = "लक्ष्य सेट करें",
    streakAchieved = "🔥 लगातार %d दिन!",
    streakModalTitle = "🔥 स्ट्रीक पूरी!",
    streakModalMessage = "बहुत बढ़िया! आपने लगातार %d दिन पूरे किए। ऐसे ही जारी रखें!",
    streakModalOk = "जारी रखें",
    streakDialogTitle = "🔥 अपनी स्ट्रीक जारी रखें!",
    streakDialogActiveMessage = "आपकी स्ट्रीक %d दिनों की है। आज का लक्ष्य पूरा करके इसे और बढ़ाएँ!",
    streakDialogRecoveryMessage = "कल पढ़ाई छूट गई थी। आज दो दिनों जितने (%2\$d शब्द) पढ़कर अपनी %1\$d-दिन की स्ट्रीक बचाएँ।",
    streakDialogRecoveryAction = "स्ट्रीक बचाएँ",
    streakDialogRecoveredMessage = "स्ट्रीक बच गई! आपकी %d-दिन की स्ट्रीक जारी है।",
    streakRecoveryTickets = "स्ट्रीक बचाने वाले टिकट: %d",
    streakTicketRecoveryAction = "टिकट से स्ट्रीक बचाएँ",
    heatmapTitle = "🌱 अध्ययन हीटमैप",
    heatmapTotalLabel = "कुल: %d शब्द सीखे गए",
    heatmapDayCount = "%d गतिविधियाँ",
    aiChange = "बदलें",
    aiLiveGuidance = "AI ऐप खोलने के बाद Live या वॉइस मोड चालू करें। Live में उच्चारण और बातचीत का अभ्यास करने से शब्दों को याद रखना आसान होता है और सीखना अधिक मज़ेदार बनता है। Live शुरू होने के बाद, हाल ही में इस्तेमाल किए गए ऐप्स की सूची से इस शब्दावली ऐप को फिर से चुनकर पढ़ाई जारी रखें।",
    aiLaunch = "खोलें"
)

/** ベトナム語UI */
val VietnameseStrings = EnglishStrings.copy(
    languageCode = "vi",
    appName = "Từ vựng",
    all = "Tất cả",
    vocabulary = "Từ vựng",
    vocabProgress = "Tiến độ học tập",
    vocabTotal = "Tổng số từ",
    vocabLearned = "Yêu thích",
    vocabMastered = "Đã thành thạo",
    vocabReviewDue = "Chưa thành thạo",
    vocabCategoryAll = "Tất cả từ",
    vocabCategoryLearned = "Từ đang học",
    vocabCategoryMastered = "Từ đã thành thạo",
    vocabCategoryReviewDue = "Từ chưa thành thạo",
    vocabFlashcard = "🃏 Thẻ ghi nhớ",
    tapToShowMeaning = "Nhấn để xem nghĩa",
    vocabPrev = "◀",
    frogPrevButtonHelp = "Xem từ trước",
    frogButtonHelpTitle = "Các nút trên thẻ từ",
    frogStarButtonHelp = "Yêu thích: thêm vào yêu thích và chuyển sang từ tiếp theo",
    frogButtonHelp = "Đã nhớ: tăng mức thành thạo và chuyển sang từ tiếp theo",
    history = "🕐 Lịch sử",
    historyEmpty = "Chưa có lịch sử. Hãy thử thẻ ghi nhớ hoặc kiểm tra mức độ thành thạo!",
    search = "Tìm kiếm…",
    level = "Cấp độ: (TOEIC score)",
    language = "🌐 Ngôn ngữ",
    buttonSoundOn = "Đã bật âm thanh nút",
    buttonSoundOff = "Đã tắt âm thanh nút",
    speechMutedTitle = "Âm thanh đang bị tắt tiếng",
    speechMutedOk = "Đóng",
    speechMutedPronounce = "Phát âm",
    premiumLevelsPrice = "Giá",
    premiumLevelsTitle = "🔒 Cấp độ Premium",
    premiumLevelsDescription = "Mở khóa %d từ vựng TOEIC 800+ với một lần mua.",
    premiumLevelsPurchase = "Mua ngay",
    premiumLevelsRestore = "Khôi phục giao dịch mua",
    premiumLevelsUnlocked = "Cấp độ Premium đã được mở khóa.",
    premiumLevelsPending = "Giao dịch mua đang chờ xử lý. Cấp độ sẽ được mở khóa sau khi thanh toán hoàn tất.",
    premiumLevelsPurchaseSuccess = "Đã mua xong. Đã mở khóa TOEIC 800+.",
    premiumLevelsPurchaseError = "Không thể xác minh giao dịch mua. Vui lòng thử lại sau.",
    settings = "⚙️ Cài đặt",
    settingsDescription = "Thiết lập ngôn ngữ ứng dụng và sao lưu/khôi phục dữ liệu. Thay đổi giọng đọc từ màn hình chính.",
    accent = "🎙️ Giọng phát âm",
    accentDescription = "Chuyển cách phát âm và chính tả giữa US và UK.",
    license = "📄 Giấy phép",
    licenseDescription = "Xem thông tin giấy phép của các thư viện mã nguồn mở được sử dụng trong ứng dụng này.",
    tutorial = "Xem hướng dẫn",
    dataMigration = "💾 Quản lý dữ liệu",
    backup = "💾 Sao lưu",
    restore = "📥 Khôi phục",
    backupRestoreDescription = "Di chuyển dữ liệu học tập bằng tệp sao lưu được lưu trên Google Drive, bộ nhớ USB hoặc vị trí khác.",
    restoreConfirmationTitle = "Xác nhận khôi phục",
    restoreConfirmationMessage = "Được tạo: %1\$s\nTừ: %2\$d\nLịch sử: %3\$d\nYêu thích: %4\$d\n\nDữ liệu học tập hiện tại sẽ bị thay thế.",
    restoreConfirmationAction = "Khôi phục",
    restoreCompletedMessage = "Đã khôi phục.\nTừ: %1\$d\nLịch sử: %2\$d\nYêu thích: %3\$d\n\nMàn hình sẽ được tải lại để áp dụng cài đặt hiển thị.",
    speechPlay = "Nghe phát âm",
    speechNetworkUnavailable = "Không thể phát âm thanh trên thiết bị này. Hãy kiểm tra dữ liệu giọng nói hoặc cài đặt TTS.",
    backupSaved = "Đã lưu bản sao lưu.",
    backupSaveFailed = "Không thể lưu bản sao lưu.",
    backupReadFailed = "Không thể đọc bản sao lưu.",
    restoreFailed = "Khôi phục thất bại.",
    comingSoon = "Tính năng này sẽ sớm ra mắt.",
    close = "Đóng",
    dailyGoal = "Mục tiêu hằng ngày",
    todayLearned = "Đã học hôm nay",
    goalReached = "🎉 Đạt mục tiêu!",
    setDailyGoal = "Đặt mục tiêu",
    streakAchieved = "🔥 Đã học liên tục %d ngày!",
    streakModalTitle = "🔥 Đạt chuỗi học tập liên tiếp!",
    streakModalMessage = "Tuyệt vời! Bạn đã học liên tục %d ngày. Hãy tiếp tục!",
    streakModalOk = "Tiếp tục",
    streakDialogTitle = "🔥 Hãy tiếp tục chuỗi học!",
    streakDialogActiveMessage = "Bạn đang có chuỗi %d ngày. Hãy hoàn thành mục tiêu hôm nay để kéo dài chuỗi!",
    streakDialogRecoveryMessage = "Hôm qua bạn đã nghỉ. Học đủ hai ngày hôm nay (%2\$d từ) để cứu chuỗi %1\$d ngày.",
    streakDialogRecoveryAction = "Cứu chuỗi học",
    streakDialogRecoveredMessage = "Cứu thành công! Chuỗi %d ngày của bạn đang tiếp tục.",
    streakRecoveryTickets = "Vé cứu chuỗi: %d",
    streakTicketRecoveryAction = "Dùng vé để cứu chuỗi",
    heatmapTitle = "🌱 Bản đồ nhiệt học tập",
    heatmapTotalLabel = "Tổng: %d từ đã học",
    heatmapDayCount = "%d hoạt động",
    aiChange = "Thay đổi",
    aiLiveGuidance = "Sau khi mở ứng dụng AI, hãy bật Live hoặc chế độ giọng nói. Luyện phát âm và hội thoại trong Live giúp bạn nhớ từ lâu hơn và học tập thú vị hơn. Sau khi bắt đầu Live, hãy mở lại ứng dụng từ vựng này từ danh sách ứng dụng gần đây để tiếp tục học.",
    aiLaunch = "Mở"
)

/** 韓国語UI */
val KoreanStrings = EnglishStrings.copy(
    languageCode = "ko",
    appName = "단어장",
    all = "전체",
    vocabulary = "단어장",
    vocabProgress = "학습 진행률",
    vocabTotal = "전체 단어",
    vocabLearned = "즐겨찾기",
    vocabMastered = "마스터함",
    vocabReviewDue = "아직 마스터하지 않은 단어",
    vocabCategoryAll = "전체 단어",
    vocabCategoryLearned = "학습 중인 단어",
    vocabCategoryMastered = "마스터한 단어",
    vocabCategoryReviewDue = "아직 마스터하지 않은 단어",
    vocabFlashcard = "🃏 단어 카드",
    tapToShowMeaning = "탭하여 뜻 보기",
    vocabPrev = "◀",
    frogPrevButtonHelp = "이전 단어 보기",
    frogButtonHelpTitle = "단어 카드 버튼",
    frogStarButtonHelp = "즐겨찾기: 즐겨찾기에 추가하고 다음 단어로 가기",
    frogButtonHelp = "기억했어요: 숙련도를 높이고 다음 단어로 가기",
    history = "🕐 기록",
    historyEmpty = "아직 기록이 없습니다. 단어 카드나 체크를 사용해 보세요!",
    search = "검색…",
    level = "레벨: (TOEIC score)",
    language = "🌐 언어",
    buttonSoundOn = "버튼 소리 켜짐",
    buttonSoundOff = "버튼 소리 꺼짐",
    speechMutedTitle = "음소거 상태입니다",
    speechMutedOk = "닫기",
    speechMutedPronounce = "발음하기",
    premiumLevelsPrice = "가격",
    premiumLevelsTitle = "🔒 프리미엄 레벨",
    premiumLevelsDescription = "한 번 구매하면 TOEIC 800+ 단어 %d개를 잠금 해제할 수 있습니다.",
    premiumLevelsPurchase = "지금 구매",
    premiumLevelsRestore = "구매 복원",
    premiumLevelsUnlocked = "프리미엄 레벨이 잠금 해제되었습니다.",
    premiumLevelsPending = "구매가 보류 중입니다. 결제가 완료되면 레벨이 잠금 해제됩니다.",
    premiumLevelsPurchaseSuccess = "구매가 완료되었습니다. TOEIC 800+ 레벨이 잠금 해제되었습니다.",
    premiumLevelsPurchaseError = "구매를 확인할 수 없습니다. 나중에 다시 시도해 주세요.",
    settings = "⚙️ 설정",
    settingsDescription = "앱 표시 언어 및 데이터 백업/복원을 설정합니다. 발음 억양은 메인 화면에서 변경할 수 있습니다.",
    accent = "🎙️ 발음 억양",
    accentDescription = "단어 발음과 철자를 US 또는 UK로 전환합니다.",
    license = "📄 라이선스",
    licenseDescription = "이 앱에서 사용하는 오픈 소스 라이브러리의 라이선스 정보를 표시합니다.",
    tutorial = "튜토리얼 보기",
    dataMigration = "💾 데이터 관리",
    backup = "💾 백업",
    restore = "📥 복원",
    backupRestoreDescription = "Google Drive, USB 저장소 또는 다른 위치에 저장한 백업 파일로 학습 데이터를 이동합니다.",
    restoreConfirmationTitle = "복원 확인",
    restoreConfirmationMessage = "생성일: %1\$s\n단어: %2\$d개\n기록: %3\$d개\n즐겨찾기: %4\$d개\n\n현재 학습 데이터가 대체됩니다.",
    restoreConfirmationAction = "복원",
    restoreCompletedMessage = "복원이 완료되었습니다.\n단어: %1\$d개\n기록: %2\$d개\n즐겨찾기: %3\$d개\n\n표시 설정을 적용하기 위해 화면을 다시 불러옵니다.",
    speechPlay = "발음 재생",
    speechNetworkUnavailable = "이 기기에서 음성을 재생할 수 없습니다. 음성 데이터 또는 TTS 설정을 확인하세요.",
    backupSaved = "백업이 저장되었습니다.",
    backupSaveFailed = "백업을 저장하지 못했습니다.",
    backupReadFailed = "백업을 읽을 수 없습니다.",
    restoreFailed = "복원에 실패했습니다.",
    comingSoon = "이 기능은 곧 제공될 예정입니다.",
    close = "닫기",
    dailyGoal = "일일 목표",
    todayLearned = "오늘 학습",
    goalReached = "🎉 목표 달성!",
    setDailyGoal = "목표 설정",
    streakAchieved = "🔥 %d일 연속!",
    streakModalTitle = "🔥 연속 학습 달성!",
    streakModalMessage = "대단합니다! %d일 연속 학습을 달성했습니다. 계속해 보세요!",
    streakModalOk = "계속",
    streakDialogTitle = "🔥 연속 학습을 이어 가세요!",
    streakDialogActiveMessage = "%d일 연속 학습 중입니다. 오늘 목표를 달성해 기록을 늘려 보세요!",
    streakDialogRecoveryMessage = "어제 학습을 쉬었습니다. 오늘 이틀 치(%2\$d단어)를 학습하면 %1\$d일 연속 기록을 되살릴 수 있습니다.",
    streakDialogRecoveryAction = "연속 학습 되살리기",
    streakDialogRecoveredMessage = "되살리기 성공! %d일 연속 학습을 이어 가고 있습니다.",
    streakRecoveryTickets = "연속 학습 구제 티켓: %d장",
    streakTicketRecoveryAction = "티켓으로 구제하기",
    heatmapTitle = "🌱 학습 히트맵",
    heatmapTotalLabel = "합계: %d개 단어를 학습했습니다",
    heatmapDayCount = "학습 %d회",
    aiChange = "변경",
    aiLiveGuidance = "AI 앱을 연 후 Live 또는 음성 기능을 켜세요. Live에서 발음과 대화를 연습하면 단어가 더 잘 기억되고 학습도 즐거워집니다. Live를 시작한 뒤 최근 앱 목록에서 이 단어장 앱을 다시 열어 학습을 계속하세요.",
    aiLaunch = "열기"
)

/** インドネシア語UI */
val IndonesianStrings = EnglishStrings.copy(
    languageCode = "id",
    appName = "Kosakata",
    all = "Semua",
    vocabulary = "Kosakata",
    vocabProgress = "Progres Belajar",
    vocabTotal = "Total Kata",
    vocabLearned = "Favorit",
    vocabMastered = "Dikuasai",
    vocabReviewDue = "Belum Dikuasai",
    vocabCategoryAll = "Semua Kata",
    vocabCategoryLearned = "Kata yang Sedang Dipelajari",
    vocabCategoryMastered = "Kata yang Dikuasai",
    vocabCategoryReviewDue = "Kata yang Belum Dikuasai",
    vocabFlashcard = "🃏 Kartu Kata",
    tapToShowMeaning = "Ketuk untuk melihat arti",
    vocabPrev = "◀",
    frogPrevButtonHelp = "Lihat kata sebelumnya",
    frogButtonHelpTitle = "Tombol kartu kata",
    frogStarButtonHelp = "Favorit: tambahkan ke favorit dan lanjut ke kata berikutnya",
    frogButtonHelp = "Ingat: tingkatkan penguasaan dan lanjut ke kata berikutnya",
    history = "🕐 Riwayat",
    historyEmpty = "Belum ada riwayat. Coba kartu kata atau centang penguasaan!",
    search = "Cari…",
    level = "Level: (TOEIC score)",
    language = "🌐 Bahasa",
    buttonSoundOn = "Suara tombol aktif",
    buttonSoundOff = "Suara tombol nonaktif",
    speechMutedTitle = "Suara dibisukan",
    speechMutedOk = "Tutup",
    speechMutedPronounce = "Putar pengucapan",
    premiumLevelsPrice = "Harga",
    premiumLevelsTitle = "🔒 Level Premium",
    premiumLevelsDescription = "Buka %d kata TOEIC 800+ dengan satu kali pembelian.",
    premiumLevelsPurchase = "Beli Sekarang",
    premiumLevelsRestore = "Pulihkan Pembelian",
    premiumLevelsUnlocked = "Level premium telah dibuka.",
    premiumLevelsPending = "Pembelian sedang diproses. Level akan terbuka setelah pembayaran selesai.",
    premiumLevelsPurchaseSuccess = "Pembelian selesai. Level TOEIC 800+ telah dibuka.",
    premiumLevelsPurchaseError = "Tidak dapat memverifikasi pembelian. Silakan coba lagi nanti.",
    settings = "⚙️ Pengaturan",
    settingsDescription = "Atur bahasa tampilan aplikasi serta cadangan/pemulihan data. Ubah aksen pengucapan dari layar utama.",
    accent = "🎙️ Aksen Pengucapan",
    accentDescription = "Beralih antara pengucapan dan ejaan bahasa Inggris AS (US) dan Inggris Raya (UK).",
    license = "📄 Lisensi",
    licenseDescription = "Tampilkan informasi lisensi pustaka sumber terbuka yang digunakan dalam aplikasi ini.",
    tutorial = "Lihat tutorial",
    dataMigration = "💾 Manajemen Data",
    backup = "💾 Cadangkan",
    restore = "📥 Pulihkan",
    backupRestoreDescription = "Pindahkan data belajar menggunakan file cadangan yang disimpan di Google Drive, penyimpanan USB, atau lokasi lain.",
    restoreConfirmationTitle = "Konfirmasi pemulihan",
    restoreConfirmationMessage = "Dibuat: %1\$s\nKata: %2\$d\nRiwayat: %3\$d\nFavorit: %4\$d\n\nData belajar saat ini akan diganti.",
    restoreConfirmationAction = "Pulihkan",
    restoreCompletedMessage = "Pemulihan selesai.\nKata: %1\$d\nRiwayat: %2\$d\nFavorit: %3\$d\n\nLayar akan dimuat ulang untuk menerapkan pengaturan tampilan.",
    speechPlay = "Putar pengucapan",
    speechNetworkUnavailable = "Audio tidak dapat diputar di perangkat ini. Periksa data suara atau pengaturan TTS.",
    backupSaved = "Cadangan disimpan.",
    backupSaveFailed = "Gagal menyimpan cadangan.",
    backupReadFailed = "Gagal membaca cadangan.",
    restoreFailed = "Pemulihan gagal.",
    comingSoon = "Fitur ini akan segera tersedia.",
    close = "Tutup",
    streakDays = "Hari",
    dailyGoal = "Target Harian",
    todayLearned = "Dipelajari Hari Ini",
    goalReached = "🎉 Target Tercapai!",
    setDailyGoal = "Atur Target",
    streakAchieved = "🔥 Streak %d hari!",
    streakModalTitle = "🔥 Streak Tercapai!",
    streakModalMessage = "Luar biasa! Anda telah belajar %d hari berturut-turut. Pertahankan!",
    streakModalOk = "Lanjutkan",
    streakDialogTitle = "🔥 Lanjutkan streak Anda!",
    streakDialogActiveMessage = "Anda memiliki streak %d hari. Capai target hari ini untuk memperpanjangnya!",
    streakDialogRecoveryMessage = "Kemarin Anda tidak belajar. Pelajari dua hari hari ini (%2\$d kata) untuk menyelamatkan streak %1\$d hari Anda.",
    streakDialogRecoveryAction = "Selamatkan streak",
    streakDialogRecoveredMessage = "Berhasil diselamatkan! Streak %d hari Anda berlanjut.",
    streakRecoveryTickets = "Tiket penyelamat streak: %d",
    streakTicketRecoveryAction = "Gunakan tiket untuk menyelamatkan",
    heatmapTitle = "🌱 Peta Panas Belajar",
    heatmapTotalLabel = "Total: %d kata dipelajari",
    heatmapDayCount = "%d aktivitas",
    aiChange = "Ubah",
    aiLiveGuidance = "Setelah membuka aplikasi AI, aktifkan Live atau mode suara. Berlatih pengucapan dan percakapan di Live membantu Anda mengingat kata-kata dengan lebih mudah dan membuat belajar lebih menyenangkan. Setelah Live dimulai, buka kembali aplikasi kosakata ini dari daftar aplikasi terbaru untuk melanjutkan belajar.",
    aiLaunch = "Buka"
)

/** ภาษาไทย UI */
val ThaiStrings = EnglishStrings.copy(
    languageCode = "th",
    languageThai = "ไทย",
    appName = "สมุดคำศัพท์",
    all = "ทั้งหมด",
    vocabulary = "สมุดคำศัพท์",
    vocabProgress = "ความคืบหน้าการเรียน",
    vocabTotal = "จำนวนคำศัพท์ทั้งหมด",
    vocabLearned = "รายการโปรด",
    vocabMastered = "จำได้แล้ว",
    vocabReviewDue = "ยังจำไม่ได้",
    vocabCategoryAll = "คำศัพท์ทั้งหมด",
    vocabCategoryLearned = "คำศัพท์ที่กำลังเรียน",
    vocabCategoryMastered = "คำศัพท์ที่จำได้แล้ว",
    vocabCategoryReviewDue = "คำศัพท์ที่ยังจำไม่ได้",
    vocabFlashcard = "🃏 บัตรคำศัพท์",
    tapToShowMeaning = "แตะเพื่อดูความหมาย",
    vocabPrev = "◀",
    frogPrevButtonHelp = "ดูคำก่อนหน้า",
    frogButtonHelpTitle = "ปุ่มบนบัตรคำศัพท์",
    frogStarButtonHelp = "รายการโปรด: เพิ่มในรายการโปรดแล้วไปคำถัดไป",
    frogButtonHelp = "จำได้: เพิ่มระดับความชำนาญแล้วไปคำถัดไป",
    history = "🕐 ประวัติการเรียน",
    historyEmpty = "ยังไม่มีประวัติการเรียน ลองใช้บัตรคำศัพท์หรือทบทวนคำศัพท์ดูสิ!",
    search = "ค้นหา…",
    level = "ระดับ: (TOEIC score)",
    language = "🌐 ภาษา",
    buttonSoundOn = "เปิดเสียงปุ่มแล้ว",
    buttonSoundOff = "ปิดเสียงปุ่มแล้ว",
    speechMutedTitle = "ปิดเสียงอยู่",
    speechMutedOk = "ปิด",
    speechMutedPronounce = "เล่นการออกเสียง",
    premiumLevelsPrice = "ราคา",
    premiumLevelsTitle = "🔒 ระดับพรีเมียม",
    premiumLevelsDescription = "ปลดล็อกคำศัพท์ TOEIC 800+ จำนวน %d คำได้ด้วยการซื้อครั้งเดียว",
    premiumLevelsPurchase = "ซื้อเลย",
    premiumLevelsRestore = "กู้คืนการซื้อ",
    premiumLevelsUnlocked = "ปลดล็อกระดับพรีเมียมแล้ว",
    premiumLevelsPending = "กำลังดำเนินการซื้อ ระดับนี้จะปลดล็อกหลังชำระเงินเสร็จสิ้น",
    premiumLevelsPurchaseSuccess = "ซื้อสำเร็จ ปลดล็อกระดับ TOEIC 800+ แล้ว",
    premiumLevelsPurchaseError = "ไม่สามารถยืนยันการซื้อได้ โปรดลองอีกครั้งภายหลัง",
    settings = "⚙️ การตั้งค่า",
    settingsDescription = "ตั้งค่าภาษาที่แสดงของแอปและการสำรอง/กู้คืนข้อมูล เปลี่ยนสำเนียงการออกเสียงได้จากหน้าหลัก",
    accent = "🎙️ สำเนียงการออกเสียง",
    accentDescription = "สลับการออกเสียงและการสะกดคำระหว่าง US และ UK",
    license = "📄 ใบอนุญาต",
    licenseDescription = "แสดงข้อมูลใบอนุญาตของไลบรารีโอเพนซอร์สที่ใช้ในแอปนี้",
    tutorial = "ดูบทช่วยสอน",
    dataMigration = "💾 การจัดการข้อมูล",
    backup = "💾 สำรองข้อมูล",
    restore = "📥 กู้คืน",
    backupRestoreDescription = "ย้ายข้อมูลการเรียนด้วยไฟล์สำรองที่บันทึกไว้ใน Google Drive, USB หรือที่อื่น",
    restoreConfirmationTitle = "ยืนยันการกู้คืน",
    restoreConfirmationMessage = "สร้างเมื่อ: %1\$s\nคำศัพท์: %2\$d\nประวัติ: %3\$d\nรายการโปรด: %4\$d\n\nข้อมูลการเรียนปัจจุบันจะถูกแทนที่",
    restoreConfirmationAction = "กู้คืน",
    restoreCompletedMessage = "กู้คืนเสร็จแล้ว\nคำศัพท์: %1\$d\nประวัติ: %2\$d\nรายการโปรด: %3\$d\n\nหน้าจอจะโหลดใหม่เพื่อใช้การตั้งค่าภาษา",
    speechPlay = "เล่นการออกเสียง",
    speechNetworkUnavailable = "ไม่สามารถเล่นเสียงบนอุปกรณ์นี้ได้ โปรดตรวจสอบข้อมูลเสียงหรือการตั้งค่า TTS",
    backupSaved = "บันทึกข้อมูลสำรองแล้ว",
    backupSaveFailed = "บันทึกข้อมูลสำรองไม่สำเร็จ",
    backupReadFailed = "อ่านข้อมูลสำรองไม่ได้",
    restoreFailed = "กู้คืนไม่สำเร็จ",
    comingSoon = "ฟีเจอร์นี้กำลังจะเปิดให้ใช้งาน",
    close = "ปิด",
    streakDays = "วัน",
    dailyGoal = "เป้าหมายรายวัน",
    todayLearned = "เรียนไปแล้ววันนี้",
    goalReached = "🎉 บรรลุเป้าหมายแล้ว!",
    setDailyGoal = "ตั้งเป้าหมาย",
    streakAchieved = "🔥 เรียนต่อเนื่อง %d วัน!",
    streakModalTitle = "🔥 เรียนต่อเนื่องสำเร็จ!",
    streakModalMessage = "ยอดเยี่ยม! คุณเรียนต่อเนื่องครบ %d วันแล้ว ทำต่อไปนะ!",
    streakModalOk = "ดำเนินการต่อ",
    streakDialogTitle = "🔥 รักษาสตรีคของคุณต่อไป!",
    streakDialogActiveMessage = "คุณเรียนต่อเนื่องมาแล้ว %d วัน ทำเป้าหมายวันนี้ให้สำเร็จเพื่อเพิ่มสตรีค!",
    streakDialogRecoveryMessage = "เมื่อวานคุณไม่ได้เรียน วันนี้เรียนให้ได้สองวัน (%2\$d คำ) เพื่อกู้สตรีค %1\$d วันกลับมา",
    streakDialogRecoveryAction = "กู้สตรีค",
    streakDialogRecoveredMessage = "กู้คืนสำเร็จ! สตรีค %d วันของคุณยังดำเนินต่อไป",
    streakRecoveryTickets = "ตั๋วกู้สตรีค: %d ใบ",
    streakTicketRecoveryAction = "ใช้ตั๋วกู้สตรีค",
    heatmapTitle = "🌱 ฮีตแมปการเรียนรู้",
    heatmapTotalLabel = "รวม: เรียนแล้ว %d คำ",
    heatmapDayCount = "%d กิจกรรม",
    aiChange = "เปลี่ยน",
    aiLiveGuidance = "หลังจากเปิดแอป AI แล้ว ให้เปิด Live หรือโหมดเสียง การฝึกออกเสียงและสนทนาใน Live ช่วยให้จำคำศัพท์ได้ง่ายขึ้นและเรียนได้สนุกขึ้น เมื่อเริ่ม Live แล้ว ให้เปิดแอปคำศัพท์นี้อีกครั้งจากรายการแอปที่ใช้ล่าสุดเพื่อเรียนต่อ",
    aiLaunch = "เปิด"
)

/** Spanish UI */
val SpanishStrings = EnglishStrings.copy(
    languageCode = "es",
    languageJapanese = "Japonés",
    languageEnglish = "Inglés",
    languageChinese = "Chino",
    languageHindi = "Hindi",
    languageVietnamese = "Vietnamita",
    languageKorean = "Coreano",
    languageIndonesian = "Indonesio",
    languageThai = "Tailandés",
    languageSpanish = "Español",
    appName = "Vocabulario",
    all = "Todo",
    vocabulary = "Vocabulario",
    vocabProgress = "Progreso de aprendizaje",
    vocabTotal = "Palabras totales",
    vocabLearned = "Favoritos",
    vocabMastered = "Dominadas",
    vocabReviewDue = "No dominadas",
    vocabCategoryAll = "Todas las palabras",
    vocabCategoryLearned = "Palabras en progreso",
    vocabCategoryMastered = "Palabras dominadas",
    vocabCategoryReviewDue = "Palabras no dominadas",
    vocabFlashcard = "🃏 Tarjetas de vocabulario",
    tapToShowMeaning = "Toca para ver el significado",
    vocabPrev = "◀",
    frogPrevButtonHelp = "Ver la palabra anterior",
    frogButtonHelpTitle = "Botones de la tarjeta",
    frogStarButtonHelp = "Favorita: añádela a favoritos y pasa a la siguiente",
    frogButtonHelp = "La recuerdas: sube el nivel y pasa a la siguiente",
    history = "🕐 Historial",
    historyEmpty = "Aún no hay historial. ¡Prueba las tarjetas o las comprobaciones de dominio!",
    search = "Buscar…",
    level = "Nivel: (puntuación TOEIC)",
    language = "🌐 Idioma",
    speechPlay = "Reproducir pronunciación",
    speechNetworkUnavailable = "No se puede reproducir el audio en este dispositivo. Comprueba los datos de voz o la configuración de TTS.",
    buttonSoundOn = "Sonidos de botones activados",
    buttonSoundOff = "Sonidos de botones desactivados",
    speechMutedTitle = "El sonido está silenciado",
    speechMutedOk = "Cerrar",
    speechMutedPronounce = "Pronunciar",
    premiumLevelsPrice = "Precio",
    premiumLevelsTitle = "🔒 Nivel premium",
    premiumLevelsDescription = "Desbloquea %d palabras de TOEIC 800+ con una compra única.",
    premiumLevelsPurchase = "Comprar ahora",
    premiumLevelsRestore = "Restaurar compra",
    premiumLevelsUnlocked = "El nivel premium está desbloqueado.",
    premiumLevelsPending = "La compra está pendiente. El nivel se desbloqueará cuando se complete el pago.",
    premiumLevelsPurchaseSuccess = "Compra completada. El nivel TOEIC 800+ está desbloqueado.",
    premiumLevelsPurchaseError = "No se pudo verificar la compra. Inténtalo de nuevo más tarde.",
    settings = "⚙️ Ajustes",
    settingsDescription = "Configura el idioma de la aplicación y la copia de seguridad/restauración de datos. Cambia el acento de pronunciación desde la pantalla principal.",
    accent = "🎙️ Acento de pronunciación",
    accentDescription = "Cambia la pronunciación y la ortografía entre inglés estadounidense y británico.",
    license = "📄 Licencias",
    licenseDescription = "Muestra la información de licencia de las bibliotecas de código abierto utilizadas en esta aplicación.",
    tutorial = "Ver tutorial",
    dataMigration = "💾 Gestión de datos",
    backup = "💾 Copia de seguridad",
    restore = "📥 Restaurar",
    backupRestoreDescription = "Transfiere tus datos de estudio mediante un archivo guardado en Google Drive, una memoria USB u otra ubicación.",
    restoreConfirmationTitle = "Confirmar restauración",
    restoreConfirmationMessage = "Creado: %1\$s\nPalabras: %2\$d\nHistorial: %3\$d\nFavoritos: %4\$d\n\nSe reemplazarán los datos de estudio actuales.",
    restoreConfirmationAction = "Restaurar",
    restoreCompletedMessage = "Restauración completada.\nPalabras: %1\$d\nHistorial: %2\$d\nFavoritos: %3\$d\n\nLa pantalla se volverá a cargar para aplicar los ajustes de visualización.",
    backupSaved = "Copia de seguridad guardada.",
    backupSaveFailed = "No se pudo guardar la copia de seguridad.",
    backupReadFailed = "No se pudo leer la copia de seguridad.",
    restoreFailed = "No se pudo restaurar.",
    comingSoon = "Esta función estará disponible próximamente.",
    close = "Cerrar",
    streakDays = "Días seguidos",
    dailyGoal = "Objetivo diario",
    todayLearned = "Aprendidas hoy",
    goalReached = "🎉 ¡Objetivo alcanzado!",
    setDailyGoal = "Establecer objetivo",
    streakAchieved = "🔥 ¡%d días seguidos!",
    streakModalTitle = "🔥 ¡Racha alcanzada!",
    streakModalMessage = "¡Excelente! Has estudiado durante %d días seguidos. ¡Sigue así!",
    streakModalOk = "Continuar",
    streakDialogTitle = "🔥 ¡Mantén tu racha!",
    streakDialogActiveMessage = "Llevas una racha de %d días. ¡Alcanza el objetivo de hoy para alargarla!",
    streakDialogRecoveryMessage = "Ayer no estudiaste. Estudia el equivalente a dos días hoy (%2\$d palabras) para recuperar tu racha de %1\$d días.",
    streakDialogRecoveryAction = "Recuperar racha",
    streakDialogRecoveredMessage = "¡Recuperación exitosa! Tu racha de %d días continúa.",
    streakRecoveryTickets = "Billetes de recuperación: %d",
    streakTicketRecoveryAction = "Usar un billete para recuperar",
    heatmapTitle = "🌱 Mapa de aprendizaje",
    heatmapTotalLabel = "Total: %d palabras estudiadas",
    heatmapDayCount = "%d actividades",
    aiApps = "Aplicaciones de IA",
    aiChange = "Cambiar",
    aiLiveGuidance = "Después de abrir la aplicación de IA, activa Live o el modo de voz. Practicar la pronunciación y conversar en Live te ayuda a recordar mejor las palabras y hace que el aprendizaje sea más divertido. Cuando inicies Live, vuelve a abrir esta aplicación desde la lista de aplicaciones recientes y continúa estudiando.",
    aiLaunch = "Abrir",
    aiNoInstalledApps = "ChatGPT y Gemini no están instalados.",
    aiLaunchFailed = "No se pudo abrir esta aplicación de IA."
)

/** 言語の選択肢 */
enum class AppLanguage(val code: String, val nativeDisplayName: String) {
    English("en", "English"),
    Japanese("ja", "日本語"),
    Chinese("zh", "简体中文"),
    Hindi("hi", "हिन्दी"),
    Vietnamese("vi", "Tiếng Việt"),
    Korean("ko", "한국어"),
    Indonesian("id", "Bahasa Indonesia"),
    Thai("th", "ไทย"),
    Spanish("es", "Español");

    companion object {
        /** 保存値やバックアップ値をアプリで扱える言語に正規化する。 */
        fun fromCode(code: String?): AppLanguage {
            val baseCode = code
                ?.trim()
                ?.lowercase(Locale.ROOT)
                ?.substringBefore('-')
                ?.substringBefore('_')
                // 一部環境のインドネシア語ロケールは古いコード "in" を報告することがある。
                ?.let { if (it == "in") "id" else it }

            return entries.firstOrNull { it.code == baseCode } ?: Japanese
        }

        /** 端末ロケールに対応するアプリ言語を返す。未対応なら null。 */
        fun fromLocale(locale: Locale): AppLanguage? =
            entries.firstOrNull {
                it.code == locale.language.lowercase(Locale.ROOT)
                    .let { lang -> if (lang == "in") "id" else lang }
            }
    }
}

/** 発音アクセント（TOEICはアメリカ英語が基本のため US がデフォルト） */
enum class AccentMode(val code: String, val ttsLang: String) {
    US("US", "en-US"),
    UK("UK", "en-GB")
}

/** 現在の言語の文字列を提供する CompositionLocal */
val LocalAppStrings = compositionLocalOf { JapaneseStrings }

/** 現在の発音アクセント（US / UK）を提供する CompositionLocal（デフォルト: US） */
val LocalAccentMode = compositionLocalOf { AccentMode.US }
