#!/usr/bin/env python3
"""Review 300 TOEIC 600+ examples (items 701-1000) in English and Japanese."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"

EN = {
    "milk": "The hotel ordered fresh milk for the conference breakfast.",
    "talent": "The company developed a program to retain talented employees.",
    "smell": "The safety officer noticed a burning smell near the machine.",
    "prior": "The client had prior experience with our delivery service.",
    "priority": "Customer safety is our highest priority.",
    "online": "The IT department monitored the online ordering system after the update.",
    "phrase": "Please use the phrase exactly as it appears in the contract.",
    "pilot": "The company will pilot the new scheduling system at one branch.",
    "stable": "The supplier has maintained stable prices this quarter.",
    "merely": "The discount is not merely a marketing offer; it reduces the final cost.",
    "resolution": "The customer accepted the proposed resolution to the complaint.",
    "vast": "The company has a vast network of overseas suppliers.",
    "producer": "The producer delivered the advertising video before the deadline.",
    "regional": "The regional manager will visit the branch next week.",
    "slip": "Please slip the completed form under the manager's door.",
    "politician": "The visiting politician spoke about support for local businesses.",
    "seed": "The company provided seed funding for a small local business.",
    "salary": "The new position offers a competitive salary and benefits.",
    "temporary": "The company hired temporary staff during the busy season.",
    "qualify": "Applicants must qualify for the discount by ordering in advance.",
    "truly": "The new service is truly useful for small businesses.",
    "yellow": "Use the yellow label for packages that require special handling.",
    "self": "The training encourages employees to evaluate their own performance.",
    "metal": "The factory recycles scrap metal from the production line.",
    "panel": "An expert panel reviewed the proposals from the suppliers.",
    "prime": "The store is in a prime location near the station.",
    "maximum": "The maximum order quantity is listed on the website.",
    "sharp": "There was a sharp increase in orders after the advertisement aired.",
    "motion": "The board approved a motion to extend the contract.",
    "plastic": "The cafeteria replaced plastic cups with reusable ones.",
    "passage": "The contract contains a passage about late-payment fees.",
    "reputation": "The company has a strong reputation for reliable service.",
    "negotiation": "The negotiation continued after both sides reviewed the proposal.",
    "mechanism": "The manual explains the mechanism that controls the machine.",
    "pocket": "The compact scanner fits easily in a technician's pocket.",
    "observation": "The inspector recorded an observation about the damaged packaging.",
    "meat": "The restaurant added a meat option to its conference menu.",
    "unusual": "The unusually high demand required an additional shipment.",
    "repair": "The technician will repair the printer this afternoon.",
    "soul": "The founder's vision remains the soul of the company.",
    "presidential": "The hotel prepared a presidential suite for the visiting leader.",
    "perfectly": "The revised schedule fits the client's availability perfectly.",
    "proud": "The team is proud of its record for on-time delivery.",
    "educational": "The company produced educational materials for its customers.",
    "substantial": "The project requires a substantial investment in new equipment.",
    "nearby": "Employees can use the nearby parking lot after six o'clock.",
    "manufacturer": "The manufacturer will repair products that fail during the warranty period.",
    "slide": "The presenter added a slide comparing the two pricing plans.",
    "valuable": "The survey provided valuable information about customer needs.",
    "personally": "Personally, I recommend the morning appointment for the client.",
    "reporter": "The reporter interviewed the CEO about the company's expansion.",
    "shirt": "The uniform includes a blue shirt with the company logo.",
    "winner": "The winner of the design contest will receive a cash prize.",
    "partly": "The delay was partly caused by a shortage of drivers.",
    "tennis": "The hotel has a tennis court for guests and business travelers.",
    "urban": "The company opened an urban delivery center near the train station.",
    "southern": "The southern branch handles shipments to three countries.",
    "output": "The factory increased its output after installing new equipment.",
    "massive": "The storm caused massive damage to the distribution center.",
    "mouse": "The IT team replaced the wireless mouse at the reception desk.",
    "mathematics": "The analyst used mathematics to verify the financial forecast.",
    "upper": "The upper floor is reserved for visiting executives.",
    "occupy": "The new equipment will occupy most of the storage area.",
    "outline": "The proposal outlines the steps for improving customer service.",
    "sufficient": "The warehouse has sufficient space for next month's inventory.",
    "update": "Please update the customer record after the call.",
    "preserve": "The archive preserves copies of all signed contracts.",
    "split": "The manager split the order into two shipments.",
    "swing": "Sales figures can swing widely during the holiday season.",
    "sudden": "A sudden power outage stopped production for an hour.",
    "originally": "The meeting was originally scheduled for Tuesday.",
    "secondly": "First, review the invoice; secondly, confirm the payment date.",
    "severe": "Severe weather delayed flights to the regional office.",
    "prospect": "The sales representative called a promising prospect.",
    "snow": "Heavy snow closed the road to the warehouse.",
    "plot": "The architect prepared a plot plan for the new office building.",
    "neck": "The employee reported neck pain after working at the desk all day.",
    "primarily": "The service is primarily designed for small retailers.",
    "retain": "The loyalty program helps the company retain customers.",
    "sequence": "The manual shows the correct sequence for starting the machine.",
    "plain": "The instructions are written in plain language.",
    "volunteer": "Employees may volunteer at the company's community event.",
    "rural": "The company expanded delivery service to rural areas.",
    "silence": "The manager asked for silence during the safety briefing.",
    "rapidly": "Online orders have grown rapidly since the new website launched.",
    "revolution": "The new payment system could revolutionize small-business banking.",
    "spell": "Please spell the customer's name exactly as it appears on the account.",
    "premise": "The proposal is based on the premise that demand will remain strong.",
    "protein": "The cafeteria added a protein option to the lunch menu.",
    "unemployment": "The report examines how unemployment affects local businesses.",
    "wheel": "The technician replaced a damaged wheel on the delivery cart.",
    "minority": "The company created a program to support minority-owned suppliers.",
    "origin": "The customs form identifies the origin of each product.",
    "educate": "The campaign aims to educate customers about the new service.",
    "toy": "The retailer recalled a toy that did not meet safety standards.",
    "minor": "A minor change to the agenda moved the performance review to Friday.",
    "storm": "The storm delayed deliveries across the region.",
    "thick": "The package needs thick padding to protect the glass equipment.",
    "negotiate": "The purchasing manager will negotiate the contract tomorrow.",
    "supplier": "The office cafeteria chose a local supplier for fresh vegetables.",
    "prize": "The employee received a prize for suggesting the cost-saving idea.",
    "typically": "The branch typically processes orders within one business day.",
    "peer": "A peer reviewed the sales manager's presentation before the meeting.",
    "pension": "The company explains pension options during the benefits meeting.",
    "wing": "The new office occupies the east wing of the building.",
    "recognition": "The employee received recognition for excellent customer service.",
    "roof": "The contractor repaired the roof before the rainy season.",
    "retirement": "The company held a reception to celebrate her retirement.",
    "respectively": "The two branches reported sales of two million and three million dollars, respectively.",
    "variation": "The report explains the seasonal variation in demand.",
    "ultimately": "The board will ultimately decide whether to approve the proposal.",
    "proof": "The auditor requested proof of payment from the supplier.",
    "soil": "The landscaping company tested the soil before planting trees.",
    "smart": "The smart payment terminal accepts several currencies.",
    "upset": "The client was upset when the order arrived damaged.",
    "tooth": "The employee visited the dentist because of a painful tooth.",
    "representation": "The union requested representation during the negotiations.",
    "preparation": "Careful preparation helped the team deliver a successful presentation.",
    "silver": "The hotel uses silver trays for formal business dinners.",
    "undertake": "The contractor agreed to undertake the renovation next month.",
    "retail": "The company sells its products through retail stores and its website.",
    "wire": "The customer will wire the payment after receiving the invoice.",
    "unlikely": "It is unlikely that the shipment will arrive before Monday.",
    "publication": "The company prepared a publication for its annual meeting.",
    "slight": "There was a slight delay in processing the payment.",
    "unknown": "The cause of the equipment failure remains unknown.",
    "zone": "Smoking is prohibited in the loading zone.",
    "restrict": "The policy restricts access to confidential files.",
    "trace": "The technician traced the network problem to a faulty cable.",
    "solid": "The company has a solid relationship with its main supplier.",
    "owe": "The client still owes the company payment for the completed work.",
    "uniform": "All warehouse employees must wear a uniform and safety shoes.",
    "port": "The shipment will leave the port on Friday.",
    "pitch": "The sales team will pitch the new service to several clients.",
    "specialist": "A software specialist helped the team solve the problem.",
    "profile": "The company created a customer profile for the new account.",
    "mood": "The manager's positive mood encouraged the team before the launch.",
    "numerous": "The report identified numerous opportunities to reduce costs.",
    "submit": "Please submit the application before the deadline.",
    "symptom": "A persistent cough can be a symptom of several infections.",
    "virtually": "The training session was held virtually for overseas employees.",
    "tension": "The mediator helped reduce tension during the contract dispute.",
    "sensitive": "The manager handled the sensitive customer information carefully.",
    "nervous": "The new employee felt nervous before making the client presentation.",
    "prisoner": "The contractor completed the security upgrade at the prison.",
    "tight": "The project is working under a tight deadline.",
    "wet": "Keep the documents dry if the package becomes wet.",
    "secondary": "The secondary entrance is closed during construction.",
    "welfare": "The company improved employee welfare by adding flexible leave.",
    "recruit": "The company plans to recruit additional sales staff.",
    "string": "The system stores the order number as a string of characters.",
    "persuade": "The representative persuaded the client to renew the contract.",
    "phenomenon": "Seasonal demand is a common phenomenon in the retail industry.",
    "pupil": "The company donated computers to a local pupil support program.",
    "restore": "The IT team restored the files from the latest backup.",
    "perceive": "Customers perceive the brand as reliable and professional.",
    "routine": "The technician completed the routine inspection before opening.",
    "sink": "The maintenance worker repaired the sink in the staff kitchen.",
    "stare": "Please do not stare at customers while they are completing the form.",
    "supporter": "The campaign received support from an influential business supporter.",
    "steady": "The company has achieved steady growth over the past year.",
    "meter": "The technician checked the electricity meter in the warehouse.",
    "truck": "The delivery truck arrived at the loading dock at eight.",
    "nose": "The aircraft's nose was damaged during the hard landing.",
    "sail": "The vessel will sail from the port after the inspection.",
    "pace": "The team increased the pace of production to meet demand.",
    "terrorist": "The security briefing covered procedures for reporting a terrorist threat.",
    "vital": "Accurate customer records are vital to the support team.",
    "spare": "The technician kept a spare cable in the equipment cabinet.",
    "whenever": "Please contact the help desk whenever the system shows an error.",
    "underlie": "Trust and transparency underlie the company's relationship with clients.",
    "mom": "My mom mailed my winter coat before the first snow reached the city.",
    "satisfaction": "The survey measures customer satisfaction after delivery.",
    "pour": "Please pour the cleaning solution into the marked container.",
    "sweep": "The new technology is expected to sweep through the logistics industry.",
    "obligation": "The supplier has an obligation to protect customer data.",
    "sir": "The receptionist said, \"Good morning, sir, your visitor is waiting.\"",
    "pub": "The hotel recommended a nearby pub for the visitors' dinner.",
    "perception": "The campaign changed customers' perception of the brand.",
    "naturally": "The new process naturally reduced the amount of paperwork.",
    "territory": "The sales representative is responsible for the northern territory.",
    "stream": "The company launched a live stream of the product demonstration.",
    "rarely": "The branch rarely receives complaints about delivery times.",
    "western": "The company opened a branch in the western region.",
    "muscle": "The employee strained a muscle while moving a heavy carton.",
    "scare": "The power outage scared several visitors in the building.",
    "ratio": "The report shows a healthy ratio of new to returning customers.",
    "scream": "The alarm may scream if the emergency door is opened.",
    "withdraw": "The supplier decided to withdraw its proposal from the bidding process.",
    "pollution": "The factory installed filters to reduce air pollution.",
    "symbol": "The green symbol indicates that the product is recyclable.",
    "platform": "The company sells the service through an online platform.",
    "steel": "The contractor used steel beams for the warehouse expansion.",
    "transform": "The new software will transform the way the team manages orders.",
    "wound": "The workplace nurse cleaned the employee's wound.",
    "restriction": "The airport introduced a restriction on liquids in carry-on bags.",
    "strain": "Long hours placed a strain on the small support team.",
    "singer": "The singer performed at the company's anniversary event.",
    "trail": "The delivery driver followed a trail of signs to the remote site.",
    "trap": "The safety team set a trap to catch the animal near the warehouse.",
    "wealth": "The report examines how personal wealth affects consumer spending.",
    "tank": "The technician inspected the fuel tank before the delivery vehicle left.",
    "remarkable": "The company achieved remarkable growth in its overseas sales.",
    "tune": "The technician tuned the conference room's audio system before the presentation.",
    "transition": "The company provided training during the transition to the new system.",
    "stem": "The manager traced the problem to the stem of the valve.",
    "reverse": "The bank may reverse the charge if the transaction was unauthorized.",
    "mode": "The team selected online mode for the training session.",
    "mirror": "The sales figures mirror the strong demand reported by retailers.",
    "pose": "The damaged wiring may pose a safety risk.",
    "nowadays": "Nowadays, many customers prefer to receive invoices electronically.",
    "poem": "The company printed a poem in the employee newsletter.",
    "vegetable": "The cafeteria added a vegetable option to the lunch menu.",
    "van": "The office van takes supplies to the regional branch every morning.",
    "planet": "The company reduced packaging waste to protect the planet.",
    "overcome": "The team overcame the delivery problem through careful planning.",
    "web": "The customer completed the application on the company's web portal.",
    "portion": "The restaurant prepared a smaller portion for the meeting guest.",
    "substance": "The safety sheet identifies the hazardous substance in the cleaner.",
    "sugar": "The café offers drinks with no added sugar.",
    "pink": "The marketing team chose pink for the product's seasonal packaging.",
    "shadow": "The new contract casts a shadow over the company's expansion plans.",
    "strip": "The technician removed a strip of damaged insulation.",
    "smooth": "The coordinator ensured a smooth registration process.",
    "vice": "The vice president approved the revised budget.",
    "radical": "The company made a radical change to its return policy.",
    "similarly": "Similarly, the eastern branch reported higher customer satisfaction.",
    "subsequent": "The subsequent meeting focused on the contract details.",
    "efficiency": "Better energy efficiency can reduce the operating costs of the office.",
    "statistic": "The report includes a statistic showing a rise in online sales.",
    "broadcast": "The company will broadcast the product announcement online.",
    "ally": "The distributor became an important ally in the overseas market.",
    "mature": "The mature market requires a different pricing strategy.",
    "disturb": "Please do not disturb the visitors during the presentation.",
    "sustain": "The new contract will sustain growth in the regional market.",
    "poverty": "The company supports programs that help reduce poverty in the community.",
    "cite": "Please cite the original report in the proposal.",
    "parallel": "The two teams ran parallel projects to test different solutions.",
    "gender": "The survey asks for gender information on a voluntary basis.",
    "sponsor": "The company agreed to sponsor the local business conference.",
    "burden": "The new software reduces the administrative burden on staff.",
    "shareholder": "The shareholder asked about the company's expansion plans.",
    "resistance": "Electrical resistance can limit the current in a circuit.",
    "frequency": "The manager increased the frequency of safety inspections.",
    "philosophy": "The company's philosophy emphasizes excellent customer service.",
    "attribute": "The manager attributes the sales increase to the new campaign.",
    "approval": "The board granted approval for the expansion.",
    "entitle": "This membership entitles customers to free standard delivery.",
    "involvement": "The project succeeded because of the involvement of every department.",
    "exposure": "The campaign increased the brand's exposure in the regional market.",
    "conventional": "The company replaced conventional forms with a digital process.",
    "formation": "The formation of the new department will take place in April.",
    "deposit": "The hotel requires a deposit to confirm the reservation.",
    "advocate": "The customer advocate helped resolve the billing problem.",
    "establishment": "The establishment of the new branch created twenty jobs.",
    "summary": "The manager distributed a summary of the meeting.",
    "characterize": "The report characterizes the market as highly competitive.",
    "specify": "The contract specifies the delivery date and payment terms.",
    "anticipate": "We anticipate higher demand during the holiday season.",
    "dependent": "The branch is dependent on the central office for technical support.",
    "specialize": "The company specializes in secure document storage.",
    "anxiety": "Clear instructions reduced employees' anxiety about the new system.",
    "precisely": "Please state precisely how many units were delivered.",
    "rival": "The rival company launched a similar service last month.",
    "offense": "The employee received a warning for a serious workplace offense.",
    "detect": "The software can detect unusual activity on the account.",
    "moderate": "The restaurant offers a moderate price for the business lunch.",
    "surgery": "The employee will return to work after recovering from surgery.",
    "significance": "The manager explained the significance of the new safety rule.",
    "universal": "The company created a universal form for all branches.",
    "constitute": "These four departments constitute the customer service division.",
    "adequate": "The warehouse has adequate lighting for evening work.",
    "ethnic": "The restaurant offers dishes from several ethnic cuisines.",
    "clinical": "The clinic uses clinical guidelines to assess workplace injuries.",
    "segment": "The marketing team targeted a new customer segment.",
    "venture": "The partners launched a joint venture in the technology sector.",
    "compound": "The factory stores the chemical compound in a secure cabinet.",
    "preference": "The survey records each customer's delivery preference.",
    "comprehensive": "The consultant prepared a comprehensive review of the operation.",
    "incentive": "The company offered a bonus as an incentive for early completion.",
    "dismiss": "The manager dismissed the complaint after reviewing the evidence.",
    "margin": "The new pricing plan improved the company's profit margin.",
    "capability": "The software has the capability to process large orders.",
    "correspond": "The figures in the invoice correspond to the purchase order.",
    "stroke": "The employee received medical attention after suffering a stroke.",
    "barrier": "The language barrier made the first customer meeting difficult.",
    "counsel": "The supervisor gave counsel before I submitted the application.",
    "tendency": "The report identifies a tendency toward shorter delivery times.",
    "survival": "Cash reserves are important to the survival of a small business.",
    "possess": "Employees must possess a valid access card to enter the lab.",
    "impressive": "The team delivered an impressive presentation to the investors.",
    "evolution": "The report describes the evolution of the company's online service.",
    "awareness": "The campaign raised awareness of workplace safety.",
    "wealthy": "The hotel attracts wealthy clients during the tourist season.",
    "architecture": "The architect presented the office building's energy-efficient architecture.",
    "depress": "High interest rates may depress demand for new homes.",
    "privilege": "The membership gives customers the privilege of early booking.",
    "mutual": "The two companies reached a mutual agreement on delivery terms.",
    "motivate": "The manager uses recognition to motivate the sales team.",
    "mortgage": "The bank approved the customer's mortgage application.",
}

JA = {
    "milk": "ホテルは会議の朝食用に新鮮な牛乳を注文した。",
    "talent": "会社は才能のある従業員を定着させる制度を作った。",
    "smell": "安全担当者は機械の近くで焦げたにおいに気づいた。",
    "prior": "顧客は当社の配送サービスを以前に利用した経験がある。",
    "priority": "顧客の安全は当社の最優先事項だ。",
    "online": "IT部門は更新後、オンライン注文システムを監視した。",
    "phrase": "契約書に記載された表現をそのまま使ってください。",
    "pilot": "会社は1つの支店で新しいスケジュールシステムを試験導入する。",
    "stable": "仕入先は今四半期、安定した価格を維持している。",
    "merely": "その割引は単なる宣伝ではなく、最終費用を下げるものだ。",
    "resolution": "顧客は苦情に対する提案された解決策を受け入れた。",
    "vast": "会社は海外の仕入先による広大なネットワークを持っている。",
    "producer": "プロデューサーは締め切り前に広告動画を納品した。",
    "regional": "地域マネージャーは来週、支店を訪問する。",
    "slip": "記入済みの用紙をマネージャーのドアの下に差し入れてください。",
    "politician": "訪問中の政治家は地元企業への支援について話した。",
    "seed": "会社は地元の小規模企業に創業資金を提供した。",
    "salary": "その職には競争力のある給与と福利厚生がある。",
    "temporary": "会社は繁忙期に臨時スタッフを雇った。",
    "qualify": "応募者は事前に注文すれば割引の条件を満たせる。",
    "truly": "新しいサービスは小規模企業にとって本当に役立つ。",
    "yellow": "特別な取り扱いが必要な荷物には黄色いラベルを使う。",
    "self": "研修では従業員が自分の業績を評価する。",
    "metal": "工場は生産ラインから出る金属くずをリサイクルしている。",
    "panel": "専門家委員会が仕入先からの提案を審査した。",
    "prime": "その店は駅の近くの一等地にある。",
    "maximum": "最大注文数量はウェブサイトに記載されている。",
    "sharp": "広告放映後、注文が急増した。",
    "motion": "取締役会は契約を延長する動議を承認した。",
    "plastic": "食堂はプラスチックのコップを再利用できるものに替えた。",
    "passage": "契約書には延滞料金に関する一節がある。",
    "reputation": "会社は信頼できるサービスで高い評判を得ている。",
    "negotiation": "双方が提案書を確認した後も交渉は続いた。",
    "mechanism": "マニュアルは機械を制御する仕組みを説明している。",
    "pocket": "小型スキャナーは技術者のポケットに簡単に入る。",
    "observation": "検査員は破損した包装について所見を記録した。",
    "meat": "レストランは会議用メニューに肉料理を加えた。",
    "unusual": "異例に高い需要のため、追加出荷が必要になった。",
    "repair": "技術者は今日の午後、プリンターを修理する。",
    "soul": "創業者の理念は今も会社の精神だ。",
    "presidential": "ホテルは来訪する指導者のために大統領用スイートを準備した。",
    "perfectly": "改訂版の予定は顧客の都合に完全に合っている。",
    "proud": "チームは時間どおりに配送してきた実績を誇りに思っている。",
    "educational": "会社は顧客向けの教育資料を作成した。",
    "substantial": "そのプロジェクトには新しい機器への多額の投資が必要だ。",
    "nearby": "従業員は6時以降、近くの駐車場を利用できる。",
    "manufacturer": "メーカーは保証期間中に故障した製品を修理する。",
    "slide": "発表者は2つの料金プランを比較するスライドを追加した。",
    "valuable": "調査は顧客のニーズについて貴重な情報を提供した。",
    "personally": "個人的には、顧客には午前の予約を勧める。",
    "reporter": "記者は会社の拡張についてCEOに取材した。",
    "shirt": "制服には会社のロゴ入りの青いシャツが含まれる。",
    "winner": "デザインコンテストの優勝者には賞金が贈られる。",
    "partly": "遅延は一部、運転手不足が原因だった。",
    "tennis": "ホテルには宿泊客と出張者が使えるテニスコートがある。",
    "urban": "会社は駅の近くに都市型配送センターを開設した。",
    "southern": "南部支店は3か国への出荷を担当している。",
    "output": "工場は新しい機器を導入した後、生産量を増やした。",
    "massive": "嵐は配送センターに甚大な被害を与えた。",
    "mouse": "ITチームは受付のワイヤレスマウスを交換した。",
    "mathematics": "アナリストは数学を使って財務予測を検証した。",
    "upper": "上階は来訪する役員専用だ。",
    "occupy": "新しい機器が保管エリアの大部分を占める。",
    "outline": "提案書は顧客サービス改善の手順を概説している。",
    "sufficient": "倉庫には来月の在庫を置く十分なスペースがある。",
    "update": "電話の後、顧客記録を更新してください。",
    "preserve": "書庫には署名済み契約書の写しがすべて保存されている。",
    "split": "マネージャーは注文を2つの出荷に分けた。",
    "swing": "休暇シーズンには売上が大きく変動することがある。",
    "sudden": "突然の停電で生産が1時間止まった。",
    "originally": "会議は当初、火曜日に予定されていた。",
    "secondly": "まず請求書を確認し、次に支払日を確認してください。",
    "severe": "悪天候で地域オフィス行きの便が遅れた。",
    "prospect": "営業担当者は有望な見込み客に電話した。",
    "snow": "大雪で倉庫への道路が閉鎖された。",
    "plot": "建築家は新しいオフィスビルの敷地計画を作成した。",
    "neck": "従業員は一日中机に向かった後、首の痛みを訴えた。",
    "primarily": "このサービスは主に小売業者向けに設計されている。",
    "retain": "ポイント制度は会社が顧客を維持するのに役立つ。",
    "sequence": "マニュアルには機械を起動する正しい順序が示されている。",
    "plain": "指示は平易な言葉で書かれている。",
    "volunteer": "従業員は会社の地域イベントでボランティア活動ができる。",
    "rural": "会社は農村地域へ配送サービスを拡大した。",
    "silence": "マネージャーは安全説明中、静かにするよう求めた。",
    "rapidly": "新しいウェブサイトの開設後、オンライン注文が急速に増えた。",
    "revolution": "新しい支払いシステムは小規模企業の銀行取引を大きく変える可能性がある。",
    "spell": "顧客の名前はアカウントの表記どおりに綴ってください。",
    "premise": "提案は需要が強く続くという前提に基づいている。",
    "protein": "食堂は昼食メニューにたんぱく質の多い料理を加えた。",
    "unemployment": "報告書は失業が地域企業に与える影響を調べている。",
    "wheel": "技術者は配送カートの壊れた車輪を交換した。",
    "minority": "会社は少数派が所有する仕入先を支援する制度を作った。",
    "origin": "税関申告書には各製品の原産地が記載されている。",
    "educate": "そのキャンペーンは新サービスについて顧客に知らせることを目的としている。",
    "toy": "小売店は安全基準を満たさないおもちゃを回収した。",
    "minor": "議題の小さな変更により、業績評価は金曜日に移された。",
    "storm": "嵐で地域全体の配送が遅れた。",
    "thick": "ガラス製機器を守るには厚い緩衝材が必要だ。",
    "negotiate": "購買マネージャーは明日、契約について交渉する。",
    "supplier": "オフィスの食堂は新鮮な野菜の地元仕入先を選んだ。",
    "prize": "従業員は経費削減のアイデアに対して賞を受け取った。",
    "typically": "その支店は通常、1営業日以内に注文を処理する。",
    "peer": "同僚が会議前に営業部長のプレゼンテーションを確認した。",
    "pension": "会社は福利厚生の説明会で年金の選択肢を説明する。",
    "wing": "新しいオフィスは建物の東棟に入っている。",
    "recognition": "従業員は優れた顧客サービスを評価された。",
    "roof": "請負業者は雨季の前に屋根を修理した。",
    "retirement": "会社は彼女の退職を祝う会を開いた。",
    "respectively": "2つの支店はそれぞれ200万ドルと300万ドルの売上を報告した。",
    "variation": "報告書は需要の季節変動を説明している。",
    "ultimately": "取締役会は最終的に提案を承認するか決定する。",
    "proof": "監査担当者は仕入先に支払いの証明を求めた。",
    "soil": "造園会社は木を植える前に土壌を検査した。",
    "smart": "スマート決済端末は複数の通貨に対応している。",
    "upset": "注文品が破損して届いたため、顧客は動揺した。",
    "tooth": "従業員は歯が痛んだため歯科医を受診した。",
    "representation": "労働組合は交渉中の代表を求めた。",
    "preparation": "入念な準備が成功するプレゼンテーションに役立った。",
    "silver": "ホテルは正式なビジネスディナーに銀色のトレーを使う。",
    "undertake": "請負業者は来月、改修工事を引き受けることに同意した。",
    "retail": "会社は小売店とウェブサイトで製品を販売している。",
    "wire": "顧客は請求書を受け取った後、代金を振り込む。",
    "unlikely": "出荷品が月曜日より前に到着する可能性は低い。",
    "publication": "会社は年次会議用の刊行物を準備した。",
    "slight": "支払い処理にわずかな遅れがあった。",
    "unknown": "機器故障の原因はまだ不明だ。",
    "zone": "荷積み区域では喫煙が禁止されている。",
    "restrict": "その方針は機密ファイルへのアクセスを制限している。",
    "trace": "技術者はネットワーク問題を故障したケーブルまで追跡した。",
    "solid": "会社は主要仕入先と堅固な関係を築いている。",
    "owe": "顧客は完了した作業の代金をまだ会社に支払っていない。",
    "uniform": "倉庫の全従業員は制服と安全靴を着用しなければならない。",
    "port": "出荷品は金曜日に港を出る予定だ。",
    "pitch": "営業チームは複数の顧客に新サービスを売り込む。",
    "specialist": "ソフトウェアの専門家がチームの問題解決を支援した。",
    "profile": "会社は新しいアカウント用に顧客プロフィールを作成した。",
    "mood": "マネージャーの前向きな雰囲気が発売前のチームを励ました。",
    "numerous": "報告書は経費削減の機会を多数特定した。",
    "submit": "締め切り前に申請書を提出してください。",
    "symptom": "長引くせきは複数の感染症の症状である可能性がある。",
    "virtually": "研修会は海外の従業員向けにオンラインで行われた。",
    "tension": "調停者は契約紛争中の緊張を和らげた。",
    "sensitive": "マネージャーは機密性の高い顧客情報を慎重に扱った。",
    "nervous": "新入社員は顧客への発表を前に緊張した。",
    "prisoner": "請負業者は刑務所の警備設備を更新した。",
    "tight": "プロジェクトは厳しい締め切りの下で進んでいる。",
    "wet": "荷物が濡れた場合は書類を乾いた状態に保ってください。",
    "secondary": "工事中は裏口が閉鎖されている。",
    "welfare": "会社は柔軟な休暇制度を追加して従業員の福利厚生を改善した。",
    "recruit": "会社は営業スタッフを追加採用する予定だ。",
    "string": "システムは注文番号を文字列として保存する。",
    "persuade": "担当者は顧客を説得して契約を更新してもらった。",
    "phenomenon": "季節的な需要は小売業界によくある現象だ。",
    "pupil": "会社は地元の生徒支援事業にコンピューターを寄付した。",
    "restore": "ITチームは最新のバックアップからファイルを復元した。",
    "perceive": "顧客はそのブランドを信頼できてプロ意識が高いと認識している。",
    "routine": "技術者は開業前に定期点検を完了した。",
    "sink": "保守担当者は従業員用キッチンの流し台を修理した。",
    "stare": "フォームに記入中の顧客をじっと見つめないでください。",
    "supporter": "そのキャンペーンは有力な事業支援者から支援を受けた。",
    "steady": "会社は過去1年間、着実な成長を遂げた。",
    "meter": "技術者は倉庫の電気メーターを確認した。",
    "truck": "配送トラックは8時に荷積み場へ到着した。",
    "nose": "航空機は不時着で機首が損傷した。",
    "sail": "船は検査後、港から出航する。",
    "pace": "チームは需要に応えるため生産のペースを上げた。",
    "terrorist": "安全説明ではテロの脅威を報告する手順を扱った。",
    "vital": "正確な顧客記録はサポートチームに不可欠だ。",
    "spare": "技術者は予備のケーブルを機器棚に保管していた。",
    "whenever": "システムにエラーが表示されたら、いつでもヘルプデスクに連絡してください。",
    "underlie": "信頼と透明性が顧客との関係の基盤になっている。",
    "mom": "母は市に初雪が降る前に冬のコートを送ってくれた。",
    "satisfaction": "調査は配送後の顧客満足度を測定する。",
    "pour": "洗浄液を表示のある容器に注いでください。",
    "sweep": "新技術は物流業界全体に広がると予想されている。",
    "obligation": "仕入先には顧客データを守る義務がある。",
    "sir": "受付係は「おはようございます。お客様のお連れ様がお待ちです」と言った。",
    "pub": "ホテルは来訪者の夕食に近くのパブを勧めた。",
    "perception": "そのキャンペーンは顧客のブランドに対する認識を変えた。",
    "naturally": "新しい手順によって書類の量は自然に減った。",
    "territory": "営業担当者は北部地域を担当している。",
    "stream": "会社は製品デモンストレーションをライブ配信した。",
    "rarely": "その支店が配送時間について苦情を受けることはめったにない。",
    "western": "会社は西部地域に支店を開設した。",
    "muscle": "従業員は重い段ボールを動かして筋肉を痛めた。",
    "scare": "停電で建物内の来訪者数人が怖がった。",
    "ratio": "報告書は新規顧客とリピーターの比率が健全だと示している。",
    "scream": "非常口が開くと警報が鳴り響くことがある。",
    "withdraw": "仕入先は入札手続きから提案を取り下げることにした。",
    "pollution": "工場は大気汚染を減らすためフィルターを設置した。",
    "symbol": "緑色の記号は製品がリサイクル可能であることを示す。",
    "platform": "会社はオンラインプラットフォームを通じてサービスを販売している。",
    "steel": "請負業者は倉庫拡張に鋼鉄の梁を使った。",
    "transform": "新しいソフトウェアはチームの注文管理方法を一変させる。",
    "wound": "職場の看護師は従業員の傷を手当てした。",
    "restriction": "空港は機内持ち込み液体に制限を設けた。",
    "strain": "長時間労働が小規模なサポートチームの負担になった。",
    "singer": "歌手は会社の記念イベントで演奏した。",
    "trail": "配送担当者は遠隔地へ続く標識の跡をたどった。",
    "trap": "安全チームは倉庫近くの動物を捕まえるわなを仕掛けた。",
    "wealth": "報告書は個人の富が消費支出に与える影響を調べている。",
    "tank": "技術者は配送車が出発する前に燃料タンクを点検した。",
    "remarkable": "会社は海外売上で目覚ましい成長を遂げた。",
    "tune": "技術者はプレゼンテーション前に会議室の音響設備を調整した。",
    "transition": "会社は新システムへの移行中に研修を行った。",
    "stem": "マネージャーは問題の原因をバルブの軸まで追跡した。",
    "reverse": "銀行は不正な取引であれば請求を取り消すことがある。",
    "mode": "チームは研修会にオンライン方式を選んだ。",
    "mirror": "売上高は小売業者が報告した強い需要を反映している。",
    "pose": "配線の損傷は安全上のリスクをもたらす可能性がある。",
    "nowadays": "今日では、多くの顧客が請求書を電子的に受け取ることを好む。",
    "poem": "会社は従業員向けのニュースレターに詩を掲載した。",
    "vegetable": "食堂は昼食メニューに野菜料理を加えた。",
    "van": "社用バンは毎朝、地域支店へ用品を運ぶ。",
    "planet": "会社は地球を守るため包装廃棄物を減らした。",
    "overcome": "チームは綿密な計画によって配送問題を克服した。",
    "web": "顧客は会社のウェブポータルで申請を完了した。",
    "portion": "レストランは会議の来客用に少なめの料理を用意した。",
    "substance": "安全データシートには洗浄剤に含まれる危険物質が記載されている。",
    "sugar": "カフェは砂糖を加えていない飲み物を提供している。",
    "pink": "マーケティングチームは季節商品の包装にピンクを選んだ。",
    "shadow": "新契約が会社の拡張計画に影を落としている。",
    "strip": "技術者は破損した断熱材の帯を取り除いた。",
    "smooth": "調整担当者は登録手続きを円滑に進めた。",
    "vice": "副社長は改訂版の予算を承認した。",
    "radical": "会社は返品方針を根本的に変更した。",
    "similarly": "同様に、東支店も顧客満足度の上昇を報告した。",
    "subsequent": "その後の会議では契約の詳細に焦点を当てた。",
    "efficiency": "エネルギー効率の向上はオフィスの運営費を削減できる。",
    "statistic": "報告書にはオンライン売上の増加を示す統計値がある。",
    "broadcast": "会社は製品発表をオンラインで放送する。",
    "ally": "その販売代理店は海外市場で重要な協力者になった。",
    "mature": "成熟した市場には異なる価格戦略が必要だ。",
    "disturb": "発表中は来訪者の邪魔をしないでください。",
    "sustain": "新契約は地域市場の成長を支えるだろう。",
    "poverty": "会社は地域の貧困を減らす事業を支援している。",
    "cite": "提案書では元の報告書を引用してください。",
    "parallel": "2つのチームが異なる解決策を試す並行プロジェクトを実施した。",
    "gender": "調査では性別の情報を任意で尋ねている。",
    "sponsor": "会社は地域のビジネス会議を後援することに同意した。",
    "burden": "新しいソフトウェアはスタッフの事務負担を減らす。",
    "shareholder": "株主は会社の拡張計画について質問した。",
    "resistance": "電気抵抗は回路内の電流を制限することがある。",
    "frequency": "マネージャーは安全点検の頻度を増やした。",
    "philosophy": "会社の理念は優れた顧客サービスを重視している。",
    "attribute": "マネージャーは売上増加を新キャンペーンの成果だと考えている。",
    "approval": "取締役会は拡張を承認した。",
    "entitle": "この会員資格があれば顧客は通常配送を無料で利用できる。",
    "involvement": "全部署の関与によってプロジェクトは成功した。",
    "exposure": "キャンペーンは地域市場でのブランド露出を増やした。",
    "conventional": "会社は従来の用紙をデジタル手続きに置き換えた。",
    "formation": "新しい部署の設立は4月に行われる。",
    "deposit": "ホテルは予約を確定するため保証金を求めている。",
    "advocate": "顧客支援担当者が請求問題の解決を手伝った。",
    "establishment": "新支店の設立により20人の雇用が生まれた。",
    "summary": "マネージャーは会議の要約を配布した。",
    "characterize": "報告書は市場を非常に競争が激しいと特徴づけている。",
    "specify": "契約書は納品日と支払条件を明記している。",
    "anticipate": "休暇シーズンには需要が高まると予想している。",
    "dependent": "その支店は技術サポートを中央オフィスに依存している。",
    "specialize": "会社は安全な書類保管を専門としている。",
    "anxiety": "明確な指示が新システムへの従業員の不安を和らげた。",
    "precisely": "何台納品されたのか正確に述べてください。",
    "rival": "競合会社は先月、似たサービスを開始した。",
    "offense": "従業員は重大な職場規則違反で警告を受けた。",
    "detect": "そのソフトウェアはアカウント上の異常な活動を検出できる。",
    "moderate": "レストランはビジネスランチを手頃な価格で提供している。",
    "surgery": "従業員は手術から回復した後、仕事に戻る予定だ。",
    "significance": "マネージャーは新しい安全規則の重要性を説明した。",
    "universal": "会社は全部署共通のフォームを作成した。",
    "constitute": "この4部署が顧客サービス部門を構成している。",
    "adequate": "倉庫には夜間作業に十分な照明がある。",
    "ethnic": "レストランは複数の民族料理を提供している。",
    "clinical": "診療所は職場でのけがを評価するため臨床指針を使っている。",
    "segment": "マーケティングチームは新しい顧客層を対象にした。",
    "venture": "取引先はテクノロジー分野で合弁事業を始めた。",
    "compound": "工場はその化合物を安全な棚に保管している。",
    "preference": "調査は各顧客の配送の好みを記録する。",
    "comprehensive": "コンサルタントは業務の包括的な見直しを行った。",
    "incentive": "会社は早期完了の奨励策としてボーナスを提供した。",
    "dismiss": "マネージャーは証拠を確認した後、その苦情を退けた。",
    "margin": "新しい価格計画で会社の利益率が改善した。",
    "capability": "そのソフトウェアには大量注文を処理する能力がある。",
    "correspond": "請求書の金額は発注書と一致している。",
    "stroke": "従業員は脳卒中を起こした後、医療処置を受けた。",
    "barrier": "言葉の壁が初回の顧客会議を難しくした。",
    "counsel": "上司は工学課程への申請書を出す前に助言をくれた。",
    "tendency": "報告書は配送時間が短くなる傾向を特定している。",
    "survival": "資金準備は小規模企業の存続に重要だ。",
    "possess": "従業員は研究室に入るため有効な入館カードを持っていなければならない。",
    "impressive": "チームは投資家に見事なプレゼンテーションを行った。",
    "evolution": "報告書は会社のオンラインサービスの発展を説明している。",
    "awareness": "キャンペーンは職場の安全に対する意識を高めた。",
    "wealthy": "ホテルは観光シーズンに裕福な顧客を引きつける。",
    "architecture": "建築家はオフィスビルの省エネ設計を発表した。",
    "depress": "高金利は新築住宅の需要を低迷させる可能性がある。",
    "privilege": "会員資格があれば顧客は早期予約の特典を利用できる。",
    "mutual": "2社は配送条件について相互合意に達した。",
    "motivate": "マネージャーは評価制度で営業チームの意欲を高めている。",
    "mortgage": "銀行は顧客の住宅ローン申請を承認した。",
}

def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 2][700:1000]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        source = EN[word]
        item["example"] = source
        example = translations.setdefault(f"builtin:{item['id']}", {}).setdefault("example", {})
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if example.get(field) != value:
                example[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 600+ English examples batch 4: {len(level_rows)} terms, {changed} fields")

if __name__ == "__main__":
    main()
