#!/usr/bin/env python3
"""Review the first 300 TOEIC 700+ examples in English and Japanese."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"

EN = {
    "meteorology": "The airline's meteorology team reviewed the forecast before setting the flight schedule.",
    "validating": "The auditor is validating the figures before approving the report.",
    "meteorological": "Meteorological conditions may delay deliveries to the northern branch.",
    "wishful": "The manager warned that expecting a recovery without a plan was wishful thinking.",
    "warship": "The port authority restricted access while a warship was docked nearby.",
    "genetically": "The manufacturer labels products that have been genetically modified.",
    "immortality": "The campaign used the idea of immortality to promote the insurance plan.",
    "astronomical": "The project faced astronomical costs after the original estimate proved inaccurate.",
    "worthlessness": "The review found the old report to be of little practical value.",
    "readability": "The editor improved the readability of the customer manual.",
    "relativity": "The engineer explained relativity during a technical training session.",
    "tubular": "The supplier uses tubular steel for the equipment frame.",
    "prodigy": "The company recruited a software prodigy for its development team.",
    "competency": "The HR manager assessed each employee's competency during the review.",
    "analyzer": "The technician used an analyzer to test the material sample.",
    "genetic": "The company follows strict rules when handling genetic data.",
    "invisibility": "The security system detects attempts to hide equipment through invisibility devices.",
    "quantitatively": "The analyst compared the two proposals quantitatively.",
    "dissect": "The operations team will dissect the cause of the delay before the audit.",
    "proportional": "The bonus is proportional to each representative's sales.",
    "randomness": "The analyst accounted for randomness in the demand forecast.",
    "conductive": "The material is conductive and suitable for the new equipment.",
    "validated": "The laboratory uses a validated method to test every shipment.",
    "fluency": "The company evaluates language fluency when hiring overseas representatives.",
    "statistics": "The sales manager reviewed the statistics before the quarterly meeting.",
    "species": "The construction plan protects endangered species near the facility.",
    "quantify": "The operations team will quantify the cost of the delay before the audit.",
    "geologic": "The geologic survey helped the company choose a safe construction site.",
    "geologist": "The company hired a geologist to assess the proposed mining site.",
    "causal": "The report examines the causal relationship between delays and customer complaints.",
    "microbiology": "The manufacturer consults a microbiology laboratory for product testing.",
    "meteorologist": "The airline contacted a meteorologist before canceling the flight.",
    "zoologist": "The company hired a zoologist to advise on the wildlife impact of construction.",
    "barometer": "The airline checked the barometer before the aircraft departed.",
    "trimester": "The benefits plan allows employees to review their coverage each trimester.",
    "zoology": "The museum hired a zoology specialist to update its animal exhibits.",
    "academically": "The training is designed to be useful professionally, not only academically.",
    "biologically": "The laboratory records how biologically active materials are stored.",
    "botany": "The company hired a botany specialist for its agricultural project.",
    "ecosystem": "The company assessed the ecosystem before expanding the facility.",
    "genetics": "The research team uses genetics to improve agricultural products.",
    "accelerated": "The company introduced an accelerated approval process for urgent orders.",
    "meteor": "The observatory notified the airline about a meteor observation near the flight path.",
    "examinee": "Each examinee received instructions before the certification test.",
    "academia": "The company partnered with academia to develop new technology.",
    "physiologist": "The company consulted a physiologist when designing the employee wellness program.",
    "intern": "The manager assigned the intern to update the customer database.",
    "institute": "The company partnered with an institute to provide technical training.",
    "dating": "The app company analyzed dating trends before updating its advertising plan.",
    "veterinarian": "The company asked a veterinarian to review the animal-care policy.",
    "cloning": "The biotech company invested in cloning research under strict ethical rules.",
    "respiration": "The medical team monitored respiration during the equipment test.",
    "magnetism": "The engineer explained how magnetism affects the equipment.",
    "educationally": "The museum designed the exhibit to be educationally useful for visitors.",
    "collegiate": "The company formed a collegiate partnership to recruit engineering interns.",
    "statistician": "The manager asked a statistician to review the survey results.",
    "quartz": "The manufacturer tested the quartz before production began.",
    "unscientific": "The auditor rejected the unscientific method used in the old report.",
    "hypothesis": "The team tested the hypothesis before changing the process.",
    "seismic": "The seismic survey helped engineers design a safer facility.",
    "alumnus": "The company invited an alumnus to speak at its career event.",
    "illiteracy": "The nonprofit launched a program to reduce illiteracy among adult workers.",
    "symmetry": "The designer checked the symmetry of the product's logo.",
    "dropout": "The program helps employees who dropped out of school complete job training.",
    "reactor": "The engineering manager explained how a reactor controls heat safely.",
    "well-informed": "A well-informed sales team can answer customer questions accurately.",
    "distillation": "The manufacturer used distillation to purify the material.",
    "well-rounded": "The company seeks well-rounded candidates with technical and communication skills.",
    "additive": "The manufacturer tested the additive before production.",
    "archaeology": "The museum hired an archaeology consultant for the heritage project.",
    "elective": "The safety workshop is elective for experienced contractors.",
    "archeologist": "The developer consulted an archeologist before building near the historic site.",
    "hibernation": "The device enters hibernation to save power overnight.",
    "biodiversity": "The company assessed biodiversity before construction began.",
    "aerodynamics": "The manufacturer tested the vehicle's aerodynamics.",
    "neanderthal": "The museum created a Neanderthal exhibit for visitors.",
    "underachieve": "The sales team may underachieve if it ignores the new customer data.",
    "carnivorous": "The wildlife center used a separate enclosure for carnivorous animals.",
    "self-discipline": "Remote work requires self-discipline and clear time management.",
    "inattentive": "The supervisor reminded the inattentive employee to follow the procedure.",
    "wholeheartedly": "The director wholeheartedly supported the employee training plan.",
    "paranormal": "The insurer requested evidence before reviewing the paranormal claim.",
    "data-based": "The company adopted a data-based approach to product development.",
    "wickedness": "The ethics report condemns the wickedness of exploiting vulnerable customers.",
    "counterweight": "The engineer added a counterweight to stabilize the lifting device.",
    "sedimentation": "The environmental team monitored sedimentation near the construction site.",
    "theoretic": "The engineer compared the theoretic model with the actual test results.",
    "cognition": "The HR team discussed cognition during a workplace training session.",
    "intramural": "The company organized an intramural sports event for employees.",
    "fissure": "The inspector found a fissure in the concrete wall.",
    "microbial": "The laboratory tested the product for microbial contamination.",
    "empiricism": "The research manager discussed empiricism as a basis for product testing.",
    "theoretician": "The company invited an economic theoretician to speak at the forum.",
    "empiricist": "The empiricist requested more test data before accepting the proposal.",
    "finitude": "The planning team considered the finitude of the available budget.",
    "confirmatory": "The audit provided confirmatory evidence for the purchasing decision.",
    "decomposition": "The waste team monitors decomposition in the composting facility.",
    "radiance": "The lighting consultant measured the radiance of the display panels.",
    "resiliency": "The new backup system improves the company's operational resiliency.",
    "luminosity": "The engineer measured the luminosity of the warning display.",
    "counterfactual": "The analyst used a counterfactual scenario to estimate the effect of the price change.",
    "hypothetically": "Hypothetically, the branch could double sales with enough staff.",
}

JA = {
    "meteorology": "航空会社の気象チームはフライトスケジュールを決める前に予報を確認した。",
    "validating": "監査担当者は報告書を承認する前に数値を検証している。",
    "meteorological": "気象条件により北部支店への配送が遅れる可能性がある。",
    "wishful": "マネージャーは計画なしに回復を期待するのは希望的観測だと警告した。",
    "warship": "軍艦が近くに停泊している間、港湾当局は立ち入りを制限した。",
    "genetically": "メーカーは遺伝子組み換え製品に表示を付けている。",
    "immortality": "キャンペーンは保険プランを宣伝するため不死のイメージを使った。",
    "astronomical": "当初の見積もりが不正確だったため、プロジェクト費用が途方もなく膨らんだ。",
    "worthlessness": "レビューで古い報告書は実務上ほとんど価値がないと判明した。",
    "readability": "編集者は顧客向けマニュアルの読みやすさを改善した。",
    "relativity": "技術者は技術研修会で相対性理論を説明した。",
    "tubular": "仕入先は機器のフレームに管状の鋼材を使っている。",
    "prodigy": "会社は開発チームにソフトウェアの天才を採用した。",
    "competency": "人事マネージャーは評価時に各従業員の能力を査定した。",
    "analyzer": "技術者は分析装置を使って素材のサンプルを検査した。",
    "genetic": "会社は遺伝情報を扱う際、厳格な規則に従っている。",
    "invisibility": "警備システムは不可視化装置で機器を隠そうとする試みを検出する。",
    "quantitatively": "アナリストは2つの提案を定量的に比較した。",
    "dissect": "運用チームは監査前に遅延の原因を詳しく分析する。",
    "proportional": "ボーナスは各担当者の売上に比例する。",
    "randomness": "アナリストは需要予測でランダム性を考慮した。",
    "conductive": "その素材は導電性があり、新しい機器に適している。",
    "validated": "研究所はすべての出荷品を検査するため検証済みの方法を使う。",
    "fluency": "会社は海外担当者の採用時に語学の流暢さを評価する。",
    "statistics": "営業部長は四半期会議の前に統計データを確認した。",
    "species": "建設計画は施設周辺の絶滅危惧種を保護している。",
    "quantify": "運用チームは監査前に遅延費用を数値化する。",
    "geologic": "地質調査は会社が安全な建設場所を選ぶのに役立った。",
    "geologist": "会社は採掘予定地を評価するため地質学者を雇った。",
    "causal": "報告書は遅延と顧客苦情の因果関係を調べている。",
    "microbiology": "メーカーは製品検査のため微生物学研究所に相談している。",
    "meteorologist": "航空会社は便を欠航にする前に気象学者へ連絡した。",
    "zoologist": "会社は建設が野生動物に与える影響について動物学者を雇った。",
    "barometer": "航空会社は航空機の出発前に気圧計を確認した。",
    "trimester": "福利厚生制度では各学期に補償内容を見直せる。",
    "zoology": "博物館は動物展示を更新するため動物学の専門家を雇った。",
    "academically": "研修は学術面だけでなく、職業上も役立つよう設計されている。",
    "biologically": "研究所は生物学的に活性のある素材の保管方法を記録している。",
    "botany": "会社は農業プロジェクトのため植物学の専門家を雇った。",
    "ecosystem": "会社は施設を拡張する前に生態系を評価した。",
    "genetics": "研究チームは農産物を改良するため遺伝学を利用している。",
    "accelerated": "会社は緊急注文向けに短縮承認手続きを導入した。",
    "meteor": "天文台は飛行経路付近での流星観測を航空会社に知らせた。",
    "examinee": "受験者は認定試験の前に指示を受けた。",
    "academia": "会社は新技術を開発するため学界と提携した。",
    "physiologist": "会社は従業員の健康制度を設計する際、生理学者に相談した。",
    "intern": "マネージャーはインターンに顧客データベースの更新を任せた。",
    "institute": "会社は技術研修を提供するため研究機関と提携した。",
    "dating": "アプリ会社は広告計画を更新する前に交際の傾向を分析した。",
    "veterinarian": "会社は動物管理方針の確認を獣医に依頼した。",
    "cloning": "バイオ企業は厳格な倫理規則の下でクローン研究に投資した。",
    "respiration": "医療チームは機器試験中の呼吸を監視した。",
    "magnetism": "技術者は磁力が機器に与える影響を説明した。",
    "educationally": "博物館は展示が来訪者に教育的に役立つよう設計した。",
    "collegiate": "会社は工学系インターンを採用するため大学と提携した。",
    "statistician": "マネージャーは調査結果の確認を統計学者に依頼した。",
    "quartz": "メーカーは生産開始前に石英を検査した。",
    "unscientific": "監査担当者は古い報告書で使われた非科学的な方法を退けた。",
    "hypothesis": "チームは手順を変更する前に仮説を検証した。",
    "seismic": "地震調査は技術者がより安全な施設を設計するのに役立った。",
    "alumnus": "会社はキャリアイベントで卒業生に講演を依頼した。",
    "illiteracy": "非営利団体は成人労働者の読み書き能力不足を減らす事業を始めた。",
    "symmetry": "デザイナーは製品ロゴの左右の均衡を確認した。",
    "dropout": "その事業は学校を中退した従業員の職業訓練修了を支援する。",
    "reactor": "技術部長は原子炉が熱を安全に制御する仕組みを説明した。",
    "well-informed": "情報に詳しい営業チームは顧客の質問に正確に答えられる。",
    "distillation": "メーカーは素材を精製するため蒸留を行った。",
    "well-rounded": "会社は技術力とコミュニケーション能力を備えたバランスのよい人材を求めている。",
    "additive": "メーカーは生産前に添加物を検査した。",
    "archaeology": "博物館は文化遺産事業のため考古学の専門家を雇った。",
    "elective": "安全研修は経験豊富な請負業者には選択制だ。",
    "archeologist": "開発業者は史跡の近くに建設する前に考古学者へ相談した。",
    "hibernation": "機器は夜間の電力を節約するため休眠状態になる。",
    "biodiversity": "会社は建設開始前に生物多様性を評価した。",
    "aerodynamics": "メーカーは車両の空気力学を検査した。",
    "neanderthal": "博物館は来訪者向けにネアンデルタール人の展示を作った。",
    "underachieve": "新しい顧客データを無視すると、営業チームは期待を下回る可能性がある。",
    "carnivorous": "野生動物センターは肉食動物用に別の囲いを使った。",
    "self-discipline": "リモート勤務には自己規律と明確な時間管理が必要だ。",
    "inattentive": "上司は不注意な従業員に手順を守るよう注意した。",
    "wholeheartedly": "取締役は従業員研修計画を心から支持した。",
    "paranormal": "保険会社は超常現象の請求を審査する前に証拠を求めた。",
    "data-based": "会社は製品開発にデータに基づく手法を採用した。",
    "wickedness": "倫理報告書は弱い立場の顧客を搾取する悪行を非難している。",
    "counterweight": "技術者は昇降装置を安定させるため釣り合い重りを追加した。",
    "sedimentation": "環境チームは建設現場付近の堆積を監視した。",
    "theoretic": "技術者は理論上のモデルを実際の試験結果と比較した。",
    "cognition": "人事チームは職場研修で認知について話し合った。",
    "intramural": "会社は従業員向けに社内スポーツイベントを開催した。",
    "fissure": "検査員はコンクリート壁に亀裂を見つけた。",
    "microbial": "研究所は製品の微生物汚染を検査した。",
    "empiricism": "研究責任者は製品試験の基礎として経験論を議論した。",
    "theoretician": "会社は経済理論家をフォーラムに招いた。",
    "empiricist": "経験論者は提案を受け入れる前に追加の試験データを求めた。",
    "finitude": "計画チームは利用可能な予算の有限性を考慮した。",
    "confirmatory": "監査は購買決定を裏付ける証拠を示した。",
    "decomposition": "廃棄物チームは堆肥化施設で分解を監視している。",
    "radiance": "照明コンサルタントは表示パネルの輝きを測定した。",
    "resiliency": "新しいバックアップシステムが会社の業務回復力を高める。",
    "luminosity": "技術者は警告表示の明るさを測定した。",
    "counterfactual": "アナリストは値上げの影響を見積もるため反事実的なシナリオを使った。",
    "hypothetically": "仮に十分な人員があれば、その支店は売上を2倍にできる。",
}

EN.update({
    "quantification": "Precise quantification of the project cost helped the board compare the proposals.",
    "reproducibility": "The quality team checked the reproducibility of the test results.",
    "experimentalism": "The research director encouraged experimentalism during product development.",
    "confounding": "A confounding error in the invoice delayed the payment.",
    "conceptualization": "The team's conceptualization of the new service clarified its target market.",
    "deterministic": "The engineer used a deterministic model to calculate the delivery time.",
    "indeterminacy": "The contract addresses the indeterminacy of the final delivery date.",
    "reductionism": "The consultant warned against reductionism when evaluating the customer survey.",
    "exponent": "The analyst explained how the exponent affects the financial model.",
    "immanent": "The risk was immanent in the original design of the payment system.",
    "mutability": "The software's mutability allows the team to update the workflow quickly.",
    "quantum": "The company invested in quantum computing research for future security tools.",
    "empirically": "The team empirically tested the new packaging before launch.",
    "entropy": "The engineer explained how entropy affects the efficiency of the process.",
    "qualitatively": "The manager qualitatively compared the service plans before reviewing the prices.",
    "imprecision": "Imprecision in the address caused the shipment to be returned.",
    "heterogeneity": "The survey reflects the heterogeneity of the company's customer base.",
    "determinism": "The analyst discussed determinism when explaining the forecasting model.",
    "materiality": "The auditor assessed the materiality of the accounting error.",
    "periodicity": "The report identifies the periodicity of monthly demand.",
    "compounded": "The company faced compounded costs after two suppliers missed the deadline.",
    "generalised": "The trainer provided a generalised procedure that every branch could use.",
    "instill": "The orientation program aims to instill confidence in new employees.",
    "fractional": "The investor purchased a fractional share of the fund.",
    "galactic": "The project did not require a galactic budget; a local solution was sufficient.",
    "singularity": "The engineer explained the singularity in the data before publishing the report.",
    "corroborate": "The auditor corroborated the figures before approving the report.",
    "assessable": "The manager set assessable targets for each sales representative.",
    "homogeneity": "The quality team checks the homogeneity of each production batch.",
    "invariance": "The analyst tested the invariance of the pricing rule across regions.",
    "generalized": "The company created a generalized checklist for all branches.",
    "hypothesize": "The operations team will hypothesize the cause of the delay before the audit.",
    "enlighten": "The specialist will enlighten the client about the new compliance policy.",
    "aberration": "The auditor treated the unusual payment as an aberration requiring review.",
    "mutable": "The workflow is mutable, so the manager can change it when regulations change.",
    "immutable": "The archive stores an immutable copy of the signed contract.",
    "cosmic": "The insurance plan covers ordinary risks, not cosmic events.",
    "resonance": "The campaign had strong resonance with younger customers.",
    "opacity": "The opacity of the pricing policy made customers uncertain about fees.",
    "oceanography": "The company consulted an oceanography specialist before planning the coastal facility.",
    "microbiologist": "The manufacturer contacted a microbiologist about product safety.",
    "histology": "The laboratory used histology results to evaluate the medical product.",
    "baccalaureate": "The applicant listed her baccalaureate on the employment form.",
    "extraterrestrial": "The museum prepared an exhibit about extraterrestrial research.",
    "meteoroid": "The observatory tracked a meteoroid before issuing its report.",
    "biologic": "The company follows special rules when transporting biologic materials.",
    "subspecies": "The conservation team recorded the subspecies found near the facility.",
    "phenotype": "The research team documented each plant's phenotype during testing.",
    "geneticist": "The company asked a geneticist to review the laboratory's safety plan.",
    "formulate": "The operations team will formulate a plan for the product launch.",
    "academe": "The company works with academe to develop workplace technology.",
    "postdoc": "The laboratory hired a postdoc to support the product-testing team.",
    "curricular": "The training director reviewed the curricular requirements for certification.",
    "academician": "The company invited an academician to advise on the research partnership.",
    "polytechnic": "The manufacturer recruited technicians from a local polytechnic.",
    "bioethics": "The board discussed bioethics before approving the medical study.",
    "subconscious": "The consultant explained how subconscious preferences can affect purchasing decisions.",
    "extraversion": "The HR team discussed extraversion during the leadership workshop.",
    "speciation": "The museum's exhibit explains speciation for visitors.",
    "behaviorist": "The company consulted a behaviorist when designing the customer survey.",
    "circadian": "The manager considered circadian patterns when creating the night-shift schedule.",
    "provost": "The provost visited the company during the university partnership meeting.",
    "paleontology": "The museum hired a paleontology consultant for the new exhibit.",
    "radioactivity": "The laboratory tested the radioactivity of the material before shipping it.",
    "botanist": "The company contacted a botanist before expanding the agricultural facility.",
    "thermodynamics": "The engineer applied thermodynamics to improve the heating system.",
    "coeducational": "The company partnered with a coeducational college for recruitment.",
    "bioscience": "The firm invested in bioscience to develop safer medical products.",
    "crustacean": "The restaurant supplier checks each crustacean shipment for freshness.",
    "neuroscience": "The company uses neuroscience research to improve the training app.",
    "astrophysics": "The museum invited an astrophysics expert to speak at the science event.",
    "naturalist": "The resort consulted a naturalist before expanding its nature trail.",
    "lactose": "The product label states whether the drink contains lactose.",
    "peroxide": "The laboratory stores peroxide in a clearly marked cabinet.",
    "anthropological": "The consultant provided an anthropological perspective on local customer habits.",
    "metaphysics": "The bookstore added a metaphysics section to its online catalog.",
    "collegial": "The department has a collegial atmosphere that encourages cooperation.",
    "genomics": "The laboratory uses genomics to support medical product development.",
    "mainstreamed": "The company mainstreamed accessibility features across its new software.",
    "pedagogical": "The trainer used a pedagogical method suited to new employees.",
    "hybridization": "The agricultural team studied hybridization to improve the crop variety.",
    "educationist": "The company invited an educationist to review the training program.",
    "nanotube": "The manufacturer tested a nanotube coating before production began.",
    "recombination": "The genetics manager explained recombination during the technical briefing.",
    "transcribe": "The assistant will transcribe the meeting recording before the audit.",
    "cosmology": "The museum hired a cosmology specialist for its space exhibit.",
    "pedagogy": "The training manager reviewed the pedagogy behind the new course.",
    "seminary": "The company donated computers to a seminary's library.",
    "educative": "The customer workshop was designed to be educative and practical.",
    "metallurgy": "The manufacturer consulted a metallurgy expert about the new alloy.",
    "allele": "The research team recorded each allele during the plant study.",
    "dissociate": "The company decided to dissociate the brand from the controversial supplier.",
    "maturation": "The manager explained how the maturation of the project affected the launch date.",
    "reverberation": "The conference room's reverberation made the speaker difficult to hear.",
    "co-occurrence": "The analyst examined the co-occurrence of delivery delays and complaints.",
    "ornithologist": "The construction company consulted an ornithologist before clearing the site.",
    "pharmacology": "The laboratory hired a pharmacology specialist for the new medicine.",
    "thermodynamic": "The engineer modeled thermodynamic constraints in the heating system.",
    "etymological": "The editor checked the etymological origin of the product name.",
    "encyclopedic": "The consultant has encyclopedic knowledge of the logistics industry.",
    "gravitationally": "The engineer explained how the equipment is gravitationally stabilized.",
    "accreditation": "The training program received accreditation from the industry association.",
    "correlative": "The report found a correlative relationship between response time and retention.",
    "electrochemical": "The laboratory tested an electrochemical battery for the new vehicle.",
    "topographical": "The survey included a topographical map of the construction site.",
    "electrostatic": "The engineer explained how electrostatic discharge can damage a microchip.",
    "metamorphose": "The old process may metamorphose into a digital service.",
    "theology": "The publisher added a theology section to its academic catalog.",
    "doctrine": "The compliance manual explains the doctrine behind the policy.",
    "vocalization": "The speech coach analyzed the manager's vocalization during the presentation.",
    "incandescent": "The factory replaced incandescent bulbs with energy-efficient lights.",
    "coagulation": "The laboratory monitors coagulation during the medical test.",
    "reflectivity": "The engineer measured the reflectivity of the safety sign.",
    "matriculation": "The university sent instructions for employee matriculation in the certificate program.",
    "expository": "The report uses an expository style to explain the new procedure.",
    "gravitation": "The engineer considered gravitation when designing the lifting system.",
    "anthropomorphic": "The advertisement uses an anthropomorphic character to explain the service.",
    "backwardness": "The consultant warned that digital backwardness could hurt the branch's competitiveness.",
    "attentiveness": "The supervisor praised the employee's attentiveness during the safety briefing.",
    "interplanetary": "The aerospace company develops equipment for interplanetary missions.",
    "thermonuclear": "The research center follows strict rules for thermonuclear materials.",
    "sedimentary": "The geologist identified sedimentary rock at the construction site.",
    "inactivate": "The operations team will inactivate the account after repeated failed logins.",
    "biochemist": "The biochemist demonstrated how enzymes affect the product formula.",
    "carotenoid": "The manufacturer tested the carotenoid before approving the food additive.",
    "pleistocene": "The museum prepared a Pleistocene exhibit for visitors.",
    "toxicology": "The laboratory completed toxicology testing before the product launch.",
    "orthographic": "The editor corrected orthographic errors in the customer manual.",
    "permutation": "The analyst tested every permutation of the delivery schedule.",
    "refraction": "The engineer measured refraction in the optical sensor.",
    "zoological": "The company followed zoological standards when designing the animal facility.",
    "earthbound": "The exhibit explains how earthbound equipment differs from space equipment.",
    "optically": "The technician optically inspected the surface for scratches.",
    "polymer": "The manufacturer tested the polymer before production began.",
    "paraprofessional": "The clinic hired a paraprofessional to support the nursing staff.",
    "prognostic": "The medical team reviewed prognostic indicators before recommending treatment.",
    "precipitous": "A precipitous fall in demand forced the company to revise its forecast.",
    "aeronautics": "The aeronautics manager analyzed simulations that improve aircraft safety.",
    "inflection": "The trainer explained how inflection can change the tone of a customer call.",
    "synergistic": "The partnership created a synergistic relationship between sales and design.",
    "coloration": "The designer adjusted the coloration of the product packaging.",
    "inhibitory": "The new policy has an inhibitory effect on unnecessary spending.",
    "prospectus": "The editor checked the prospectus before publication.",
    "repulsion": "The engineer explained how repulsion affects the magnetic component.",
    "plagiarism": "The publisher's software detects plagiarism in submitted content.",
    "implosion": "The engineer explained the safety risks of an implosion inside the tank.",
    "irreducible": "The analyst identified an irreducible cost in the production process.",
    "organelle": "The laboratory recorded how the organelle responds during the product test.",
    "photosynthetic": "The company developed a photosynthetic coating for the greenhouse panels.",
})

JA.update({
    "quantification": "プロジェクト費用を正確に数値化したことで、取締役会は提案を比較できた。",
    "reproducibility": "品質管理チームは試験結果の再現性を確認した。",
    "experimentalism": "研究部長は製品開発で実験主義を奨励した。",
    "confounding": "請求書の混乱を招く誤りが支払いを遅らせた。",
    "conceptualization": "チームが新サービスを概念化したことで対象市場が明確になった。",
    "deterministic": "技術者は配送時間を計算するため決定論的なモデルを使った。",
    "indeterminacy": "契約書は最終納品日の不確実性について定めている。",
    "reductionism": "コンサルタントは顧客調査を評価する際の還元主義に注意した。",
    "exponent": "アナリストは指数が財務モデルに与える影響を説明した。",
    "immanent": "支払いシステムの元の設計にはリスクが内在していた。",
    "mutability": "ソフトウェアは変更しやすいため、チームは業務の流れを素早く更新できる。",
    "quantum": "会社は将来の安全ツールのため量子コンピューティング研究に投資した。",
    "empirically": "チームは発売前に新しい包装を実証的に試験した。",
    "entropy": "技術者はエントロピーが工程の効率に与える影響を説明した。",
    "qualitatively": "マネージャーは価格を確認する前にサービスプランを定性的に比較した。",
    "imprecision": "住所の不正確さが出荷品の返送を招いた。",
    "heterogeneity": "調査は会社の顧客層の異質性を反映している。",
    "determinism": "アナリストは予測モデルを説明する際に決定論を議論した。",
    "materiality": "監査担当者は会計上の誤りの重要性を評価した。",
    "periodicity": "報告書は月次需要の周期性を特定している。",
    "compounded": "2社の仕入先が締め切りに遅れたため、会社は複合的な費用を負担した。",
    "generalised": "研修担当者は全支店で使える一般化された手順を用意した。",
    "instill": "オリエンテーションは新入社員に自信を植え付けることを目的としている。",
    "fractional": "投資家はファンドの一部持分を購入した。",
    "galactic": "そのプロジェクトに途方もない予算は必要なく、地域の解決策で十分だった。",
    "singularity": "技術者は報告書を公開する前にデータの特異点を説明した。",
    "corroborate": "監査担当者は報告書を承認する前に数値を裏付けた。",
    "assessable": "マネージャーは各営業担当者に評価可能な目標を設定した。",
    "homogeneity": "品質チームは各生産バッチの均質性を確認している。",
    "invariance": "アナリストは地域間で価格規則が不変か試験した。",
    "generalized": "会社は全部署向けの一般化されたチェックリストを作成した。",
    "hypothesize": "運用チームは監査前に遅延の原因を仮定する。",
    "enlighten": "専門家は新しいコンプライアンス方針について顧客の理解を深める。",
    "aberration": "監査担当者は異常な支払いを確認が必要な逸脱とみなした。",
    "mutable": "業務フローは変更可能なので、規制が変わればマネージャーが修正できる。",
    "immutable": "書庫には署名済み契約書の変更できない写しが保存されている。",
    "cosmic": "保険プランは通常のリスクを補償するが、宇宙規模の事象は対象外だ。",
    "resonance": "そのキャンペーンは若い顧客に強く響いた。",
    "opacity": "価格方針の不透明さが料金への顧客の不安を招いた。",
    "oceanography": "会社は沿岸施設を計画する前に海洋学の専門家へ相談した。",
    "microbiologist": "メーカーは製品の安全性について微生物学者に連絡した。",
    "histology": "研究所は医療製品を評価するため組織学の結果を使った。",
    "baccalaureate": "応募者は採用フォームに学士号を記載した。",
    "extraterrestrial": "博物館は地球外研究についての展示を準備した。",
    "meteoroid": "天文台は報告を発行する前に流星物質を追跡した。",
    "biologic": "会社は生物学的材料を輸送する際、特別な規則に従っている。",
    "subspecies": "保全チームは施設の近くで見つかった亜種を記録した。",
    "phenotype": "研究チームは試験中、各植物の表現型を記録した。",
    "geneticist": "会社は研究所の安全計画を遺伝学者に確認してもらった。",
    "formulate": "運用チームは製品発売の計画を明確にまとめる。",
    "academe": "会社は職場技術を開発するため学界と協力している。",
    "postdoc": "研究所は製品試験チームを支援する博士研究員を雇った。",
    "curricular": "研修部長は資格認定に必要な教育課程を確認した。",
    "academician": "会社は研究提携について助言を求めて学者を招いた。",
    "polytechnic": "メーカーは地元の工科専門学校から技術者を採用した。",
    "bioethics": "取締役会は医療研究を承認する前に生命倫理を議論した。",
    "subconscious": "コンサルタントは潜在的な好みが購買決定に与える影響を説明した。",
    "extraversion": "人事チームはリーダーシップ研修で外向性について議論した。",
    "speciation": "博物館の展示は来訪者に種分化を説明している。",
    "behaviorist": "会社は顧客調査を設計する際、行動主義心理学者に相談した。",
    "circadian": "マネージャーは夜勤の予定を作る際、概日リズムを考慮した。",
    "provost": "大学の学務担当副学長が大学提携会議で会社を訪問した。",
    "paleontology": "博物館は新しい展示のため古生物学の専門家を雇った。",
    "radioactivity": "研究所は発送前に素材の放射能を検査した。",
    "botanist": "会社は農業施設を拡張する前に植物学者へ連絡した。",
    "thermodynamics": "技術者は暖房システムの改善に熱力学を応用した。",
    "coeducational": "会社は採用のため男女共学の大学と提携した。",
    "bioscience": "企業はより安全な医療製品を開発するため生命科学に投資した。",
    "crustacean": "レストランの仕入先は甲殻類の出荷品の鮮度を確認している。",
    "neuroscience": "会社は研修アプリの改善に神経科学の研究を利用している。",
    "astrophysics": "博物館は科学イベントに天体物理学の専門家を招いた。",
    "naturalist": "リゾートは自然遊歩道を拡張する前に博物学者に相談した。",
    "lactose": "製品ラベルには飲料に乳糖が含まれるか記載されている。",
    "peroxide": "研究所は過酸化物を明確に表示した棚に保管している。",
    "anthropological": "コンサルタントは地域顧客の習慣について人類学的な視点を示した。",
    "metaphysics": "書店はオンラインカタログに形而上学のコーナーを追加した。",
    "collegial": "部署には協力を促す同僚間の友好的な雰囲気がある。",
    "genomics": "研究所は医療製品の開発にゲノム学を利用している。",
    "mainstreamed": "会社は新しいソフトウェア全体にアクセシビリティ機能を統合した。",
    "pedagogical": "研修担当者は新入社員に合った教授法を使った。",
    "hybridization": "農業チームは作物の品種改良のため交雑を研究した。",
    "educationist": "会社は研修プログラムの確認に教育学者を招いた。",
    "nanotube": "メーカーは生産開始前にナノチューブのコーティングを検査した。",
    "recombination": "遺伝学部長は技術説明会で遺伝子再結合を説明した。",
    "transcribe": "アシスタントは監査前に会議録音を文字に起こす。",
    "cosmology": "博物館は宇宙展示のため宇宙論の専門家を雇った。",
    "pedagogy": "研修マネージャーは新講座の教授法を確認した。",
    "seminary": "会社は神学校の図書館にコンピューターを寄付した。",
    "educative": "顧客向け研修会は教育的で実践的になるよう設計された。",
    "metallurgy": "メーカーは新合金について冶金学の専門家に相談した。",
    "allele": "研究チームは植物研究中に各対立遺伝子を記録した。",
    "dissociate": "会社は論争のある仕入先からブランドを切り離すことにした。",
    "maturation": "マネージャーはプロジェクトの成熟が発売日に与える影響を説明した。",
    "reverberation": "会議室の残響で発表者の声が聞き取りにくかった。",
    "co-occurrence": "アナリストは配送遅延と苦情の同時発生を調べた。",
    "ornithologist": "建設会社は現場を整地する前に鳥類学者へ相談した。",
    "pharmacology": "研究所は新薬のため薬理学の専門家を雇った。",
    "thermodynamic": "技術者は暖房システムの熱力学的な制約をモデル化した。",
    "etymological": "編集者は製品名の語源を確認した。",
    "encyclopedic": "コンサルタントは物流業界について百科事典のような知識を持っている。",
    "gravitationally": "技術者は機器が重力の作用で安定する仕組みを説明した。",
    "accreditation": "研修プログラムは業界団体から認定を受けた。",
    "correlative": "報告書は対応時間と顧客定着率の相関関係を示した。",
    "electrochemical": "研究所は新車用の電気化学電池を試験した。",
    "topographical": "調査には建設現場の地形図が含まれていた。",
    "electrostatic": "技術者は静電気放電がチップを損傷する仕組みを説明した。",
    "metamorphose": "古い手続きはデジタルサービスへ完全に変わる可能性がある。",
    "theology": "出版社は学術カタログに神学のコーナーを加えた。",
    "doctrine": "コンプライアンスマニュアルは方針の根底にある教義を説明している。",
    "vocalization": "スピーチ講師は発表中のマネージャーの発声を分析した。",
    "incandescent": "工場は白熱電球を省エネ照明に交換した。",
    "coagulation": "研究所は医療試験中の血液凝固を監視している。",
    "reflectivity": "技術者は安全標識の反射率を測定した。",
    "matriculation": "大学は資格講座への入学登録の手順を送った。",
    "expository": "報告書は新しい手順を説明する解説的な文体を使っている。",
    "gravitation": "技術者は昇降装置を設計する際に引力を考慮した。",
    "anthropomorphic": "広告はサービスを説明するため擬人化したキャラクターを使っている。",
    "backwardness": "コンサルタントはデジタル化の遅れが支店の競争力を損なうと警告した。",
    "attentiveness": "上司は安全説明中の従業員の注意深さを評価した。",
    "interplanetary": "航空宇宙企業は惑星間ミッション用の機器を開発している。",
    "thermonuclear": "研究所は熱核物質について厳格な規則に従っている。",
    "sedimentary": "地質学者は建設現場で堆積岩を特定した。",
    "inactivate": "運用チームはログイン失敗が続いた後、監査前にアカウントを無効化する。",
    "biochemist": "生化学者は酵素が製品配合に与える影響を実演した。",
    "carotenoid": "メーカーは食品添加物を承認する前にカロテノイドを検査した。",
    "pleistocene": "博物館は来訪者向けに更新世の展示を用意した。",
    "toxicology": "研究所は製品発売前に毒性検査を完了した。",
    "orthographic": "編集者は顧客向けマニュアルの綴りの誤りを直した。",
    "permutation": "アナリストは配送予定のあらゆる並べ替えを試験した。",
    "refraction": "技術者は光学センサーの屈折を測定した。",
    "zoological": "会社は動物施設の設計で動物学の基準に従った。",
    "earthbound": "展示は地上用機器と宇宙用機器の違いを説明している。",
    "optically": "技術者は表面の傷を光学的に検査した。",
    "polymer": "メーカーは生産開始前にポリマーを検査した。",
    "paraprofessional": "診療所は看護スタッフを支援する専門職補助員を雇った。",
    "prognostic": "医療チームは治療を勧める前に予後指標を確認した。",
    "precipitous": "需要の急激な落ち込みで会社は予測を修正した。",
    "aeronautics": "航空学の責任者は航空機の安全を高めるシミュレーションを分析した。",
    "inflection": "講師は抑揚が顧客電話の口調を変える仕組みを説明した。",
    "synergistic": "提携によって営業とデザインの間に相乗効果が生まれた。",
    "coloration": "デザイナーは製品包装の配色を調整した。",
    "inhibitory": "新方針には不要な支出を抑制する効果がある。",
    "prospectus": "編集者は公開前に案内書を確認した。",
    "repulsion": "技術者は反発力が磁気部品に与える影響を説明した。",
    "plagiarism": "出版社のソフトウェアは提出原稿の盗用を検出する。",
    "implosion": "技術者はタンク内部の内破による安全リスクを説明した。",
    "irreducible": "アナリストは生産工程の削減できない費用を特定した。",
    "organelle": "研究所は製品試験中の細胞小器官の反応を記録した。",
    "photosynthetic": "会社は温室パネル用の光合成コーティングを開発した。",
})

EN.update({
    "infection": "The workplace clinic reported an infection according to its medical protocol.",
    "jacket": "The company provides a jacket for employees who work outdoors.",
    "regularly": "The equipment is regularly inspected by the maintenance team.",
    "resort": "The company selected a resort for the annual management retreat.",
    "iron": "The technician used an iron to repair the fabric sample.",
    "membership": "The membership includes access to the company's business lounge.",
    "pure": "The manufacturer uses pure water in the production process.",
    "quantity": "Please confirm the quantity of products required for the order.",
    "newly": "The newly opened training center serves employees from three branches.",
    "mate": "Her business mate helped negotiate the overseas contract.",
    "occasionally": "The manager occasionally works from the regional office.",
    "tap": "Tap the screen to confirm the delivery address.",
    "lip": "The technician checked the lip of the container for cracks.",
    "lend": "The bank agreed to lend the company money for the expansion.",
    "translate": "The agency will translate the safety manual into three languages.",
    "pleasant": "The receptionist created a pleasant atmosphere for the visiting clients.",
    "overseas": "The company plans to open an overseas office next year.",
    "rough": "The contractor gave us a rough estimate for the renovation.",
    "pen": "The farm keeps the animals in a secure pen.",
    "recovery": "The IT team completed recovery of the missing files.",
    "seal": "Please seal the package before giving it to the courier.",
    "tube": "The laboratory stored the sample in a sealed tube.",
    "tower": "The company rented office space in the new tower.",
    "spin": "The marketing team will spin the announcement as a customer benefit.",
    "operator": "The machine operator completed the safety checklist.",
    "infant": "The clinic provides a quiet room for employees with infants.",
    "mount": "The technician will mount the screen on the conference-room wall.",
    "wrap": "Please wrap the fragile equipment before shipping it.",
    "virus": "The IT department updated the software to protect against a virus.",
    "teenager": "The company offers a summer work program for teenagers.",
    "musician": "The hotel hired a musician for the company anniversary dinner.",
    "shower": "The hotel repaired the shower before the guests arrived.",
    "illegal": "The company dismissed the contractor for using an illegal payment method.",
    "consultant": "The consultant recommended changes to the procurement process.",
    "historian": "The museum hired a historian to prepare the company's heritage exhibit.",
    "visual": "The designer created a visual guide to the new procedure.",
    "stupid": "It would be stupid to ignore the warning from the safety officer.",
    "keen": "The new manager is keen to improve customer retention.",
    "twin": "The company installed twin servers to protect the database.",
    "sand": "The contractor delivered sand for the construction project.",
    "prompt": "The support team gave a prompt response to the customer's complaint.",
    "react": "The team must react quickly to changes in customer demand.",
    "rescue": "The safety team rescued a worker from the damaged lift.",
    "mess": "The contractor cleaned the mess left after the renovation.",
    "league": "The company sponsors a local sports league.",
    "rapid": "The rapid growth of online sales required more warehouse space.",
    "regret": "The supplier may regret ignoring the revised delivery instructions.",
    "opponent": "The sales team studied its main opponent before the presentation.",
    "resist": "The packaging must resist moisture during overseas shipping.",
})

JA.update({
    "infection": "職場の診療所は医療手順に従って感染を報告した。",
    "jacket": "会社は屋外で働く従業員にジャケットを支給している。",
    "regularly": "機器は保守チームによって定期的に点検される。",
    "resort": "会社は年次管理職研修会の会場にリゾートを選んだ。",
    "iron": "技術者は布地のサンプルを直すためアイロンを使った。",
    "membership": "会員資格には会社のビジネスラウンジの利用が含まれる。",
    "pure": "メーカーは製造工程で純水を使っている。",
    "quantity": "注文に必要な製品数量を確認してください。",
    "newly": "新しく開設された研修センターは3支店の従業員を受け入れる。",
    "mate": "彼女の仕事仲間は海外契約の交渉を手伝った。",
    "occasionally": "マネージャーは時々地域オフィスで仕事をする。",
    "tap": "画面をタップして配送先住所を確認してください。",
    "lip": "技術者は容器の縁にひびがないか確認した。",
    "lend": "銀行は拡張資金を会社に貸すことに同意した。",
    "translate": "代理店は安全マニュアルを3言語に翻訳する。",
    "pleasant": "受付係は来訪した顧客が心地よく過ごせる雰囲気を作った。",
    "overseas": "会社は来年、海外オフィスを開設する予定だ。",
    "rough": "請負業者は改修費用のおおよその見積もりを出した。",
    "pen": "農場は動物を安全な囲いに入れている。",
    "recovery": "ITチームは紛失したファイルの復旧を完了した。",
    "seal": "宅配業者に渡す前に荷物を封じてください。",
    "tube": "研究所はサンプルを密閉した試験管に保管した。",
    "tower": "会社は新しいタワーのオフィスを借りた。",
    "spin": "マーケティングチームは発表を顧客メリットとして伝える。",
    "operator": "機械の操作者は安全チェックリストを完了した。",
    "infant": "診療所は乳児のいる従業員向けに静かな部屋を用意している。",
    "mount": "技術者は会議室の壁に画面を取り付ける。",
    "wrap": "発送前に壊れやすい機器を包んでください。",
    "virus": "IT部門はウイルスから守るためソフトウェアを更新した。",
    "teenager": "会社は10代の若者向けに夏の就業プログラムを提供している。",
    "musician": "ホテルは会社の記念夕食会のため音楽家を雇った。",
    "shower": "ホテルは宿泊客の到着前にシャワーを修理した。",
    "illegal": "会社は違法な支払い方法を使った請負業者を解雇した。",
    "consultant": "コンサルタントは調達手続きの変更を勧めた。",
    "historian": "博物館は会社の歴史展示を準備するため歴史家を雇った。",
    "visual": "デザイナーは新しい手順の視覚的なガイドを作った。",
    "stupid": "安全担当者の警告を無視するのは愚かなことだ。",
    "keen": "新しいマネージャーは顧客定着率の改善に熱心だ。",
    "twin": "会社はデータベースを守るため二重のサーバーを設置した。",
    "sand": "請負業者は建設プロジェクト用の砂を納品した。",
    "prompt": "サポートチームは顧客の苦情に迅速に対応した。",
    "react": "チームは顧客需要の変化に素早く対応しなければならない。",
    "rescue": "安全チームは損傷したエレベーターから作業員を救出した。",
    "mess": "請負業者は改修後に残った混乱を片付けた。",
    "league": "会社は地元のスポーツリーグを後援している。",
    "rapid": "オンライン売上の急速な成長により、より広い倉庫が必要になった。",
    "regret": "仕入先は改訂版の配送指示を無視したことを後悔するかもしれない。",
    "opponent": "営業チームはプレゼンテーション前に主な競争相手を調べた。",
    "resist": "包装は海外輸送中の湿気に耐えなければならない。",
})

def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 3][:300]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        source = EN[word]
        item["example"] = source
        example = translations.setdefault(f"builtin:{item['id']}", {}).setdefault("example", {})
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if example.get(field) != value:
                example[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 700+ English examples batch 1: {len(level_rows)} terms, {changed} fields")

if __name__ == "__main__":
    main()
