#!/usr/bin/env python3
"""Review 300 TOEIC 600+ examples (items 101-400) in English and Japanese."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"


EN = {
    "several": "Several suppliers submitted revised quotations.",
    "remember": "Please remember to attach the receipt before submitting the report.",
    "share": "The team will share the results with the client tomorrow.",
    "real": "The company faces real challenges in the overseas market.",
    "sit": "The visitors may sit in the reception area.",
    "subject": "The subject of the meeting was the revised budget.",
    "town": "The company opened a branch in a nearby town.",
    "remain": "A few tasks remain before the project can be completed.",
    "top": "The sales representative was at the top of the list.",
    "win": "Our team hopes to win the contract this year.",
    "reach": "The team will reach an agreement before the deadline.",
    "social": "The company uses social media to communicate with customers.",
    "type": "Please select the type of service you need.",
    "sound": "The alarm sounded when the door was opened.",
    "receive": "You will receive the revised invoice by email.",
    "sale": "The store announced a sale on office furniture.",
    "require": "The position requires experience in customer service.",
    "wait": "Please wait outside the supervisor's office.",
    "toward": "The company is moving toward paperless operations.",
    "team": "The project team meets every Monday.",
    "sense": "The manager showed a strong sense of responsibility.",
    "rule": "All employees must follow the safety rules.",
    "produce": "The factory produces parts for the automotive industry.",
    "sell": "The team will sell the product before the deadline.",
    "short": "The company offers a short training course for new staff.",
    "research": "The company invested in market research before launching the product.",
    "situation": "The manager explained the situation to the client.",
    "staff": "The hotel staff prepared the conference room.",
    "war": "The company donated supplies to people affected by the war.",
    "shop": "The company opened a new shop near the station.",
    "someone": "Someone from the purchasing department will contact you.",
    "special": "The client requested special packaging for the shipment.",
    "sometimes": "The system sometimes requires a manual restart.",
    "table": "The manager put the survey results in a table.",
    "strong": "The company has a strong reputation for quality.",
    "rise": "Costs may rise after the system is updated.",
    "role": "The manager explained my role in the project.",
    "step": "The first step is to confirm the delivery address.",
    "true": "The report confirms that the statement is true.",
    "themselves": "The employees completed the training materials themselves.",
    "white": "The warehouse uses white labels for domestic shipments.",
    "wear": "Employees must wear safety glasses in the warehouse.",
    "raise": "The company plans to raise salaries next year.",
    "site": "The construction site will close during the holiday.",
    "teacher": "The training manager invited a teacher to lead the workshop.",
    "sign": "Please sign the contract at the bottom of the page.",
    "relationship": "The company values its relationship with local suppliers.",
    "travel": "My colleague plans to travel abroad for work.",
    "regard": "The manager showed regard for the employees' concerns.",
    "range": "The store offers a wide range of office supplies.",
    "quality": "The quality of the products improved this quarter.",
    "project": "The project will be completed by the end of the month.",
    "round": "The manager requested one more round of revisions.",
    "road": "The road to the warehouse is closed for repairs.",
    "wish": "The client wishes to change the delivery date.",
    "therefore": "The shipment was delayed; therefore, the customer was notified.",
    "rest": "The technician took a short rest after the repair.",
    "serve": "The team will serve customers before the deadline.",
    "teach": "The trainer will teach the procedure to new employees.",
    "education": "The company provides continuing education for employees.",
    "security": "The security team checked the entrance.",
    "trade": "The latest report explains how trade affected local businesses.",
    "risk": "The report identifies the risk of data loss.",
    "standard": "The product meets the required safety standard.",
    "vote": "The committee will vote on the proposal tomorrow.",
    "stage": "The project is at an important stage of development.",
    "space": "The warehouse has enough space for the new inventory.",
    "unit": "Each unit of the report covers a separate stage of the process.",
    "realize": "The team realized that the invoice contained an error.",
    "usually": "The branch usually receives orders in the morning.",
    "single": "A single mistake can delay the entire shipment.",
    "society": "The company supports projects that benefit society.",
    "technology": "The IT department monitored the technology after the update.",
    "save": "Please save a copy of the revised contract.",
    "total": "The invoice shows the total amount due.",
    "wrong": "The documents were sent to the wrong branch.",
    "upon": "Upon arrival, please report to the reception desk.",
    "reduce": "The team will reduce expenses before the deadline.",
    "evidence": "The audit found evidence of duplicate payments.",
    "similar": "The two products have similar designs.",
    "street": "The new office is on a busy street.",
    "wife": "His wife works for an international company.",
    "sport": "The company sponsors a local sports team.",
    "response": "The customer service team sent a quick response.",
    "voice": "The automated system recognizes the customer's voice.",
    "suppose": "I suppose the supplier will confirm the date today.",
    "president": "The president approved the expansion plan.",
    "store": "The store displays the new products near the entrance.",
    "knowledge": "Her knowledge of the software helped the team solve the problem.",
    "source": "Please identify the source of the information.",
    "simply": "The supervisor said we could simply email the administrator.",
    "surprise": "The sudden price increase surprised the customer.",
    "pretty": "The new office is pretty close to the station.",
    "recently": "The company recently opened a regional office.",
    "recent": "The company adopted a recent software update.",
    "relate": "The training relates directly to the employee's duties.",
    "private": "The meeting will be held in a private room.",
    "worry": "Please do not worry about the delivery delay.",
    "summer": "The company hires interns during the summer.",
    "represent": "The sales manager will represent the company at the conference.",
    "wonder": "The manager wondered why the shipment was late.",
    "structure": "The report explains the structure of the organization.",
    "section": "Please read the safety section of the manual.",
    "worker": "The factory worker inspected the machine.",
    "press": "The company issued a press release about the merger.",
    "whatever": "Please report whatever problem you encounter.",
    "region": "The company serves customers throughout the region.",
    "respect": "The manager treats all employees with respect.",
    "various": "The company considered various options before selecting a supplier.",
    "thus": "The bus was late; thus, the meeting started late.",
    "skill": "The job requires strong communication skills.",
    "son": "Her son works in the company's sales department.",
    "simple": "The new process is simple and easy to follow.",
    "stock": "The finance manager explained how a stock represents ownership of a company.",
    "yesterday": "The supplier sent the revised quotation yesterday.",
    "size": "Please confirm the size of the replacement part.",
    "station": "The branch is close to the train station.",
    "production": "The factory increased production this month.",
    "significant": "The manager announced a significant change in the schedule.",
    "wall": "The technician repaired a crack in the office wall.",
    "series": "The company released a series of training videos.",
    "success": "The product launch was a success.",
    "tomorrow": "The office will reopen tomorrow.",
    "review": "The team will review the report before the deadline.",
    "race": "The company entered a race to develop the product first.",
    "recognize": "The manager recognized the employee's contribution.",
    "window": "Please close the office window before leaving.",
    "purpose": "The purpose of the meeting is to review the budget.",
    "tree": "The company planted a tree for every new employee.",
    "college": "The company recruited interns from a local college.",
    "prove": "The audit will prove whether the figures are accurate.",
    "season": "The store hires extra staff during the holiday season.",
    "stuff": "Please move your personal belongings before the meeting.",
    "wide": "The company offers a wide range of products.",
    "analysis": "The sales analysis showed that demand had increased.",
    "sorry": "I am sorry, but the meeting has been postponed.",
    "statement": "The manager issued a statement about the schedule change.",
    "ready": "The revised contract is ready for signature.",
    "strike": "The workers threatened to strike over the contract terms.",
    "seek": "The team will seek approval before the deadline.",
    "quickly": "The team responded quickly to the customer's request.",
    "release": "The company will release the product next month.",
    "tax": "The latest report explains how the tax affected local businesses.",
    "solution": "The team proposed a solution to the delivery problem.",
    "specific": "The client requested a specific delivery date.",
    "television": "The company advertised the product on television.",
    "serious": "The missing report was a serious problem.",
    "target": "The sales team reached its target this quarter.",
    "degree": "The position requires a degree in accounting.",
    "pull": "Please pull the door firmly to close it.",
    "red": "The warehouse uses red labels for urgent shipments.",
    "treat": "The clinic treats employees with minor injuries.",
    "shall": "The contract states that the supplier shall deliver by Friday.",
    "pressure": "The manager worked under pressure to meet the deadline.",
    "treatment": "The clinic provides treatment for minor injuries.",
    "yourself": "Please introduce yourself to the new client.",
    "supply": "The company will supply equipment to the new branch.",
    "village": "The company supports a school in a nearby village.",
    "worth": "The investment is worth the additional cost.",
    "score": "The training score improved after the review.",
    "trip": "The assistant arranged a business trip for the director.",
    "sleep": "Employees need enough sleep to work safely.",
    "promise": "The supplier promised to deliver the order on Friday.",
    "trouble": "The technician had trouble starting the machine.",
    "relation": "The report examines the relation between price and demand.",
    "touch": "Please do not touch the equipment during the test.",
    "middle": "The meeting is scheduled for the middle of the quarter.",
    "suffer": "The company may suffer a loss if the order is canceled.",
    "strategy": "The report explains the company's marketing strategy.",
    "tend": "New employees tend to ask many questions during orientation.",
    "star": "The hotel received a star for excellent service.",
    "network": "The IT department monitored the network after the update.",
    "operation": "The report explains the operation of the new machine.",
    "match": "The supplier's quotation matches our budget.",
    "seat": "Please reserve a seat for the visiting client.",
    "throw": "Please do not throw the packaging away.",
    "task": "The manager assigned a task to each employee.",
    "normal": "It is normal for new employees to feel nervous during their first week.",
    "positive": "The company received positive feedback from customers.",
    "option": "The client has three delivery options.",
    "message": "The administrator sent a message about the deadline.",
    "style": "The architect's style combines glass walls with traditional brick details.",
    "refer": "Please refer to the agenda before the meeting.",
    "push": "Please push the button to start the machine.",
    "quarter": "The payment is due next quarter.",
    "successful": "The product launch was successful.",
    "sing": "The performers may sing at the company event.",
    "theory": "The manager explained the theory behind the new process.",
    "propose": "The team will propose a solution before the deadline.",
    "reference": "Please include a reference to the original contract.",
    "pattern": "The analyst identified a pattern in the sales data.",
    "obviously": "Obviously, the delivery date must be confirmed.",
    "unclear": "The instructions were unclear, so I asked my supervisor for help.",
    "search": "The team will search the database for the missing record.",
    "separate": "Please separate the damaged products from the others.",
    "speech": "The president gave a speech at the annual meeting.",
    "officer": "The safety officer inspected the warehouse.",
    "throughout": "The policy applies throughout the company.",
    "oil": "The factory uses less oil after the equipment upgrade.",
    "profit": "The latest report explains how profit changed this quarter.",
    "protect": "The team will protect customer data.",
    "resource": "The manager allocated resources to the new project.",
    "science": "The company uses science to develop safer products.",
    "operate": "The machine will operate automatically after the update.",
    "reflect": "The performance review will reflect the employee's progress.",
    "useful": "The new software is useful for tracking expenses.",
    "restaurant": "The office restaurant serves affordable vegetarian meals.",
    "property": "The company purchased property near the airport.",
    "previous": "The previous manager approved the original schedule.",
    "okay": "The revised delivery date is okay with the customer.",
    "post": "The company will post the vacancy on its website.",
    "newspaper": "The journalist compared a newspaper article with its online source.",
    "weekend": "The office will be closed this weekend.",
    "perform": "The team will perform a safety check before opening.",
    "professional": "The company maintains a professional workplace.",
    "mine": "The company closed the mine for safety inspections.",
    "memory": "The device has enough memory to store the files.",
    "song": "The company used a song in its new advertisement.",
    "object": "The object of this meeting is to review the budget.",
    "ring": "The phone will ring when the customer calls.",
    "prefer": "The client prefers a later delivery date.",
    "possibility": "There is a possibility that the shipment will be delayed.",
    "variety": "The cafeteria offers a variety of vegetarian meals.",
    "screen": "The technician replaced the damaged screen.",
    "track": "The team will track the shipment online.",
    "responsibility": "The manager assigned responsibility for the report to Anna.",
    "original": "The company developed an original approach to the problem.",
    "sister": "Her sister works at the regional office.",
    "rock": "The construction crew removed a rock from the site.",
    "nor": "The warranty covers neither labor nor replacement parts.",
    "university": "The company partnered with a university to develop new software.",
    "yeah": "Yeah, I can send the revised quotation this afternoon.",
    "weight": "Please check the weight of the package.",
    "proposal": "The board approved the proposal after a brief discussion.",
    "version": "Please download the newest version of the agenda.",
    "somebody": "Somebody from the sales team will call you shortly.",
    "pound": "The package weighs five pounds.",
    "shape": "The package arrived in good shape.",
    "sea": "The company ships products by sea.",
    "welcome": "The team will welcome the guests before the meeting.",
    "smile": "The customer smiled after receiving the quick response.",
    "traditional": "The company uses traditional methods for quality control.",
    "replace": "The team will replace the damaged equipment.",
    "suddenly": "The machine suddenly stopped during production.",
    "purchase": "The department approved my purchase of specialized software.",
    "shoot": "The team will shoot a video for the new product.",
    "unless": "The shipment will arrive on time unless the weather changes.",
    "recommend": "I recommend meeting the supervisor before making a decision.",
    "survey": "The company conducted a survey of customer satisfaction.",
    "stick": "Please stick the label on the outside of the box.",
    "request": "The manager approved the customer's request.",
    "rich": "The soil is rich enough to support the farm's crops.",
    "wind": "Strong wind delayed the delivery flight.",
    "none": "None of the suppliers could meet the original deadline.",
    "warm": "The hotel provided a warm welcome to the guests.",
    "scene": "The security camera recorded the scene.",
    "writer": "The writer prepared an article for the company magazine.",
    "prevent": "The team will prevent further damage before the deadline.",
    "safe": "Please keep the documents in a safe place.",
    "mix": "The machine mixes the ingredients automatically.",
    "medical": "The company provides medical insurance to employees.",
    "telephone": "Please answer the telephone at the reception desk.",
    "trial": "The company offered a free trial of the software.",
    "stress": "The counselor taught employees how stress can affect concentration.",
    "radio": "The company advertised the service on the radio.",
    "text": "Please text the client when the shipment arrives.",
    "ride": "Employees can ride the shuttle bus to the branch.",
    "remove": "The team will remove the damaged products.",
    "otherwise": "Please confirm the order; otherwise, it may be canceled.",
    "title": "The title of the report is listed on the cover.",
    "sample": "The supplier sent a sample of the new material.",
    "sex": "The survey asked employees to report their sex voluntarily.",
    "video": "The training video explains the new procedure.",
    "primary": "The primary purpose of the meeting is to review safety.",
    "weather": "Bad weather delayed the shipment.",
    "principle": "The engineering manager explained the principle behind the design.",
    "straight": "The road runs straight to the warehouse.",
    "trust": "The company has earned the trust of its customers.",
    "wonderful": "The hotel provided wonderful service to the conference guests.",
    "responsible": "The manager is responsible for approving expenses.",
    "negative": "The report showed a negative effect on sales.",
    "relative": "A relative works at the company's regional office.",
    "tour": "The manager gave visitors a tour of the factory.",
    "software": "The engineering manager demonstrated how new software models stress in a bridge design.",
    "pair": "The supplier sent a pair of replacement parts.",
    "ship": "The company will ship the order tomorrow.",
    "observe": "The operations team will observe the safety procedure before the next audit.",
    "sentence": "The contract contains a sentence about late fees.",
    "print": "The team will print the report before the deadline.",
    "progress": "The manager reviewed the project's progress.",
    "truth": "The manager told the truth about the error.",
    "nobody": "Nobody from the supplier's office answered the phone.",
    "speed": "The new system increases the speed of order processing.",
    "politics": "The company monitors politics that may affect trade.",
    "reply": "The team will reply to the client before the deadline.",
    "transfer": "The team will transfer the funds before the deadline.",
    "perfect": "The revised schedule is perfect for the client.",
    "slightly": "The revised schedule is slightly shorter than the original.",
    "overall": "Overall performance improved significantly this year.",
    "user": "The user reported a problem with the application.",
}


JA = {
    "several": "複数の仕入先が改訂版の見積書を提出した。",
    "remember": "報告書を提出する前に領収書を添付するのを忘れないでください。",
    "share": "チームは明日、顧客と結果を共有する。",
    "real": "会社は海外市場で現実的な課題に直面している。",
    "sit": "来訪者は受付エリアで座ってもよい。",
    "subject": "会議の議題は改訂版の予算だった。",
    "town": "会社は近くの町に支店を開設した。",
    "remain": "プロジェクトを完了するまでに残っている作業は少しだけだ。",
    "top": "営業担当者はリストの最上位にいた。",
    "win": "私たちのチームは今年、契約を獲得したいと考えている。",
    "reach": "チームは締め切り前に合意に達する。",
    "social": "会社はソーシャルメディアで顧客と連絡を取っている。",
    "type": "必要なサービスの種類を選択してください。",
    "sound": "ドアが開くと警報が鳴った。",
    "receive": "改訂版の請求書をメールで受け取ります。",
    "sale": "店はオフィス家具のセールを発表した。",
    "require": "その職には顧客サービスの経験が必要だ。",
    "wait": "上司のオフィスの外でお待ちください。",
    "toward": "会社はペーパーレス業務に向かっている。",
    "team": "プロジェクトチームは毎週月曜日に会議をする。",
    "sense": "マネージャーは強い責任感を示した。",
    "rule": "全従業員は安全規則に従わなければならない。",
    "produce": "その工場は自動車産業向けの部品を生産している。",
    "sell": "チームは締め切り前に製品を販売する。",
    "short": "会社は新入社員向けの短期研修を提供している。",
    "research": "会社は製品発売前に市場調査へ投資した。",
    "situation": "マネージャーは顧客に状況を説明した。",
    "staff": "ホテルのスタッフは会議室を準備した。",
    "war": "会社は戦争の影響を受けた人々に物資を寄付した。",
    "shop": "会社は駅の近くに新しい店を開いた。",
    "someone": "購買部の誰かが連絡します。",
    "special": "顧客は出荷品に特別な包装を求めた。",
    "sometimes": "システムは手動で再起動しなければならないことがある。",
    "table": "マネージャーは調査結果を表にまとめた。",
    "strong": "会社は品質について強い評判を得ている。",
    "rise": "システム更新後、費用が上がる可能性がある。",
    "role": "マネージャーはプロジェクトでの私の役割を説明した。",
    "step": "最初のステップは納品先住所を確認することだ。",
    "true": "報告書はその記述が真実だと確認している。",
    "themselves": "従業員は研修資料を自分たちで完成させた。",
    "white": "倉庫では国内配送に白いラベルを使う。",
    "wear": "従業員は倉庫で安全メガネを着用しなければならない。",
    "raise": "会社は来年、給与を引き上げる予定だ。",
    "site": "建設現場は休暇中に閉鎖される。",
    "teacher": "研修マネージャーは講師を招いて研修会を指導してもらった。",
    "sign": "ページ下部の契約書に署名してください。",
    "relationship": "会社は地元の仕入先との関係を重視している。",
    "travel": "同僚は仕事で海外へ行く予定だ。",
    "regard": "マネージャーは従業員の懸念に配慮を示した。",
    "range": "その店は幅広いオフィス用品を扱っている。",
    "quality": "製品の品質は今四半期に向上した。",
    "project": "プロジェクトは月末までに完了する。",
    "round": "マネージャーはもう一度修正を求めた。",
    "road": "倉庫への道路は修理のため閉鎖されている。",
    "wish": "顧客は納品日を変更したいと考えている。",
    "therefore": "出荷が遅れたため、顧客に連絡した。",
    "rest": "技術者は修理後に短い休憩を取った。",
    "education": "会社は従業員に継続教育を提供している。",
    "serve": "チームは締め切り前に顧客へ対応する。",
    "teach": "研修担当者は新入社員に手順を教える。",
    "security": "警備チームは入口を確認した。",
    "trade": "最新の報告書は貿易が地域企業に与えた影響を説明している。",
    "risk": "報告書はデータ損失のリスクを特定している。",
    "standard": "製品は必要な安全基準を満たしている。",
    "vote": "委員会は明日、提案について投票する。",
    "stage": "プロジェクトは重要な開発段階にある。",
    "space": "倉庫には新しい在庫を置く十分なスペースがある。",
    "unit": "報告書の各単位は工程の別の段階を扱っている。",
    "realize": "チームは請求書に誤りがあることに気づいた。",
    "usually": "その支店には通常、午前中に注文が届く。",
    "single": "1つのミスで出荷全体が遅れる可能性がある。",
    "society": "会社は社会に役立つ事業を支援している。",
    "technology": "IT部門は更新後に技術を監視した。",
    "save": "改訂版の契約書のコピーを保存してください。",
    "total": "請求書には支払総額が記載されている。",
    "wrong": "書類が誤った支店に送られた。",
    "upon": "到着したら受付へお越しください。",
    "reduce": "チームは締め切り前に経費を削減する。",
    "evidence": "監査で二重支払いの証拠が見つかった。",
    "similar": "2つの製品は似たデザインをしている。",
    "street": "新しいオフィスは交通量の多い通りにある。",
    "wife": "彼の妻は国際企業に勤めている。",
    "sport": "会社は地元のスポーツチームを支援している。",
    "response": "顧客サービスチームは迅速に返答した。",
    "voice": "自動システムは顧客の声を認識する。",
    "suppose": "仕入先は今日、日付を確認すると思う。",
    "president": "社長は拡張計画を承認した。",
    "store": "店は入口付近に新製品を展示している。",
    "knowledge": "彼女のソフトウェア知識がチームの問題解決に役立った。",
    "source": "その情報源を特定してください。",
    "simply": "上司は管理者にメールするだけでよいと言った。",
    "surprise": "突然の値上げが顧客を驚かせた。",
    "pretty": "新しいオフィスは駅からかなり近い。",
    "recently": "会社は最近、地域オフィスを開設した。",
    "recent": "会社は最近のソフトウェア更新を導入した。",
    "relate": "その研修は従業員の職務に直接関係している。",
    "private": "会議は個室で行われる。",
    "worry": "配送の遅れを心配しないでください。",
    "summer": "会社は夏にインターンを雇う。",
    "represent": "営業部長が会議で会社を代表する。",
    "wonder": "マネージャーはなぜ出荷が遅れたのか不思議に思った。",
    "structure": "報告書は組織の構造を説明している。",
    "section": "マニュアルの安全に関する項目を読んでください。",
    "worker": "工場作業員は機械を点検した。",
    "press": "会社は合併についてプレスリリースを発表した。",
    "whatever": "遭遇した問題は何でも報告してください。",
    "region": "会社は地域全体の顧客にサービスを提供している。",
    "respect": "マネージャーは全従業員を尊重している。",
    "various": "会社は仕入先を選ぶ前にさまざまな選択肢を検討した。",
    "thus": "バスが遅れたため、会議も遅れて始まった。",
    "skill": "その仕事には高いコミュニケーション能力が必要だ。",
    "son": "彼女の息子は会社の営業部で働いている。",
    "simple": "新しい手順は簡単で従いやすい。",
    "stock": "財務マネージャーは株式が会社の所有権を表す仕組みを説明した。",
    "yesterday": "仕入先は昨日、改訂版の見積書を送った。",
    "size": "交換部品のサイズを確認してください。",
    "station": "支店は駅の近くにある。",
    "production": "工場は今月、生産量を増やした。",
    "significant": "マネージャーはスケジュールの重要な変更を発表した。",
    "wall": "技術者はオフィスの壁のひびを修理した。",
    "series": "会社は一連の研修動画を公開した。",
    "success": "製品発売は成功した。",
    "tomorrow": "オフィスは明日再開する。",
    "review": "チームは締め切り前に報告書を確認する。",
    "race": "会社は最初に製品を開発する競争に参加した。",
    "recognize": "マネージャーは従業員の貢献を評価した。",
    "window": "退出する前にオフィスの窓を閉めてください。",
    "purpose": "会議の目的は予算を確認することだ。",
    "tree": "会社は新入社員1人につき1本の木を植えた。",
    "college": "会社は地元の大学からインターンを採用した。",
    "prove": "監査で数値が正確かどうかを証明する。",
    "season": "店は休暇シーズンに臨時スタッフを雇う。",
    "stuff": "会議前に私物を移動してください。",
    "wide": "会社は幅広い製品を提供している。",
    "analysis": "売上分析は需要が増加したことを示した。",
    "sorry": "申し訳ありませんが、会議は延期されました。",
    "statement": "マネージャーはスケジュール変更について声明を出した。",
    "ready": "改訂版の契約書は署名の準備ができている。",
    "strike": "従業員は契約条件をめぐりストライキを予告した。",
    "seek": "チームは締め切り前に承認を求める。",
    "quickly": "チームは顧客の依頼に迅速に対応した。",
    "release": "会社は来月、製品を発売する。",
    "tax": "最新の報告書は税が地域企業に与えた影響を説明している。",
    "solution": "チームは配送問題の解決策を提案した。",
    "specific": "顧客は具体的な納品日を指定した。",
    "television": "会社はテレビで製品を宣伝した。",
    "serious": "報告書の紛失は深刻な問題だった。",
    "target": "営業チームは今四半期に目標を達成した。",
    "degree": "その職には会計学の学位が必要だ。",
    "pull": "ドアをしっかり引いて閉めてください。",
    "red": "倉庫では緊急出荷に赤いラベルを使う。",
    "treat": "診療所は軽傷を負った従業員を治療する。",
    "shall": "契約書には仕入先が金曜までに納品すると記載されている。",
    "pressure": "マネージャーは締め切りを守るためプレッシャーの中で働いた。",
    "treatment": "診療所は軽傷の治療を行っている。",
    "yourself": "新しい顧客に自己紹介してください。",
    "supply": "会社は新しい支店に機器を供給する。",
    "village": "会社は近隣の村の学校を支援している。",
    "worth": "その投資は追加費用に見合う価値がある。",
    "score": "確認後、研修の得点が上がった。",
    "trip": "アシスタントは取締役の出張を手配した。",
    "sleep": "安全に働くには十分な睡眠が必要だ。",
    "promise": "仕入先は金曜に注文品を納品すると約束した。",
    "trouble": "技術者は機械の始動に苦労した。",
    "relation": "報告書は価格と需要の関係を調べている。",
    "touch": "試験中は機器に触れないでください。",
    "middle": "会議は四半期の半ばに予定されている。",
    "suffer": "注文がキャンセルされると会社は損失を被る可能性がある。",
    "strategy": "報告書は会社のマーケティング戦略を説明している。",
    "tend": "新入社員はオリエンテーション中に多くの質問をする傾向がある。",
    "star": "ホテルは優れたサービスで星を獲得した。",
    "network": "IT部門は更新後にネットワークを監視した。",
    "operation": "報告書は新しい機械の操作を説明している。",
    "match": "仕入先の見積もりは当社の予算に合っている。",
    "seat": "来訪する顧客の席を予約してください。",
    "throw": "包装を捨てないでください。",
    "task": "マネージャーは各従業員に作業を割り当てた。",
    "normal": "新入社員が最初の週に緊張するのは普通だ。",
    "positive": "会社は顧客から肯定的なフィードバックを受けた。",
    "option": "顧客には3つの配送方法がある。",
    "message": "管理者は締め切りについてメッセージを送った。",
    "style": "建築家の作風はガラス壁と伝統的なれんがの細部を組み合わせている。",
    "refer": "会議前に議事次第を参照してください。",
    "push": "機械を起動するにはボタンを押してください。",
    "quarter": "支払い期限は来四半期です。",
    "successful": "製品の発売は成功した。",
    "sing": "出演者は会社のイベントで歌うことがある。",
    "theory": "マネージャーは新しい手順の背後にある理論を説明した。",
    "propose": "チームは締め切り前に解決策を提案する。",
    "reference": "元の契約書への参照を含めてください。",
    "pattern": "アナリストは売上データのパターンを特定した。",
    "obviously": "明らかに、納品日を確認する必要がある。",
    "unclear": "指示が不明確だったので、上司に助けを求めた。",
    "search": "チームはデータベースで紛失した記録を検索する。",
    "separate": "破損した製品を他の製品から分けてください。",
    "speech": "社長は年次会議でスピーチをした。",
    "officer": "安全担当者は倉庫を点検した。",
    "throughout": "その方針は会社全体に適用される。",
    "oil": "機器を更新した後、工場は油の使用量を減らした。",
    "profit": "最新の報告書は今四半期の利益の変化を説明している。",
    "protect": "チームは顧客データを保護する。",
    "resource": "マネージャーは新しいプロジェクトに資源を配分した。",
    "science": "会社はより安全な製品の開発に科学を利用している。",
    "operate": "更新後、機械は自動的に動作する。",
    "reflect": "業績評価は従業員の進捗を反映する。",
    "useful": "新しいソフトウェアは経費の追跡に役立つ。",
    "restaurant": "オフィスのレストランは昼休みに手頃な菜食料理を提供する。",
    "property": "会社は空港近くの不動産を購入した。",
    "previous": "前任のマネージャーは元のスケジュールを承認した。",
    "okay": "改訂された納品日は顧客にとって問題ない。",
    "post": "会社はウェブサイトに求人を掲載する。",
    "newspaper": "ジャーナリストは新聞記事とオンライン情報源を比較した。",
    "weekend": "オフィスは今週末閉まっている。",
    "perform": "チームは開業前に安全点検を実施する。",
    "professional": "会社はプロ意識の高い職場環境を維持している。",
    "mine": "会社は安全点検のため鉱山を閉鎖した。",
    "memory": "その機器にはファイルを保存する十分なメモリがある。",
    "song": "会社は新しい広告に曲を使った。",
    "object": "この会議の目的は予算を確認することだ。",
    "ring": "顧客から電話があると電話が鳴る。",
    "prefer": "顧客は遅い納品日を希望している。",
    "possibility": "出荷が遅れる可能性がある。",
    "variety": "食堂はさまざまな菜食料理を提供している。",
    "screen": "技術者は破損した画面を交換した。",
    "track": "チームはオンラインで出荷品を追跡する。",
    "responsibility": "マネージャーは報告書の責任をアンナに割り当てた。",
    "original": "会社はその問題に独自の取り組み方を考案した。",
    "sister": "彼女の姉は地域オフィスで働いている。",
    "rock": "建設作業員は現場から岩を撤去した。",
    "nor": "保証は人件費も交換部品も対象としない。",
    "university": "会社は大学と提携して新しいソフトウェアを開発した。",
    "yeah": "はい、改訂版の見積書を今日の午後送れます。",
    "weight": "荷物の重量を確認してください。",
    "proposal": "取締役会は短い議論の後、提案を承認した。",
    "version": "管理者のウェブサイトから最新の議事次第をダウンロードしてください。",
    "somebody": "営業チームの誰かがまもなく電話します。",
    "pound": "荷物の重量は5ポンドです。",
    "shape": "荷物は良好な状態で届いた。",
    "sea": "会社は海上輸送で製品を発送する。",
    "welcome": "チームは会議前に来訪者を歓迎する。",
    "smile": "迅速な返答を受け、顧客は笑顔になった。",
    "traditional": "会社は品質管理に伝統的な方法を使っている。",
    "replace": "チームは破損した機器を交換する。",
    "suddenly": "生産中に機械が突然停止した。",
    "purchase": "部署は建築スタジオ向けの専門ソフトウェアの購入を承認した。",
    "shoot": "チームは新製品の動画を撮影する。",
    "unless": "天候が変わらなければ、出荷品は時間どおり到着する。",
    "recommend": "決定する前に上司と会うことを勧めます。",
    "survey": "会社は顧客満足度の調査を実施した。",
    "stick": "箱の外側にラベルを貼ってください。",
    "request": "マネージャーは顧客の依頼を承認した。",
    "rich": "その土壌は農作物を育てるのに十分肥沃だ。",
    "wind": "強風で配送便が遅れた。",
    "none": "元の締め切りを守れる仕入先はなかった。",
    "warm": "ホテルは来訪者を温かく迎えた。",
    "scene": "防犯カメラがその場面を記録した。",
    "writer": "作家は社内誌の記事を準備した。",
    "prevent": "チームは締め切り前にさらなる損害を防ぐ。",
    "safe": "書類を安全な場所に保管してください。",
    "mix": "機械は材料を自動的に混ぜる。",
    "medical": "会社は従業員に医療保険を提供している。",
    "telephone": "受付の電話に出てください。",
    "trial": "会社はソフトウェアの無料試用を提供した。",
    "stress": "カウンセラーはストレスが集中力に与える影響を従業員に教えた。",
    "radio": "会社はラジオでサービスを宣伝した。",
    "text": "出荷品が到着したら顧客にメッセージを送ってください。",
    "ride": "従業員はシャトルバスに乗って支店へ行ける。",
    "remove": "チームは破損した製品を取り除く。",
    "otherwise": "注文を確認してください。そうしないとキャンセルされる可能性があります。",
    "title": "報告書の題名は表紙に記載されている。",
    "sample": "仕入先は新素材のサンプルを送った。",
    "sex": "調査では従業員に性別の任意回答を求めた。",
    "video": "研修動画は新しい手順を説明している。",
    "primary": "会議の主な目的は安全を確認することだ。",
    "weather": "悪天候で出荷が遅れた。",
    "principle": "技術責任者は設計の原理を説明した。",
    "straight": "道路は倉庫までまっすぐ続いている。",
    "trust": "会社は顧客の信頼を得ている。",
    "wonderful": "ホテルは会議の参加者にすばらしいサービスを提供した。",
    "responsible": "マネージャーは経費の承認に責任を持つ。",
    "negative": "報告書は売上への悪影響を示した。",
    "relative": "親族が会社の地域オフィスで働いている。",
    "tour": "マネージャーは来訪者に工場を案内した。",
    "software": "技術責任者は新しいソフトウェアが橋の設計の応力をモデル化する仕組みを説明した。",
    "pair": "仕入先は交換部品を1組送った。",
    "ship": "会社は明日、注文品を発送する。",
    "observe": "運用チームは次回の監査前に安全手順を観察する。",
    "sentence": "契約書には延滞料金についての一文がある。",
    "print": "チームは締め切り前に報告書を印刷する。",
    "progress": "マネージャーはプロジェクトの進捗を確認した。",
    "truth": "マネージャーは誤りについて真実を話した。",
    "nobody": "仕入先のオフィスから電話に出る人は誰もいなかった。",
    "speed": "新しいシステムは注文処理の速度を高める。",
    "politics": "会社は貿易に影響する政治情勢を監視している。",
    "reply": "チームは締め切り前に顧客へ返信する。",
    "transfer": "チームは締め切り前に資金を振り込む。",
    "perfect": "改訂版のスケジュールは顧客にとって理想的だ。",
    "slightly": "改訂版のスケジュールは元のものより少し短い。",
    "overall": "今年、全体的な業績は大幅に改善した。",
    "user": "利用者はアプリケーションの問題を報告した。",
}


def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 2][100:400]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        item["example"] = EN[word]
        key = f"builtin:{item['id']}"
        example = translations.setdefault(key, {}).setdefault("example", {})
        source = EN[word]
        if example.get("source") != source:
            example["source"] = source
            changed += 1
        if example.get("en") != source:
            example["en"] = source
            changed += 1
        if example.get("ja") != JA[word]:
            example["ja"] = JA[word]
            changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 600+ English examples batch 2: {len(level_rows)} terms, {changed} fields")


if __name__ == "__main__":
    main()
