#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Review 700+ examples 1201-1350 in English and Japanese."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
VOCAB_PATH=ROOT/"app/src/main/assets/vocabulary.json"
PHRASE_PATH=ROOT/"app/src/main/assets/vocabulary_phrase_translations.json"
EN={
"legally":"The company is legally required to keep these records for five years.",
"eclipse":"The museum scheduled a public event to observe the eclipse.",
"cuisine":"The hotel restaurant specializes in regional cuisine.",
"accused":"The accused appeared in court with an attorney.",
"invalid":"The system rejected the invalid access code.",
"prairie":"The research station monitors wildlife on the prairie.",
"warming":"The report examines how global warming may affect agriculture.",
"corresponding":"Please file each receipt with its corresponding expense report.",
"imposed":"The port imposed a temporary fee on oversized shipments.",
"royalty":"The author receives royalty payments from each sale.",
"warrant":"The police obtained a warrant to search the warehouse.",
"silicon":"The manufacturer uses silicon in its sensor components.",
"ceramic":"The laboratory tested a ceramic coating for the new equipment.",
"survivor":"The rescue team provided supplies to the storm survivor.",
"impaired":"The company provides accessible tools for employees with impaired vision.",
"tragedy":"The company donated to a relief fund after the tragedy.",
"manufacturing":"The region is known for manufacturing electronic parts.",
"engineering":"The engineering team redesigned the support structure.",
"assault":"The security guard reported an assault near the loading dock.",
"elegant":"The architect proposed an elegant solution to the space problem.",
"disciplinary":"The employee received a disciplinary warning for repeated lateness.",
"relocation":"The office relocation will take place during the holiday weekend.",
"respondent":"Each respondent completed the customer satisfaction survey.",
"bibliography":"The researcher added the sources to the report's bibliography.",
"excerpt":"The newsletter included an excerpt from the director's speech.",
"hypothetical":"The workshop uses a hypothetical customer complaint for practice.",
"assumed":"The budget was based on the assumed cost of materials.",
"demonstrated":"The technician demonstrated the new safety procedure.",
"torture":"The report condemns the use of torture in detention facilities.",
"integer":"The software accepts an integer between one and ten.",
"confirmation":"The airline sent confirmation of the reservation by email.",
"pending":"The payment remains pending until the bank completes its review.",
"occupational":"The clinic specializes in occupational health for factory workers.",
"personalized":"The website provides personalized recommendations to each customer.",
"induced":"The medication induced drowsiness, so the employee went home.",
"contamination":"The laboratory found contamination in one water sample.",
"endangered":"The conservation project protects endangered species near the resort.",
"insider":"The company investigated whether an insider had shared confidential data.",
"engaging":"The trainer used engaging activities to teach the new process.",
"triumph":"The successful launch was a triumph for the product team.",
"prescribed":"The physician prescribed rest after the workplace injury.",
"electoral":"The company closed its offices during the national electoral holiday.",
"derived":"The figures were derived from the latest quarterly report.",
"amended":"The parties signed the amended agreement yesterday.",
"outlook":"The chief economist presented a positive outlook for the industry.",
"granted":"The city granted permission to expand the distribution center.",
"engagement":"The campaign increased customer engagement on social media.",
"suspension":"The airline announced a temporary suspension of the route.",
"mapping":"The team is mapping delivery routes for the new service.",
"incorporated":"The revised plan incorporated feedback from branch managers.",
"motivated":"The bonus motivated staff to exceed their sales targets.",
"premier":"The hotel is a premier venue for international conferences.",
"gourmet":"The caterer prepared a gourmet dinner for the visiting executives.",
"groove":"The technician found a groove in the machine's drive belt.",
"pursuit":"The company supports employees in the pursuit of professional qualifications.",
"restricted":"Access to the archive is restricted to authorized staff.",
"counseling":"The employee assistance program offers confidential counseling.",
"calculated":"The accountant calculated the tax before issuing the invoice.",
"supreme":"The court is the country's supreme judicial authority.",
"tutorial":"The software includes a tutorial for new users.",
"learned":"The team learned valuable lessons from the delivery error.",
"inspection":"The warehouse passed its annual safety inspection.",
"revised":"The supplier sent a revised quotation this morning.",
"removal":"The removal of old equipment created more storage space.",
"circuit":"The electrician repaired the circuit in the meeting room.",
"seeking":"The company is seeking a candidate with logistics experience.",
"instant":"The app gives customers instant confirmation of payment.",
"calling":"The receptionist is calling the supplier about the delay.",
"enclosure":"The document includes an enclosure with technical specifications.",
"glucose":"The clinic checked the employee's glucose level.",
"vintage":"The restaurant decorated its dining room with vintage furniture.",
"binding":"The signed contract is binding on both parties.",
"nursing":"The hospital is hiring nursing staff for the new ward.",
"upgrade":"The company approved an upgrade to the computer network.",
"compilation":"The editor prepared a compilation of customer comments.",
"presently":"The director is presently meeting with the audit team.",
"trading":"The firm specializes in trading agricultural commodities.",
"setting":"The hotel provides a quiet setting for business meetings.",
"default":"The system uses English as the default language.",
"archive":"The assistant retrieved the invoice from the digital archive.",
"advancement":"The company offers training for career advancement.",
"restoration":"The restoration of the historic lobby took six months.",
"thorough":"The inspector conducted a thorough review of the equipment.",
"pledge":"The company made a pledge to reduce plastic packaging.",
"ballot":"Employees used a secret ballot to choose the committee chair.",
"denial":"The insurer sent a denial of the claim.",
"tactic":"The sales team changed its pricing tactic after the review.",
"refuge":"The emergency shelter provided refuge for displaced residents.",
"legendary":"The hotel is famous for its legendary customer service.",
"prefix":"Add the country prefix before dialing the international number.",
"declaration":"The importer filed a customs declaration for the shipment.",
"continental":"The airline serves several continental destinations.",
"hygiene":"The restaurant trains all staff in food hygiene.",
"patrol":"Security guards patrol the warehouse every night.",
"remedy":"The supplier offered a replacement as a remedy for the defect.",
"tenant":"The tenant reported a leak in the office ceiling.",
"activist":"The environmental activist spoke at the company forum.",
"varied":"The conference offers a varied program of workshops.",
"recruitment":"The recruitment team will visit three universities.",
"merchandise":"The store displays new merchandise near the entrance.",
"zoning":"The city approved the zoning change for the new hotel.",
"reservation":"Please confirm your reservation before traveling.",
"lender":"The lender requested updated financial statements.",
"longitude":"The navigation system calculates longitude and latitude.",
"insertion":"The insertion of the new card activated the machine.",
"romance":"The bookstore created a display of romance novels.",
"marketplace":"The online marketplace connects small sellers with customers.",
"insulation":"The building's insulation reduces heating costs.",
"residential":"The company is developing a residential area near the station.",
"exaggerate":"The advertisement must not exaggerate the product's benefits.",
"expire":"The membership will expire at the end of June.",
"feasible":"The engineer confirmed that the proposed expansion is feasible.",
"hinder":"Road construction may hinder deliveries this week.",
"immerse":"The training allows new employees to immerse themselves in the service process.",
"tuning":"The technician is tuning the machine before production begins.",
"allied":"The company works with allied organizations on disaster relief.",
"originate":"The error originated in the billing system.",
"proficiency":"Applicants must demonstrate proficiency in spreadsheet software.",
"provoke":"The sudden price increase provoked complaints from customers.",
"simultaneous":"The branches held simultaneous safety drills.",
"asthma":"The clinic prepared an emergency plan for employees with asthma.",
"endure":"The outdoor equipment is designed to endure severe weather.",
"abolish":"The company decided to abolish the outdated approval step.",
"superb":"The hotel received superb reviews from conference guests.",
"interactive":"The museum created an interactive exhibit for visitors.",
"adhere":"All contractors must adhere to the site's safety rules.",
"hazard":"The wet floor is a hazard for warehouse workers.",
"intake":"The clinic recorded the patient's daily water intake.",
"aptitude":"The applicant showed an aptitude for customer service.",
"ruling":"The court issued a ruling on the contract dispute.",
"arrogant":"The manager apologized for sounding arrogant during the meeting.",
"aspire":"Many employees aspire to become team leaders.",
"tribal":"The museum sells crafts made by a local tribal community.",
"parade":"The company sponsored a parade celebrating the city's anniversary.",
"tunnel":"The railway tunnel will be closed for maintenance.",
"escort":"A security officer escorted the visitor to the meeting room.",
"sacred":"The site is sacred to the local community and is carefully protected.",
"divine":"The hotel offers a view of the temple's divine artwork.",
"collaborate":"The two departments collaborate on customer research.",
"exotic":"The restaurant imports exotic spices for its seasonal menu.",
"conceal":"The cabinet conceals the network equipment from visitors.",
"confront":"The supervisor confronted the supplier about the missing items.",
"reprint":"The publisher will reprint the manual with the corrected diagram.",
"warrior":"The museum exhibit tells the story of an ancient warrior.",
"conversion":"The conversion to digital records reduced filing time.",
"solely":"The decision was not based solely on price.",
"recreation":"The resort offers recreation facilities for employees and guests.",
"funding":"The nonprofit received government funding for the training program.",
"warning":"The system issued a warning when the temperature rose.",
"deliberate":"The delay was deliberate so the team could check the figures.",
}
JA={
"legally":"会社は法的にこれらの記録を5年間保管する義務がある。","eclipse":"博物館は日食を観察する公開イベントを企画した。","cuisine":"ホテルのレストランは郷土料理を専門にしている。","accused":"被告人は弁護士とともに出廷した。","invalid":"システムは無効なアクセスコードを拒否した。","prairie":"研究所は草原の野生動物を監視している。","warming":"報告書は地球温暖化が農業に及ぼす影響を検討している。","corresponding":"各領収書を対応する経費報告書と一緒に保管してください。","imposed":"港は大型出荷品に一時料金を課した。","royalty":"著者は販売ごとに印税を受け取る。","warrant":"警察は倉庫を捜索する令状を取得した。","silicon":"メーカーはセンサー部品にシリコンを使用している。","ceramic":"研究所は新機器用のセラミックコーティングを試験した。","survivor":"救助隊は嵐の生存者に物資を提供した。","impaired":"会社は視力に障害のある従業員に利用しやすい道具を提供する。","tragedy":"会社は悲劇の後、救援基金に寄付した。","manufacturing":"その地域は電子部品の製造で知られている。","engineering":"工学チームは支持構造を設計し直した。","assault":"警備員は荷積み場近くの暴行を報告した。","elegant":"建築家は空間問題への洗練された解決策を提案した。","disciplinary":"従業員は度重なる遅刻で懲戒警告を受けた。","relocation":"オフィス移転は祝日の週末に行われる。","respondent":"回答者全員が顧客満足度調査に答えた。","bibliography":"研究者は報告書の参考文献一覧に資料を加えた。","excerpt":"ニュースレターには取締役のスピーチの抜粋が含まれていた。","hypothetical":"研修会では練習用に仮想の顧客苦情を使う。","assumed":"予算は材料費の想定額に基づいていた。","demonstrated":"技術者は新しい安全手順を実演した。","torture":"報告書は拘禁施設での拷問の使用を非難している。","integer":"ソフトウェアは1から10までの整数を受け付ける。","confirmation":"航空会社は予約確認をメールで送った。","pending":"銀行の審査が終わるまで支払いは保留される。","occupational":"診療所は工場作業員向けの労働衛生を専門にしている。","personalized":"ウェブサイトは各顧客に合わせた提案を表示する。","induced":"薬で眠気が出たため、従業員は帰宅した。","contamination":"研究所は水試料の1つに汚染を見つけた。","endangered":"保全計画はリゾート近くの絶滅危惧種を保護する。","insider":"会社は内部者が機密データを共有したか調査した。","engaging":"講師は魅力的な活動で新しい工程を教えた。","triumph":"発売の成功は製品チームにとって大きな勝利だった。","prescribed":"医師は職場で負傷した従業員に休養を処方した。","electoral":"会社は国政選挙の祝日に事務所を閉めた。","derived":"数値は最新の四半期報告書から導き出された。","amended":"両社は昨日、修正版の契約に署名した。","outlook":"主任エコノミストは業界の明るい見通しを示した。","granted":"市は配送センター拡張の許可を与えた。","engagement":"キャンペーンでソーシャルメディア上の顧客参加が増えた。","suspension":"航空会社は路線の一時運休を発表した。","mapping":"チームは新サービスの配送ルートを地図化している。","incorporated":"改訂版計画には支店長からの意見が取り入れられた。","motivated":"賞与が職員の売上目標超過を促した。","premier":"そのホテルは国際会議の一流会場だ。","gourmet":"ケータリング業者は来訪幹部に高級ディナーを用意した。","groove":"技術者は機械の駆動ベルトに溝を見つけた。","pursuit":"会社は従業員の専門資格取得を支援している。","restricted":"資料室への立ち入りは許可職員に制限されている。","counseling":"従業員支援制度は秘密厳守で相談に応じる。","calculated":"経理担当者は請求書発行前に税額を計算した。","supreme":"その裁判所は国の最高司法機関だ。","tutorial":"ソフトウェアには新規利用者向けのチュートリアルがある。","learned":"チームは配送ミスから貴重な教訓を得た。","inspection":"倉庫は年次安全検査に合格した。","revised":"仕入先は今朝、改訂版の見積書を送った。","removal":"古い機器を撤去して保管スペースが増えた。","circuit":"電気技師は会議室の回路を修理した。","seeking":"会社は物流経験のある候補者を探している。","instant":"アプリは支払いを即時確認してくれる。","calling":"受付係は遅延について仕入先に電話している。","enclosure":"書類には技術仕様を記した同封資料がある。","glucose":"診療所は従業員の血糖値を確認した。","vintage":"レストランは食堂をビンテージ家具で飾った。","binding":"署名済み契約は両当事者を拘束する。","nursing":"病院は新病棟の看護職員を募集している。","upgrade":"会社はコンピューターネットワークの更新を承認した。","compilation":"編集者は顧客の意見をまとめた資料を作成した。","presently":"取締役は現在、監査チームと会議中だ。","trading":"その会社は農産物の取引を専門にしている。","setting":"ホテルはビジネス会議に静かな環境を提供する。","default":"システムの初期言語は英語だ。","archive":"アシスタントは電子保管庫から請求書を取り出した。","advancement":"会社は昇進のための研修を提供している。","restoration":"歴史的なロビーの修復に6か月かかった。","thorough":"検査員は機器を徹底的に確認した。","pledge":"会社はプラスチック包装を減らすと誓約した。","ballot":"従業員は秘密投票で委員長を選んだ。","denial":"保険会社は請求の拒否通知を送った。","tactic":"営業チームは検討後、価格戦術を変更した。","refuge":"緊急避難所は住む場所を失った住民を受け入れた。","legendary":"そのホテルは伝説的な顧客サービスで有名だ。","prefix":"国際電話をかける前に国番号を加えてください。","declaration":"輸入業者は出荷品の税関申告書を提出した。","continental":"航空会社は複数の大陸内都市へ就航している。","hygiene":"レストランは全職員に食品衛生研修を行う。","patrol":"警備員は毎晩倉庫を巡回する。","remedy":"仕入先は欠陥への救済策として交換品を提供した。","tenant":"借主はオフィスの天井からの水漏れを報告した。","activist":"環境活動家は会社のフォーラムで講演した。","varied":"会議では多様な研修会が用意されている。","recruitment":"採用チームは3つの大学を訪問する。","merchandise":"店は入口付近に新商品を展示している。","zoning":"市は新ホテルのための用途地域変更を承認した。","reservation":"旅行前に予約を確認してください。","lender":"貸し手は最新の財務諸表を求めた。","longitude":"ナビゲーションシステムは経度と緯度を計算する。","insertion":"新しいカードを差し込むと機械が起動した。","romance":"書店は恋愛小説の特設売り場を作った。","marketplace":"オンライン市場は小規模販売者と顧客をつなぐ。","insulation":"建物の断熱材が暖房費を抑えている。","residential":"会社は駅の近くに住宅地を開発している。","exaggerate":"広告は製品の利点を誇張してはならない。","expire":"会員資格は6月末に期限切れとなる。","feasible":"技術者は提案された拡張が実行可能だと確認した。","hinder":"道路工事で今週の配送が妨げられる可能性がある。","immerse":"研修では新入社員がサービス工程に深く取り組める。","tuning":"技術者は生産開始前に機械を調整している。","allied":"会社は災害救援で関係団体と協力している。","originate":"エラーは請求システムで発生した。","proficiency":"応募者は表計算ソフトの熟練度を示さなければならない。","provoke":"突然の値上げが顧客の苦情を引き起こした。","simultaneous":"各支店は同時に安全訓練を行った。","asthma":"診療所は喘息のある従業員向けの緊急計画を用意した。","endure":"屋外機器は厳しい天候に耐えるよう設計されている。","abolish":"会社は古い承認手順を廃止することに決めた。","superb":"ホテルは会議参加者から素晴らしい評価を受けた。","interactive":"博物館は来訪者向けに体験型展示を作った。","adhere":"請負業者は全員、現場の安全規則を守らなければならない。","hazard":"濡れた床は倉庫作業員にとって危険だ。","intake":"診療所は患者の1日の水分摂取量を記録した。","aptitude":"応募者は顧客サービスの適性を示した。","ruling":"裁判所は契約紛争について判決を出した。","arrogant":"マネージャーは会議中、傲慢に聞こえたことを謝った。","aspire":"多くの従業員がチームリーダーを目指している。","tribal":"博物館は地元部族の工芸品を販売している。","parade":"会社は市の記念日を祝うパレードを後援した。","tunnel":"鉄道トンネルは保守のため閉鎖される。","escort":"警備員は来訪者を会議室まで案内した。","sacred":"その場所は地域にとって神聖で、慎重に保護されている。","divine":"ホテルから寺院の神聖な芸術作品を眺められる。","collaborate":"2部署は顧客調査で協力している。","exotic":"レストランは季節メニュー用に珍しい香辛料を輸入する。","conceal":"戸棚は来訪者からネットワーク機器を隠している。","confront":"監督者は不足品について仕入先を問いただした。","reprint":"出版社は図を訂正したマニュアルを再版する。","warrior":"博物館の展示は古代の戦士の物語を伝える。","conversion":"電子記録への変換でファイル作業時間が減った。","solely":"決定は価格だけに基づくものではなかった。","recreation":"リゾートは従業員と宿泊客に余暇施設を提供する。","funding":"非営利団体は研修計画の政府資金を受けた。","warning":"温度が上昇するとシステムが警告を出した。","deliberate":"チームが数値を確認できるよう遅延は意図的に行われた。",
}
def main() -> None:
    vocabulary=json.loads(VOCAB_PATH.read_text(encoding="utf-8")); phrase_root=json.loads(PHRASE_PATH.read_text(encoding="utf-8")); translations=phrase_root.setdefault("translations",{})
    rows=[x for x in vocabulary if int(x.get("level",0))==3][1200:1350]; expected={str(x["word"]).casefold() for x in rows}; assert set(EN)==expected and set(JA)==expected
    changed=0
    for item in rows:
        word=str(item["word"]).casefold(); source=EN[word]; item["example"]=source; ex=translations.setdefault(f"builtin:{item['id']}",{}).setdefault("example",{})
        for field,value in (("source",source),("en",source),("ja",JA[word])):
            if ex.get(field)!=value: ex[field]=value; changed+=1
    VOCAB_PATH.write_text(json.dumps(vocabulary,ensure_ascii=False,indent=1)+"\n",encoding="utf-8"); PHRASE_PATH.write_text(json.dumps(phrase_root,ensure_ascii=False,indent=1)+"\n",encoding="utf-8")
    print(f"reviewed 700+ English/Japanese examples batch 3c: {len(rows)} terms, {changed} fields")
if __name__=="__main__": main()
