#!/usr/bin/env python3
"""Review 700+ examples 401-600 in English and Japanese."""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
VOCAB_PATH=ROOT/"app/src/main/assets/vocabulary.json"
PHRASE_PATH=ROOT/"app/src/main/assets/vocabulary_phrase_translations.json"
EN={
"uncle":"Her uncle manages the company's regional warehouse.","rice":"The restaurant ordered rice for the conference lunch.","slope":"The construction crew secured the slope beside the new road.","happiness":"The manager believes employee happiness improves customer service.","verb":"The editor checked how the verb was used in the manual.","reckon":"The finance team reckons the repair will cost less than the replacement.","silly":"It would be silly to ignore the supplier's safety warning.","transportation":"The logistics manager reviewed transportation options before the client meeting.","universe":"The museum invited an expert to speak about the universe.","horrible":"The storm caused horrible damage to the warehouse roof.","sheep":"The farm supplies wool from its sheep to a local manufacturer.","lover":"The hotel manager is a lover of traditional local food.","rat":"The pest-control team removed a rat from the storage area.","portrait":"The company displayed a portrait of its founder in the lobby.","innocent":"The audit confirmed that the employee was innocent of the error.","substitute":"The supervisor arranged a substitute for the absent technician.","reasonably":"The supplier priced the replacement parts reasonably.","tent":"The rescue team set up a tent near the construction site.","stranger":"The receptionist asked a stranger to show identification.","shade":"The outdoor seating area provides shade for visiting clients.","leap":"Online orders took a leap after the new campaign began.","snap":"The technician heard a snap when the old cable broke.","leather":"The company ordered leather chairs for the executive office.","swear":"The witness swore that the delivery record was accurate.","shore":"The resort hired a company to protect the shore from erosion.","monthly":"The finance team prepares a monthly expense report.","stir":"The announcement stirred concern among the suppliers.","sigh":"The manager sighed with relief after the shipment arrived.","pregnancy":"The company provides leave and support during pregnancy.","slice":"The caterer served each guest a slice of fresh bread.","wander":"Visitors may wander through the factory tour area after signing in.","empire":"The founder built a business empire through careful expansion.","attendance":"Attendance at the mandatory safety meeting is recorded.","pale":"The employee looked pale and visited the workplace clinic.","stain":"The cleaner removed a stain from the conference-room carpet.","tongue":"The training app supports several languages and helps users practice each tongue.","website":"The company updated its website with the new delivery information.","unite":"The campaign aims to unite employees around a common goal.","wipe":"Please wipe the counter after preparing the samples.","weird":"The technician noticed a weird sound from the new machine.","royal":"The hotel prepared a royal suite for the visiting delegation.","mayor":"The mayor attended the opening of the new distribution center.","tournament":"The company sponsored a local tennis tournament.","registration":"Online registration for the training course closes Friday.","listener":"The speaker asked each listener to complete a short survey.","ugly":"The damaged sign looked ugly outside the newly renovated store.","faithfully":"Please follow the safety instructions faithfully.","holder":"The card holder must show identification at the entrance.","solar":"The company installed solar panels on the warehouse roof.","grin":"The customer gave a grin after receiving the replacement product.","rose":"The hotel placed a rose on each table for the anniversary dinner.","noun":"The editor checked whether the noun was clear in the customer manual.","fortunate":"We were fortunate that the shipment arrived before the storm.","lazy":"A lazy approval process can delay an urgent order.","hello":"The receptionist said hello to each visitor.","hunger":"The team's hunger for improvement led to a new training plan.","insure":"The company will insure the equipment during overseas transport.","ashamed":"The employee felt ashamed after sending the confidential file to the wrong client.","found":"The founders found the company in 2010.","blog":"The marketing team published a blog about the new service.","thirst":"The sales team's thirst for growth encouraged careful planning.","acid":"The laboratory stores the acid in a marked safety cabinet.","actively":"The company actively seeks feedback from customers.","afterward":"The manager sent a summary afterward.","agriculture":"The company supplies software to businesses in agriculture.","algebra":"The analyst used algebra to check the pricing formula.","alien":"The company hired an alien resident with the required work authorization.","aluminum":"The manufacturer uses aluminum for lightweight equipment frames.","amongst":"Amongst the proposals, the manager selected the one with the clearest budget.","ancestor":"The museum traced the ancestor of the company's original logo.","anti":"The packaging includes an anti-theft feature.","antibiotic":"The clinic stores antibiotic medicine according to safety rules.","appendix":"The contract appendix lists the technical specifications.","applause":"The team received applause after presenting the successful results.","architect":"The architect redesigned the office entrance.","artistic":"The designer made artistic choices that fit the company's brand.","artwork":"The company displayed local artwork in the reception area.","athletic":"The hotel provides athletic facilities for conference guests.","atom":"The engineer explained how an atom behaves in the sensor material.","audio":"The technician tested the audio before the online presentation.","authority":"The local authority approved the warehouse expansion.","availability":"Please confirm the availability of the meeting room.","axis":"The engineer checked the axis of the rotating component.","bacteria":"The laboratory tests the product for harmful bacteria.","basin":"The maintenance worker repaired the basin in the staff kitchen.","biologist":"The company hired a biologist to review the environmental impact.","biology":"The research team uses biology to develop safer agricultural products.","bonus":"The company paid a bonus to employees who exceeded their targets.","bound":"The shipment is bound for the overseas branch.","bracket":"The estimate includes the cost in a separate bracket.","bullet":"The manager summarized the action items in bullet points.","bundle":"The supplier offered a bundle of installation and support services.","calculation":"The accountant checked the calculation before issuing the invoice.","cattle":"The farm uses tracking tags to monitor its cattle.","chemistry":"The manufacturer uses chemistry to improve the product formula.","chunk":"The technician found a chunk of damaged material in the shipment.","composer":"The hotel hired a composer for its anniversary video.","connector":"The technician replaced the damaged connector.","conscious":"The company is conscious of its responsibility to protect customer data.","consent":"The clinic obtained the employee's consent before the medical test.","correction":"The editor made a correction to the customer manual.","crystal":"The laboratory examined the crystal before approving the material.","cylinder":"The technician replaced the cylinder in the production machine.","damp":"The warehouse floor became damp after the pipe leaked.","definite":"The client requested a definite delivery date.","dense":"The dense report was shortened for the executive meeting.","diagram":"The manual includes a diagram of the installation process.","diameter":"The engineer measured the diameter of the replacement pipe.","disability":"The company provides workplace support for employees with a disability.","disadvantage":"The report identifies the disadvantage of the older system.","distribution":"The distribution center sends products across the region.","dose":"The clinic recorded the correct dose in the patient's file.","dye":"The manufacturer used a safe dye for the product fabric.","elastic":"The engineer modeled the bridge as an elastic structure.","electron":"The engineer explained how an electron moves through the sensor.","elementary":"The manual explains the process in elementary terms.","emperor":"The museum displayed a portrait of an emperor during the history exhibition.","enormously":"The project benefited enormously from the additional investment.","forum":"The company hosted a forum on workplace safety.","fossil":"The museum displayed a fossil found near the construction site.","fracture":"The clinic treated the employee's fracture after the workplace accident.","freely":"Employees may freely share suggestions through the internal portal.","friction":"The mediator reduced friction between the two departments.","fringe":"The designer used a fringe detail on the promotional display.","fundamentally":"The revised process is fundamentally different from the old one.","fungus":"The laboratory checked the material for fungus before storage.","fusion":"The merger created a fusion of two complementary business cultures.","gauge":"The manager will gauge customer interest before expanding the service.","generalize":"The analyst should not generalize from one customer complaint.","grammatical":"The editor corrected grammatical errors in the report.","grasp":"The new employee quickly grasped the purpose of the procedure.","gravity":"The engineer explained the gravity of the safety issue.","grid":"The utility company upgraded the electrical grid near the factory.","gross":"The invoice shows gross sales before expenses.","gut":"The manager trusted her gut when selecting the supplier.","habitat":"The construction plan protects the habitat near the facility.","halfway":"The project is halfway to completion.","handout":"The trainer distributed a handout about the new procedure.","harvest":"The company buys its harvest from local farms.","hawk":"The resort protects a hawk that nests near the property.","headquarter":"The company will headquarter its new division in Osaka.","hedge":"The finance team used a hedge to limit currency risk.","hierarchy":"The manager explained the reporting hierarchy to the new employee.","hip":"The clinic treated an employee who injured a hip at work.","historically":"The port has historically supported regional trade.","homework":"The online course gives employees homework after each session.","horizon":"The new service expands the company's business horizon.","horizontal":"The engineer installed a horizontal support beam.","hormone":"The laboratory recorded hormone levels during the product study.","hydrogen":"The company is researching hydrogen as a cleaner energy source.","identical":"The two invoices are identical except for the dates.","identification":"Visitors must show identification at the reception desk.","illusion":"The advertisement creates the illusion of instant results.","importantly":"Importantly, the contract protects customer data.","impulse":"The buyer avoided an impulse purchase by reviewing the budget.","incline":"Customers tend to incline toward the simpler payment option.","incredible":"The support team achieved an incredible response time.","incredibly":"The new system is incredibly easy to use.","independently":"Each branch operates independently but follows the same policy.","indicator":"Repeat orders are an indicator of customer satisfaction.","indirect":"The policy has an indirect effect on delivery costs.","individually":"Please label each package individually.","induce":"The discount may induce customers to renew their contracts.","infect":"The virus can infect devices that lack the security update.","infectious":"The clinic follows strict rules for infectious materials.","inferior":"The test showed that the replacement material was inferior.","infinite":"The software cannot store an infinite number of records.","influential":"The influential customer recommended the service to several partners.","informal":"The manager held an informal meeting with the team.","inject":"The technician will inject the solution into the sealed unit.","injection":"The clinic recorded the employee's injection in the medical file.","insect":"The warehouse team removed an insect from the storage area.","insert":"Insert the card before entering the security code.","instinct":"The manager trusted her instinct when responding to the complaint.","integration":"The integration of the two systems reduced duplicate work.","intensity":"The engineer measured the intensity of the signal.","intensive":"The company provided intensive training before the system launch.","interact":"The app allows customers to interact with support staff.","interestingly":"Interestingly, repeat customers preferred the shorter form.","interface":"The new interface makes the order process easier.","interfere":"Construction work may interfere with deliveries.","intermediate":"The course is designed for intermediate users.","interrupt":"Please do not interrupt the client during the briefing.","interval":"The system sends updates at a regular interval.","intervene":"The manager had to intervene when the negotiation stalled.","interviewer":"The interviewer asked about the applicant's customer-service experience.","invade":"The software blocks attempts to invade the company's network.","invasion":"The security team detected an attempted invasion of the network.","ion":"The engineer measured ion levels in the battery material.","irrelevant":"Please remove irrelevant information from the proposal.","irrigation":"The farm installed irrigation equipment to protect the crop.","jazz":"The hotel played jazz during the networking dinner.","junior":"A junior analyst prepared the first draft of the report.","justification":"The manager requested justification for the additional expense.","kidney":"The clinic helped an employee arrange kidney treatment.","kilometer":"The warehouse is five kilometers from the port.","lab":"The lab completed the product test before shipment.","layout":"The architect changed the office layout to create more meeting space.",
}

EN.update({
    "impact":"The new policy had a significant impact on delivery costs.",
    "inclusion":"The inclusion of delivery insurance increased the order total.",
})

JA={
"uncle":"彼女のおじは会社の地域倉庫を管理している。",
"rice":"レストランは会議の昼食用に米を注文した。",
"slope":"建設作業員は新しい道路脇の斜面を補強した。",
"happiness":"マネージャーは従業員の幸福が顧客サービスを改善すると考えている。",
"verb":"編集者はマニュアルでその動詞が正しく使われているか確認した。",
"reckon":"財務チームは修理費が交換費より安いと見積もっている。",
"silly":"仕入先の安全警告を無視するのは愚かなことだ。",
"transportation":"物流マネージャーは顧客会議前に輸送手段を確認した。",
"universe":"博物館は宇宙について専門家を招いて講演してもらった。",
"horrible":"嵐は倉庫の屋根にひどい損害を与えた。",
"sheep":"農場は羊毛を地元メーカーに供給している。",
"lover":"ホテルのマネージャーは伝統的な郷土料理を愛好している。",
"rat":"害虫駆除チームは保管区域からネズミを取り除いた。",
"portrait":"会社はロビーに創業者の肖像画を飾った。",
"innocent":"監査でその従業員に誤りの責任がないと確認された。",
"substitute":"上司は欠勤した技術者の代役を手配した。",
"reasonably":"仕入先は交換部品を妥当な価格で提供した。",
"tent":"救助チームは建設現場の近くにテントを設置した。",
"stranger":"受付係は見知らぬ人に身分証の提示を求めた。",
"shade":"屋外席には来訪客用の日陰がある。",
"leap":"新キャンペーン開始後、オンライン注文が急増した。",
"snap":"古いケーブルが切れたとき、パキッという音がした。",
"leather":"会社は役員室用に革張りの椅子を注文した。",
"swear":"目撃者は配送記録が正確だと誓った。",
"shore":"リゾートは海岸を浸食から守る会社を雇った。",
"monthly":"財務チームは毎月、経費報告書を作成する。",
"stir":"発表が仕入先の間に懸念を引き起こした。",
"sigh":"出荷品が届くとマネージャーは安堵のため息をついた。",
"pregnancy":"会社は妊娠中に休暇と支援を提供している。",
"slice":"ケータリング担当者は来客に焼きたてのパンを一切れずつ出した。",
"wander":"来訪者は受付で記帳した後、工場見学エリアを歩き回れる。",
"empire":"創業者は慎重な拡張で企業帝国を築いた。",
"attendance":"必須安全会議への出席を記録する。",
"pale":"従業員は顔色が悪く、職場の診療所を訪れた。",
"stain":"清掃員は会議室のじゅうたんの染みを取った。",
"tongue":"研修アプリは複数言語に対応している。",
"website":"会社は新しい配送情報をウェブサイトに掲載した。",
"unite":"キャンペーンは共通の目標を中心に従業員を団結させる。",
"wipe":"サンプルを準備した後、カウンターを拭いてください。",
"weird":"技術者は新しい機械から奇妙な音がすることに気づいた。",
"royal":"ホテルは来訪団のためにロイヤルスイートを準備した。",
"mayor":"市長は新しい配送センターの開業式に出席した。",
"tournament":"会社は地元のテニス大会を後援した。",
"registration":"研修コースのオンライン登録は金曜日に締め切る。",
"listener":"講演者は各聞き手に短い調査への回答を求めた。",
"ugly":"破損した看板は改装した店の外で見栄えが悪かった。",
"faithfully":"安全指示に忠実に従ってください。",
"holder":"カード所持者は入口で身分証を提示しなければならない。",
"solar":"会社は倉庫の屋根に太陽光パネルを設置した。",
"grin":"交換品を受け取った顧客はにっこり笑った。",
"rose":"ホテルは記念ディナーの各テーブルにバラを置いた。",
"noun":"編集者は顧客向けマニュアルの名詞が明確か確認した。",
"fortunate":"嵐の前に出荷品が届いたのは幸運だった。",
"lazy":"承認手続きが遅いと緊急注文が遅れる可能性がある。",
"hello":"受付係は来訪者一人ひとりに挨拶した。",
"hunger":"営業チームの成長への強い意欲が新しい研修計画につながった。",
"insure":"会社は海外輸送中の機器に保険をかける。",
"ashamed":"従業員は機密ファイルを誤った顧客に送ってしまい恥じた。",
"found":"創業者たちは2010年に会社を設立した。",
"blog":"マーケティングチームは新サービスについてブログを書いた。",
"thirst":"営業チームの成長への渇望が慎重な計画を促した。",
"acid":"研究所は酸を安全棚に保管している。",
"actively":"会社は顧客から積極的に意見を集めている。",
"afterward":"マネージャーはその後、要約を送った。",
"agriculture":"会社は農業分野の企業にソフトウェアを提供している。",
"algebra":"アナリストは代数を使って価格計算式を確認した。",
"alien":"会社は必要な就労許可を持つ外国人を雇った。",
"aluminum":"メーカーは軽量な機器フレームにアルミニウムを使っている。",
"amongst":"提案の中から、マネージャーは予算が最も明確なものを選んだ。",
"ancestor":"博物館は会社の元のロゴの由来をたどった。",
"anti":"包装には盗難防止機能がある。",
"antibiotic":"診療所は抗生物質を安全規則に従って保管している。",
"appendix":"契約書の付録には技術仕様が記載されている。",
"applause":"成功結果を発表した後、チームは拍手を受けた。",
"architect":"建築家はオフィス入口を設計し直した。",
"artistic":"デザイナーは会社のブランドに合う芸術的な選択をした。",
"artwork":"会社は受付エリアに地元の芸術作品を展示した。",
"athletic":"ホテルは会議参加者向けにスポーツ施設を提供している。",
"atom":"技術者はセンサー素材の原子の動きを説明した。",
"audio":"技術者はオンライン発表前に音声をテストした。",
"authority":"地方当局は倉庫の拡張を承認した。",
"availability":"会議室が利用できるか確認してください。",
"axis":"技術者は回転部品の軸を確認した。",
"bacteria":"研究所は製品に有害な細菌がないか検査する。",
"basin":"保守担当者は従業員用キッチンの洗面台を修理した。",
"biologist":"会社は環境への影響を確認するため生物学者を雇った。",
"biology":"研究チームはより安全な農産物の開発に生物学を使う。",
"bonus":"会社は目標を上回った従業員に賞与を支給した。",
"bound":"出荷品は海外支店行きだ。",
"bracket":"見積書には費用が別の区分で記載されている。",
"bullet":"マネージャーは行動項目を箇条書きでまとめた。",
"bundle":"仕入先は設置と支援サービスのセットを提供した。",
"calculation":"経理担当者は請求書を発行する前に計算を確認した。",
"cattle":"農場は追跡タグで牛を管理している。",
"chemistry":"メーカーは製品配合の改善に化学を利用している。",
"chunk":"技術者は出荷品の中に破損した素材の塊を見つけた。",
"composer":"ホテルは記念動画のため作曲家を雇った。",
"connector":"技術者は破損したコネクターを交換した。",
"conscious":"会社は顧客データを守る責任を自覚している。",
"consent":"診療所は医療検査の前に従業員の同意を得た。",
"correction":"編集者は報告書を訂正した。",
"crystal":"研究所は素材を承認する前に結晶を検査した。",
"cylinder":"技術者は生産機械のシリンダーを交換した。",
"damp":"パイプが漏れた後、倉庫の床が湿った。",
"definite":"顧客は確定した納品日を求めた。",
"dense":"密度の高い報告書を役員会議向けに短くした。",
"diagram":"マニュアルには設置工程の図がある。",
"diameter":"技術者は交換用パイプの直径を測定した。",
"disability":"会社は障害のある従業員に職場支援を提供している。",
"disadvantage":"報告書は旧システムの欠点を特定している。",
"distribution":"配送センターは地域全体へ製品を発送する。",
"dose":"診療所は患者の記録に正しい投薬量を記載した。",
"dye":"メーカーは製品の布地に安全な染料を使った。",
"elastic":"技術者は橋を適度な負荷で元の形に戻る弾性構造としてモデル化した。",
"electron":"技術者は電子がセンサー内を移動する仕組みを説明した。",
"elementary":"マニュアルは工程を基礎的な言葉で説明している。",
"emperor":"博物館は歴史展示で皇帝の肖像画を公開した。",
"enormously":"追加投資でプロジェクトは大きな恩恵を受けた。",
"forum":"会社は職場の安全について討論会を開催した。",
"fossil":"博物館は建設現場の近くで見つかった化石を展示した。",
"fracture":"診療所は職場事故で骨折した従業員を治療した。",
"freely":"従業員は社内ポータルで自由に提案を共有できる。",
"friction":"調停者は2部署間の不和を和らげた。",
"fringe":"デザイナーは宣伝展示に房飾りの細部を使った。",
"fundamentally":"改訂版の工程は以前のものと根本的に異なる。",
"fungus":"研究所は保管前に素材に菌類がないか確認した。",
"fusion":"合併により、補完し合う2つの企業文化が融合した。",
"gauge":"マネージャーはサービス拡大前に顧客の関心を測る。",
"generalize":"アナリストは1件の苦情から一般化すべきではない。",
"grammatical":"編集者は報告書の文法上の誤りを直した。",
"grasp":"新入社員は手順の目的をすぐに理解した。",
"gravity":"技術者は安全問題の重大さを説明した。",
"grid":"電力会社は工場付近の電力網を改修した。",
"gross":"請求書には費用控除前の総売上が表示されている。",
"gut":"マネージャーは仕入先を選ぶ際に直感を信じた。",
"habitat":"建設計画は施設周辺の生息地を保護している。",
"halfway":"プロジェクトは完了まで半分の地点に来ている。",
"handout":"研修担当者は新しい手順の配布資料を配った。",
"harvest":"会社は地域の農家から収穫物を仕入れている。",
"hawk":"リゾートは敷地内に巣を作るタカを保護している。",
"headquarter":"会社は新部門の本社を大阪に置く。",
"hedge":"財務チームは為替リスクを抑えるためヘッジを使った。",
"hierarchy":"マネージャーは新入社員に報告の階層を説明した。",
"hip":"診療所は職場で腰を痛めた従業員を治療した。",
"historically":"その港は歴史的に地域貿易を支えてきた。",
"homework":"オンライン講座は各回の後に従業員へ課題を出す。",
"horizon":"新サービスは会社の事業の視野を広げる。",
"horizontal":"技術者は水平な支持梁を取り付けた。",
"hormone":"研究所は製品研究中のホルモン値を記録した。",
"hydrogen":"会社はよりクリーンなエネルギー源として水素を研究している。",
"identical":"2つの請求書は日付以外まったく同じだ。",
"identification":"来訪者は受付で身分証を提示しなければならない。",
"illusion":"広告は即効性があるような錯覚を作り出している。",
"importantly":"重要なことに、契約は顧客データを保護している。",
"impulse":"買い手は予算を確認して衝動買いを避けた。",
"incline":"顧客はより簡単な決済方法を選ぶ傾向がある。",
"incredible":"サポートチームは驚くほど短い対応時間を達成した。",
"incredibly":"新しいシステムは信じられないほど使いやすい。",
"independently":"各支店は独立して運営するが、同じ方針に従う。",
"indicator":"リピート注文は顧客満足度の指標だ。",
"indirect":"その方針は配送費に間接的な影響を与える。",
"individually":"各荷物に個別にラベルを貼ってください。",
"induce":"割引は顧客に契約更新を促す可能性がある。",
"infect":"更新していない端末はウイルスに感染する可能性がある。",
"infectious":"診療所は感染性物質について厳格な規則に従う。",
"inferior":"試験で交換素材の品質が劣ることが分かった。",
"infinite":"ソフトウェアは無限の記録を保存できない。",
"influential":"影響力のある顧客が複数の取引先にサービスを勧めた。",
"informal":"マネージャーはチームと非公式の会議を開いた。",
"inject":"技術者は密閉装置に溶液を注入する。",
"injection":"診療所は従業員の注射を医療記録に記載した。",
"insect":"倉庫チームは保管区域から昆虫を取り除いた。",
"insert":"セキュリティコードを入力する前にカードを差し込んでください。",
"instinct":"マネージャーは苦情への対応で直感を信じた。",
"integration":"2つのシステムを統合したことで重複作業が減った。",
"intensity":"技術者は信号の強度を測定した。",
"intensive":"会社はシステム導入前に集中的な研修を行った。",
"interact":"アプリで顧客がサポート担当者とやり取りできる。",
"interestingly":"興味深いことに、リピーターは短いフォームを好んだ。",
"interface":"新しいインターフェースで注文手続きが簡単になった。",
"interfere":"工事が配送の妨げになる可能性がある。",
"intermediate":"この講座は中級者向けに設計されている。",
"interrupt":"説明中に顧客の話を遮らないでください。",
"interval":"システムは一定間隔で更新を送る。",
"intervene":"交渉が行き詰まったため、マネージャーが介入した。",
"interviewer":"面接官は応募者の顧客サービス経験について尋ねた。",
"invade":"ソフトウェアは会社のネットワークへの侵入を防ぐ。",
"invasion":"警備チームはネットワークへの侵入未遂を検知した。",
"ion":"技術者は電池素材のイオン濃度を測定した。",
"irrelevant":"提案書から関係のない情報を削除してください。",
"irrigation":"農場は作物を守るため灌漑設備を設置した。",
"jazz":"ホテルは交流ディナーでジャズを流した。",
"junior":"若手アナリストが報告書の初稿を作成した。",
"justification":"マネージャーは追加費用の正当な理由を求めた。",
"kidney":"診療所は従業員の腎臓治療の手配を支援した。",
"kilometer":"倉庫は港から5キロメートル離れている。",
"lab":"研究室は出荷前に製品試験を完了した。",
"layout":"建築家は会議スペースを増やすためオフィスの配置を変更した。",
}

JA.update({
    "impact":"新しい方針は配送費に大きな影響を与えた。",
    "inclusion":"配送保険を含めたことで注文総額が増えた。",
})

def main():
    vocabulary=json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root=json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations=phrase_root.setdefault("translations", {})
    target=[item for item in vocabulary if int(item.get("level", 0)) == 3][400:600]
    expected={str(item["word"]).casefold() for item in target}
    if set(EN)!=expected or set(JA)!=expected:
        raise ValueError(f"700+ 401-600 key mismatch: expected={len(expected)} en={len(EN)} ja={len(JA)}")
    changed=0
    for item in target:
        word=str(item["word"]).casefold()
        source=EN[word]
        item["example"]=source
        example=translations.setdefault(f"builtin:{item['id']}",{}).setdefault("example",{})
        for field,value in (("source",source),("en",source),("ja",JA[word])):
            if example.get(field)!=value:
                example[field]=value
                changed+=1
    VOCAB_PATH.write_text(json.dumps(vocabulary,ensure_ascii=False,indent=1)+"\n",encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root,ensure_ascii=False,indent=1)+"\n",encoding="utf-8")
    print(f"reviewed 700+ English/Japanese examples batch 2b: {len(target)} terms, {changed} fields")

if __name__=="__main__":
    main()
