#!/usr/bin/env python3
"""Review 700+ examples 301-600 in English and Japanese."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"

EN = {
    "rid": "The team will rid the warehouse of obsolete stock before the audit.",
    "ruin": "A careless change could ruin the customer's delivery schedule.",
    "motor": "The technician replaced the motor in the conveyor system.",
    "permission": "Please obtain permission before entering the restricted area.",
    "valley": "The company built a relay station in the valley.",
    "mad": "The client was mad about the unexplained charge.",
    "visible": "The safety label must remain visible on every package.",
    "violent": "The security plan covers the risk of violent incidents.",
    "slave": "The museum explains how slavery affected the region's trade history.",
    "journal": "The researcher recorded the inspection results in the project journal.",
    "measurement": "The engineer checked the measurement before approving the design.",
    "random": "The system assigns each audit a random reference number.",
    "successfully": "The engineering team successfully tested the new equipment.",
    "illustration": "The manual includes an illustration of the installation process.",
    "rail": "The shipment will leave by rail from the northern depot.",
    "laboratory": "The company upgraded its laboratory to support product testing.",
    "passion": "Her passion for customer service is clear in every call.",
    "roughly": "The repair will take roughly three hours.",
    "skirt": "The designer selected a dark skirt for the formal event.",
    "march": "The new policy will take effect in March.",
    "weakness": "The audit identified a weakness in the approval process.",
    "salt": "The restaurant reduced the salt in its business lunch menu.",
    "opera": "The hotel arranged opera tickets for the visiting executives.",
    "praise": "The director praised the team for meeting the deadline.",
    "silent": "Please keep your phone silent during the presentation.",
    "pump": "The maintenance team repaired the water pump.",
    "publisher": "The publisher released the company's annual report.",
    "weigh": "The buyer will weigh the costs before signing the contract.",
    "profession": "The company offers training for people entering the accounting profession.",
    "injure": "The safety procedure helps prevent workers from getting injured.",
    "remote": "The company supports employees who work at remote sites.",
    "orange": "The warehouse uses orange labels for priority shipments.",
    "twist": "The manager added a practical twist to the standard training exercise.",
    "imagination": "The design team used imagination to create a more user-friendly package.",
    "throat": "The clinic advised the employee to rest after reporting a sore throat.",
    "joy": "The team felt joy when the client approved the proposal.",
    "pregnant": "The company provides flexible schedules for pregnant employees.",
    "reliable": "The supplier has a reliable record of on-time delivery.",
    "poet": "The company invited a poet to read at the charity event.",
    "pile": "Please move the pile of documents to the archive room.",
    "pig": "The farm supplies pork to the hotel's restaurant.",
    "mixture": "The technician prepared a mixture for cleaning the equipment.",
    "poetry": "The bookstore added poetry books to its cultural event display.",
    "sake": "For the sake of safety, keep the loading area clear.",
    "shelf": "The warehouse added a shelf for small replacement parts.",
    "tail": "The assistant checked the tail number of the aircraft.",
    "possession": "Employees must not bring alcohol into the company's possession area.",
    "wooden": "The hotel replaced the wooden counter near reception.",
    "tale": "The annual report tells the tale of the company's expansion.",
    "pot": "The cafeteria placed a pot of coffee in the meeting room.",
    "whilst": "The assistant checked the invoice whilst waiting for the client.",
    "pretend": "Do not pretend that the missing approval is unimportant.",
    "pride": "The team takes pride in its record of accurate deliveries.",
    "strict": "The laboratory follows strict rules for handling samples.",
    "shell": "The technician replaced the outer shell of the device.",
    "humor": "The speaker used gentle humor to make the training more engaging.",
    "wise": "It was wise to confirm the contract before ordering materials.",
    "jail": "The contractor completed a security upgrade at the jail.",
    "shelter": "The company donated supplies to a local shelter.",
    "pipe": "The maintenance team replaced a leaking pipe.",
    "guitar": "The hotel hired a guitarist for the employee event.",
    "piano": "The restaurant moved the piano to make room for the conference tables.",
    "magic": "The new software is not magic; it requires careful setup.",
    "ski": "The resort offers ski packages for corporate guests.",
    "whisper": "Please do not whisper while the client is speaking.",
    "menu": "The restaurant prepared a special menu for the business dinner.",
    "moon": "The hotel used the moon as a theme for its evening event.",
    "jury": "The jury reviewed the evidence before reaching its decision.",
    "scan": "The technician will scan the documents into the archive.",
    "hopefully": "Hopefully, the supplier will confirm the delivery date today.",
    "trick": "The trainer showed a trick for remembering the new procedure.",
    "paragraph": "The report begins each paragraph with a clear topic sentence.",
    "maker": "The equipment maker issued a safety notice.",
    "potato": "The cafeteria added a baked potato to the lunch menu.",
    "invent": "The engineer invented a tool that speeds up inspections.",
    "pro": "The company hired a pro to train the sales team.",
    "stair": "The emergency stair is beside the service entrance.",
    "hesitate": "Please do not hesitate to contact customer support.",
    "shine": "The new product will shine in a competitive market.",
    "romantic": "The hotel prepared a romantic package for the anniversary promotion.",
    "stomach": "The employee visited the clinic after reporting stomach pain.",
    "nowhere": "The missing invoice was nowhere in the finance archive.",
    "pray": "The family asked employees to pray for the injured colleague.",
    "servant": "The museum's former servant quarters are now offices.",
    "surprisingly": "Surprisingly, the small branch exceeded its sales target.",
    "stamp": "Please stamp the receipt before filing it.",
    "knife": "Store the kitchen knife safely after the catering event.",
    "weekly": "The manager holds a weekly meeting with the support team.",
    "wherever": "Wherever the branch operates, the same safety rules apply.",
    "printer": "The technician repaired the printer before the meeting.",
    "ocean": "The company monitors ocean conditions before shipping by sea.",
    "quietly": "The team quietly tested the new system before the public launch.",
    "nerve": "The representative had the nerve to ask for a contract extension.",
    "fiction": "The bookstore selected business fiction for the lobby display.",
    "hurry": "There is no need to hurry; the meeting starts at three.",
    "raw": "The factory stores raw materials in a separate area.",
    "hint": "The audit provided a hint about the source of the error.",
    "hook": "The display uses a hook to hold each product sample.",
    "liquid": "The laboratory stores the liquid in a sealed container.",
    "panic": "The emergency plan helps staff avoid panic during an outage.",
}

JA = {
    "rid": "チームは監査前に倉庫から古い在庫を取り除く。",
    "ruin": "不注意な変更で顧客の配送予定を台無しにする可能性がある。",
    "motor": "技術者は搬送システムのモーターを交換した。",
    "permission": "立入制限区域に入る前に許可を得てください。",
    "valley": "会社は谷に中継施設を建設した。",
    "mad": "顧客は説明のない料金に腹を立てた。",
    "visible": "安全ラベルはすべての荷物にはっきり見える状態で貼る必要がある。",
    "violent": "警備計画は暴力的な事件のリスクを扱っている。",
    "slave": "博物館は奴隷制度が地域の交易史に与えた影響を説明している。",
    "journal": "研究者は検査結果をプロジェクト日誌に記録した。",
    "measurement": "技術者は設計を承認する前に測定値を確認した。",
    "random": "システムは各監査に無作為の照会番号を割り当てる。",
    "successfully": "技術チームは新しい機器の試験に成功した。",
    "illustration": "マニュアルには設置手順の図解がある。",
    "rail": "出荷品は北部の配送拠点から鉄道で発送される。",
    "laboratory": "会社は製品検査のため研究室を改修した。",
    "passion": "彼女の顧客サービスへの情熱は電話対応に表れている。",
    "roughly": "修理にはおよそ3時間かかる。",
    "skirt": "デザイナーは正式なイベント用に濃い色のスカートを選んだ。",
    "march": "新しい方針は3月に施行される。",
    "weakness": "監査で承認手続きの弱点が見つかった。",
    "salt": "レストランはビジネスランチの塩分を減らした。",
    "opera": "ホテルは来訪する役員のためオペラのチケットを手配した。",
    "praise": "取締役は締め切りを守ったチームを称賛した。",
    "silent": "発表中は携帯電話を消音にしてください。",
    "pump": "保守チームは水ポンプを修理した。",
    "publisher": "出版社は会社の年次報告書を発行した。",
    "weigh": "買い手は契約に署名する前に費用を慎重に検討する。",
    "profession": "会社は会計職に就く人向けの研修を提供している。",
    "injure": "安全手順は作業員の負傷防止に役立つ。",
    "remote": "会社は遠隔地の現場で働く従業員を支援している。",
    "orange": "倉庫は優先出荷品にオレンジ色のラベルを使う。",
    "twist": "マネージャーは標準研修に実用的な工夫を加えた。",
    "imagination": "デザインチームは想像力を使って使いやすい包装を作った。",
    "throat": "従業員が喉の痛みを訴えたため、診療所は休養を勧めた。",
    "joy": "顧客が提案を承認したとき、チームは喜びを感じた。",
    "pregnant": "会社は妊娠中の従業員に柔軟な勤務時間を提供している。",
    "reliable": "仕入先は納期を守ってきた信頼できる実績がある。",
    "poet": "会社は慈善イベントに詩人を招いた。",
    "pile": "書類の山を資料室へ移してください。",
    "pig": "その農場はホテルのレストランに豚肉を供給している。",
    "mixture": "技術者は機器の洗浄用混合液を準備した。",
    "poetry": "書店は文化イベントの展示に詩集を加えた。",
    "sake": "安全のため荷積み場を空けておいてください。",
    "shelf": "倉庫は小さな交換部品用の棚を追加した。",
    "tail": "アシスタントは航空機の尾翼番号を確認した。",
    "possession": "従業員は会社の保管区域へアルコールを持ち込んではならない。",
    "wooden": "ホテルは受付近くの木製カウンターを交換した。",
    "tale": "年次報告書は会社の拡張の物語を伝えている。",
    "pot": "食堂は会議室にコーヒーのポットを置いた。",
    "whilst": "アシスタントは顧客を待つ間に請求書を確認した。",
    "pretend": "承認がないことを重要でないふりをしないでください。",
    "pride": "チームは正確な配送実績を誇りにしている。",
    "strict": "研究所はサンプルの取り扱いに厳格な規則を設けている。",
    "shell": "技術者は機器の外装を交換した。",
    "humor": "講演者は研修を楽しくするため穏やかなユーモアを使った。",
    "wise": "注文前に契約を確認したのは賢明だった。",
    "jail": "請負業者は刑務所の警備設備を更新した。",
    "shelter": "会社は地域の保護施設に物資を寄付した。",
    "pipe": "保守チームは水漏れした管を交換した。",
    "guitar": "ホテルは従業員イベントのためギタリストを雇った。",
    "piano": "レストランは会議テーブルの場所を作るためピアノを移動した。",
    "magic": "新しいソフトウェアは魔法ではなく、慎重な設定が必要だ。",
    "ski": "リゾートは法人客向けにスキーのパッケージを提供している。",
    "whisper": "顧客が話している間はささやかないでください。",
    "menu": "レストランはビジネスディナー用の特別メニューを用意した。",
    "moon": "ホテルは夜のイベントのテーマに月を使った。",
    "jury": "陪審員団は判断を下す前に証拠を確認した。",
    "scan": "技術者は会議前に書類をスキャンして保存する。",
    "hopefully": "うまくいけば、仕入先は今日納品日を確認する。",
    "trick": "研修担当者は新しい手順を覚えるコツを教えた。",
    "paragraph": "報告書は各段落を明確な主題文で始める。",
    "maker": "機器メーカーは安全通知を発行した。",
    "potato": "食堂は昼食メニューにベイクドポテトを加えた。",
    "invent": "技術者は検査を速める工具を発明した。",
    "pro": "会社は営業チームを指導するプロを雇った。",
    "stair": "非常階段はサービス入口の隣にある。",
    "hesitate": "顧客サポートへの連絡をためらわないでください。",
    "shine": "新製品は競争の激しい市場で際立つだろう。",
    "romantic": "ホテルは記念日キャンペーン用にロマンチックなパッケージを用意した。",
    "stomach": "従業員は腹痛を訴えて診療所を訪れた。",
    "nowhere": "紛失した請求書は財務資料のどこにもなかった。",
    "pray": "家族は負傷した同僚のために祈るよう従業員に求めた。",
    "servant": "博物館の元使用人宿舎は現在オフィスになっている。",
    "surprisingly": "意外にも、小さな支店が売上目標を上回った。",
    "stamp": "領収書にスタンプを押してから保管してください。",
    "knife": "ケータリングイベント後は台所用ナイフを安全に保管する。",
    "weekly": "マネージャーはサポートチームと毎週会議を行う。",
    "wherever": "支店がどこで営業していても同じ安全規則を適用する。",
    "printer": "技術者は会議前にプリンターを修理した。",
    "ocean": "会社は海上輸送前に海洋状況を監視している。",
    "quietly": "チームは一般公開前に新システムを静かに試験した。",
    "nerve": "担当者は契約延長を求める度胸があった。",
    "fiction": "書店はロビーの展示にビジネス小説を選んだ。",
    "hurry": "会議は3時に始まるので急ぐ必要はない。",
    "raw": "工場は原材料を別の区域に保管している。",
    "hint": "監査で誤りの原因を示す手がかりが見つかった。",
    "hook": "展示台はフックで各製品サンプルを支えている。",
    "liquid": "研究所は液体を密閉容器に保管している。",
    "panic": "緊急計画は停電時にスタッフがパニックになるのを防ぐ。",
}

def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    rows = [x for x in vocabulary if int(x.get("level", 0)) == 3][300:400]
    assert {str(x["word"]).casefold() for x in rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in rows:
        word = str(item["word"]).casefold()
        source = EN[word]
        item["example"] = source
        ex = translations.setdefault(f"builtin:{item['id']}", {}).setdefault("example", {})
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if ex.get(field) != value:
                ex[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 700+ English examples batch 2a: {len(rows)} terms, {changed} fields")

if __name__ == "__main__":
    main()
