#!/usr/bin/env python3
"""Review 300 TOEIC 600+ examples (items 1001-1300) in English and Japanese."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"

EN = {
    "promotion": "She received a promotion after exceeding her sales targets.",
    "fulfill": "The supplier must fulfill the terms of the purchase agreement.",
    "dedicate": "The company will dedicate additional staff to the customer support team.",
    "province": "The company opened a distribution center in the northern province.",
    "evaluation": "The manager completed an evaluation of the new employee's performance.",
    "compromise": "Both sides reached a compromise on the delivery schedule.",
    "accomplish": "The team accomplished its goal before the end of the quarter.",
    "literary": "The hotel hosted a literary event for local authors.",
    "govern": "The board governs the company according to its bylaws.",
    "embrace": "The company decided to embrace digital payments across all branches.",
    "compensation": "The employee received compensation for the approved travel expenses.",
    "classical": "The restaurant played classical music during the formal dinner.",
    "versus": "The report compares online sales versus in-store sales.",
    "deficit": "The department must reduce its budget deficit this year.",
    "modify": "The engineer modified the design to reduce production costs.",
    "literally": "The instructions literally state that all visitors must sign in.",
    "equation": "The analyst checked the equation used in the cost estimate.",
    "gesture": "The manager made a welcoming gesture to the visiting clients.",
    "assign": "The manager assigned the task to the most experienced technician.",
    "inflation": "Inflation has increased the cost of raw materials.",
    "historic": "The company signed a historic agreement with its first overseas partner.",
    "therapy": "The company offers therapy support through its employee assistance program.",
    "personnel": "Only authorized personnel may enter the storage area.",
    "insight": "The survey provided valuable insight into customer preferences.",
    "tackle": "The new manager plans to tackle the staffing problem first.",
    "exceed": "The product exceeded the sales forecast in its first month.",
    "expenditure": "The finance team reviewed capital expenditure for the next quarter.",
    "fortune": "The company spent a fortune upgrading its aging equipment.",
    "ceremony": "The company held a ceremony to recognize long-serving employees.",
    "automatically": "The system automatically sends a receipt after payment.",
    "scholar": "The company invited a scholar to speak about the history of trade.",
    "psychological": "The training covers the psychological effects of workplace stress.",
    "dramatically": "The new process dramatically reduced the time needed to approve orders.",
    "stake": "The investor has a significant stake in the company.",
    "partnership": "The partnership will expand the company's delivery network.",
    "participation": "Employee participation in the safety workshop is required.",
    "clause": "The contract includes a clause about late-payment fees.",
    "penalty": "The supplier must pay a penalty for missing the agreed deadline.",
    "chamber": "The meeting was held in the largest chamber of the conference center.",
    "fancy": "The client requested a fancy dinner for the visiting executives.",
    "evolve": "The service continues to evolve as customer needs change.",
    "boost": "The campaign should boost sales during the holiday season.",
    "abortion": "The clinic provides confidential information about reproductive health services.",
    "boom": "The region experienced a construction boom after the new airport opened.",
    "democratic": "The committee used a democratic process to select its chairperson.",
    "maintenance": "Regular maintenance keeps the delivery vehicles safe and reliable.",
    "consequently": "The supplier missed the deadline; consequently, the shipment was delayed.",
    "strengthen": "The company strengthened its data-security procedures.",
    "constraint": "The main constraint on the project is the limited budget.",
    "undergo": "The equipment will undergo a safety inspection next week.",
    "potentially": "The new route could potentially reduce delivery time.",
    "scope": "The project scope includes training, installation, and follow-up support.",
    "diversity": "The company values diversity in its workforce.",
    "allege": "The customer alleged that the invoice contained unauthorized charges.",
    "intense": "The sales team faced intense competition in the overseas market.",
    "inquiry": "Our representative will respond to your inquiry within one business day.",
    "resign": "The director decided to resign at the end of the fiscal year.",
    "craft": "The artisan crafted a display case for the company's award.",
    "concrete": "The client requested concrete details about the delivery plan.",
    "distinct": "The two brands have distinct identities and target different customers.",
    "limitation": "The report explains a limitation of the current software.",
    "indication": "The rise in repeat orders is an indication of customer satisfaction.",
    "stability": "The new contract provides stability for the regional office.",
    "neglect": "The company must not neglect routine safety checks.",
    "compose": "The assistant composed a brief email to the supplier.",
    "mere": "The delay was not a mere inconvenience because it affected production.",
    "regulate": "The agency regulates the transport of hazardous materials.",
    "trigger": "The announcement triggered a sharp increase in online orders.",
    "destruction": "The storm caused the destruction of several storage buildings.",
    "mystery": "The technician solved the mystery of the repeated system failures.",
    "rear": "The rear entrance is reserved for deliveries.",
    "presumably": "The package was presumably sent to the wrong branch.",
    "amendment": "The lawyer prepared an amendment to the service contract.",
    "civilian": "The emergency plan explains how to protect civilian visitors.",
    "composition": "The manager reviewed the composition of the project team.",
    "regardless": "The service will operate regardless of weather conditions.",
    "racial": "The company prohibits racial discrimination in the workplace.",
    "sanction": "The facility cannot open without regulatory sanction.",
    "stimulate": "The tax reduction may stimulate investment in local businesses.",
    "narrative": "The annual report presents a clear narrative about the company's growth.",
    "tissue": "The clinic stores tissue samples according to strict safety rules.",
    "barely": "The branch barely met its sales target this quarter.",
    "tourism": "Tourism supports many businesses in the coastal region.",
    "motivation": "The bonus gave employees extra motivation to meet the target.",
    "firmly": "Please hold the package firmly while sealing the box.",
    "interior": "The contractor redesigned the interior of the reception area.",
    "immigrant": "The company offers language support to immigrant employees.",
    "excess": "The warehouse returned the excess inventory to the supplier.",
    "complexity": "The consultant explained the complexity of the new tax rules.",
    "liability": "The contract defines the supplier's liability for damaged goods.",
    "extract": "The analyst extracted the sales figures from the database.",
    "implementation": "The implementation of the new policy begins next month.",
    "bias": "The hiring committee received training to reduce unconscious bias.",
    "continuous": "The factory requires continuous monitoring of the temperature.",
    "guideline": "The manual provides a guideline for handling customer complaints.",
    "biological": "The laboratory follows strict rules for biological materials.",
    "consume": "The new equipment consumes less electricity than the old model.",
    "luxury": "The hotel offers a luxury package for corporate guests.",
    "anxious": "The applicant felt anxious before the job interview.",
    "exhaust": "The technician checked the vehicle's exhaust system.",
    "attraction": "The new museum is a major attraction for business travelers.",
    "veteran": "A veteran manager trained the new customer-service representatives.",
    "reflection": "The report is a reflection of the company's improved performance.",
    "determination": "Her determination helped the team finish the project on time.",
    "cluster": "The company opened offices in a cluster of buildings near the airport.",
    "logic": "The proposal follows a clear logic that the board could understand.",
    "controversial": "The board postponed the controversial policy change.",
    "revise": "The team will revise the contract before sending it to the client.",
    "genuine": "The customer expressed genuine appreciation for the quick response.",
    "vessel": "The vessel will transport the equipment to the island branch.",
    "harbor": "The company built a warehouse near the harbor.",
    "storage": "The new storage area has room for next month's inventory.",
    "supplement": "The brochure includes a supplement with updated prices.",
    "adjustment": "The accountant made an adjustment to the final invoice.",
    "flexible": "The company offers flexible working hours to full-time staff.",
    "abstract": "The report begins with an abstract of the proposed research.",
    "precise": "Please provide the precise location of the delivery entrance.",
    "situate": "The architect situated the reception desk near the main entrance.",
    "summarize": "Please summarize the main points of the client meeting.",
    "probability": "There is a high probability that the shipment will arrive tomorrow.",
    "uncertainty": "The manager explained the uncertainty surrounding the launch date.",
    "refugee": "The company supports a program that helps refugees find work.",
    "comprise": "The project team comprises engineers, designers, and sales staff.",
    "experimental": "The company is testing an experimental payment system.",
    "institutional": "The policy addresses institutional responsibility for data security.",
    "subsequently": "The supplier subsequently sent a corrected invoice.",
    "ownership": "The contract clearly states who has ownership of the software.",
    "qualification": "The position requires a qualification in accounting or finance.",
    "suspend": "The company will suspend deliveries during the holiday closure.",
    "functional": "The new office has a functional layout for collaborative work.",
    "voluntary": "Participation in the employee survey is voluntary.",
    "organic": "The supermarket sells organic coffee to office customers.",
    "server": "The IT team restarted the server after the system update.",
    "structural": "The engineer inspected the structural supports of the warehouse.",
    "alongside": "The new warehouse was built alongside the existing facility.",
    "compute": "The software can compute the total cost automatically.",
    "gaze": "The visitor began to gaze at the display of new products.",
    "theoretical": "The training connects theoretical knowledge with practical tasks.",
    "fragment": "The technician found a fragment of metal in the machine.",
    "immigration": "The company provides information about immigration procedures for new hires.",
    "tender": "The contractor submitted a tender for the office renovation.",
    "density": "The warehouse manager checked the density of the packed materials.",
    "module": "The online course includes a module on customer complaints.",
    "attachment": "Please open the attachment before the meeting.",
    "dirty": "The maintenance team replaced the dirty air filter.",
    "bread": "The hotel ordered fresh bread for the morning buffet.",
    "blind": "The company installed tactile signs to support blind visitors.",
    "bloody": "The nurse replaced the bloody bandage in the clinic.",
    "bend": "The metal beam may bend under excessive pressure.",
    "briefly": "The director briefly explained the reason for the schedule change.",
    "alarm": "The alarm sounded when smoke entered the loading area.",
    "flood": "The flood damaged the road leading to the warehouse.",
    "crazy": "It would be crazy to ignore the safety warning.",
    "boot": "The technician will boot the computer after replacing the hard drive.",
    "accurate": "Please check that the customer address is accurate before shipping.",
    "dealer": "The dealer offered a discount on the replacement vehicle.",
    "button": "Press the green button to start the machine.",
    "desert": "The company built a solar facility in the desert.",
    "bowl": "The cafeteria placed a bowl of fruit near the entrance.",
    "discovery": "The discovery of the defect prevented a costly recall.",
    "bath": "The hotel renovated every bath before reopening.",
    "criticize": "The manager encouraged staff to improve the process rather than criticize colleagues.",
    "apologize": "The supplier apologized for the delay in delivery.",
    "grab": "Please grab the correct file before the client arrives.",
    "digital": "The company adopted digital invoices to reduce paper use.",
    "edit": "The assistant will edit the report before publication.",
    "exact": "The customer requested the exact delivery time.",
    "dig": "The construction crew will dig a trench for the new cable.",
    "drag": "A missing approval can drag out the purchasing process.",
    "angle": "The presentation explains the issue from a customer's angle.",
    "chicken": "The restaurant added a grilled chicken dish to the lunch menu.",
    "admire": "The team admires the director's calm leadership style.",
    "charity": "The company donated equipment to a local charity.",
    "cigarette": "Smoking cigarettes is prohibited near the warehouse entrance.",
    "cousin": "Her cousin works for an international logistics company.",
    "eastern": "The eastern branch serves customers in three neighboring countries.",
    "forecast": "The finance team updated its sales forecast.",
    "custom": "The manufacturer can produce custom packaging for large orders.",
    "adapt": "The team adapted the training materials for remote employees.",
    "cap": "The company placed a cap on travel expenses.",
    "charm": "The hotel preserves the historic charm of the building.",
    "dialog": "The software displays a dialog asking users to confirm payment.",
    "cream": "The café provides cream and sugar beside the coffee machine.",
    "cancel": "The airline may cancel the flight because of severe weather.",
    "beneath": "The emergency exit is beneath the main staircase.",
    "absolute": "The contract requires absolute confidentiality during the negotiations.",
    "dare": "Few employees dare to question the safety procedure.",
    "divorce": "The employee requested leave to handle a divorce proceeding.",
    "bury": "The construction crew had to bury the new cables underground.",
    "frequent": "The branch receives frequent requests for weekend delivery.",
    "counter": "The manager proposed a plan to counter the competitor's discount.",
    "float": "The company let the idea float before making a final decision.",
    "greatly": "The revised process greatly improved customer satisfaction.",
    "electric": "The company added electric vehicles to its delivery fleet.",
    "acceptable": "The revised delivery date is acceptable to the client.",
    "coal": "The factory is reducing its use of coal to cut emissions.",
    "burst": "A pipe burst and flooded the maintenance room.",
    "buyer": "The buyer inspected the equipment before signing the agreement.",
    "champion": "The director is a champion of flexible work policies.",
    "dust": "The cleaning team removed dust from the ventilation system.",
    "announcement": "The company issued an announcement about the office relocation.",
    "glance": "A quick glance at the agenda showed that the budget review was next.",
    "contest": "The company held a contest to choose a design for the new brochure.",
    "brush": "The cleaner used a brush to remove dust from the equipment.",
    "embarrass": "The manager's mistake did not embarrass the new employee.",
    "gallery": "The company rented a gallery for the product launch event.",
    "aggressive": "The sales team adopted an aggressive strategy in the new market.",
    "chest": "The emergency kit is stored in a chest near the reception desk.",
    "format": "Please save the report in the requested format.",
    "celebration": "The department held a celebration after reaching its annual target.",
    "golf": "The hotel has a golf course for corporate guests.",
    "flash": "A flash from the camera distracted the presenter.",
    "friendship": "The partnership developed into a lasting friendship between the founders.",
    "entertain": "The host arranged a short performance to entertain the conference guests.",
    "fantastic": "The team received fantastic feedback from the client.",
    "disagree": "The managers disagree about the best delivery option.",
    "forever": "The company cannot keep the temporary system forever.",
    "gear": "The technician checked the safety gear before entering the site.",
    "click": "Click the menu item to pay for your lunch with office funds.",
    "creature": "The safety team removed a small creature from the warehouse.",
    "chat": "Employees can chat with the support team through the internal app.",
    "clothing": "The company provides protective clothing for warehouse workers.",
    "curious": "The customer was curious about the reason for the price change.",
    "cow": "The farm supplies milk from cows to the local hotel.",
    "fold": "Please fold the brochures before placing them on the counter.",
    "bin": "Please put empty coffee cups in the bin near the entrance.",
    "damn": "The technician said the damn printer had stopped again.",
    "carbon": "The report explains how carbon emissions affect nearby communities.",
    "cheese": "The cafeteria added a grilled cheese sandwich to the lunch menu.",
    "flag": "The national flag was displayed at the entrance to the conference hall.",
    "bless": "The director blessed the new partnership at the opening ceremony.",
    "airline": "The airline notified passengers about the departure change.",
    "grandmother": "Her grandmother owns a small shop near the regional office.",
    "cooperation": "The project succeeded through cooperation between the two departments.",
    "coin": "The vending machine accepts both coins and cards.",
    "bunch": "The assistant ordered a bunch of flowers for the opening event.",
    "greet": "The receptionist will greet visitors at the main entrance.",
    "chocolate": "The hotel placed a box of chocolate in each guest room.",
    "belt": "The conveyor belt stopped during the morning shift.",
    "championship": "The company sponsored the regional tennis championship.",
    "differently": "The two branches handle customer complaints differently.",
    "catalog": "The supplier sent a catalog of its latest office furniture.",
    "golden": "The company saw a golden opportunity to enter the growing market.",
    "envelope": "Please place the signed contract in the envelope.",
    "bite": "The employee took a quick bite before returning to the meeting.",
    "firstly": "Firstly, check the invoice; then, approve the payment.",
    "adventure": "The travel company offers an adventure package for corporate groups.",
    "fence": "The contractor repaired the fence around the construction site.",
    "castle": "The hotel organized a tour of the historic castle for visitors.",
    "altogether": "The three branches hired fifty employees altogether.",
    "carpet": "The hotel replaced the carpet in the conference room.",
    "confusion": "The unclear notice caused confusion among the customers.",
    "grammar": "The editor checked the grammar in the customer newsletter.",
    "bell": "The bell rings when a customer enters the store.",
    "comedy": "The company hired a comedy group for the staff event.",
    "chase": "The security guard had to chase a thief from the store.",
    "filter": "The technician replaced the filter in the air-conditioning unit.",
    "distant": "The branch is in a distant town, so deliveries take longer.",
    "grain": "The company exports grain through the northern port.",
    "excitement": "There was excitement in the office when the product won an award.",
    "gentle": "The nurse used a gentle approach when treating the injured employee.",
    "athlete": "The company hired a professional athlete for the health campaign.",
    "fool": "It would be foolish to ignore the warning from the safety officer.",
    "gently": "Please close the cabinet gently so the equipment is not damaged.",
    "fade": "The color on the outdoor sign may fade in direct sunlight.",
    "cough": "A persistent cough should be reported to the workplace clinic.",
    "curtain": "The theater lowered the curtain after the company presentation.",
    "darkness": "The emergency lights turned on when darkness filled the hallway.",
    "aunt": "Her aunt manages a small restaurant near the airport.",
    "autumn": "The company plans to launch the service in autumn.",
    "cheek": "The employee had a bruise on her cheek after the minor accident.",
    "alright": "The revised delivery date is alright with the customer.",
    "absorb": "The training helps new employees absorb the company's procedures.",
    "accent": "The call-center agent's accent was clear and easy to understand.",
    "airplane": "The airplane carrying the sales team landed on time.",
    "apple": "The cafeteria provides an apple with every employee lunch.",
    "arrow": "Follow the arrow on the sign to reach the loading dock.",
    "artificial": "The company uses artificial lighting in the underground storage area.",
    "assignment": "The manager gave each employee a clear assignment.",
    "backward": "The truck moved backward slowly while leaving the loading dock.",
    "bang": "A loud bang came from the maintenance room.",
    "bargain": "The purchasing manager found a bargain on office chairs.",
    "barrel": "The factory stores oil in a secure barrel.",
    "bat": "The warehouse closed early after a bat entered the building.",
    "beam": "The engineer inspected the steel beam above the entrance.",
    "blank": "Please do not leave any required field blank on the form.",
    "bleed": "The nurse treated the cut before it began to bleed again.",
    "bubble": "A bubble in the packaging showed that the seal was defective.",
    "bucket": "The cleaner carried a bucket of water to the storage area.",
    "calculator": "The accountant used a calculator to check the invoice total.",
    "cheat": "Employees must not cheat on the compliance examination.",
    "cheer": "The staff gathered to cheer for the company team.",
    "chess": "The hotel offers a chess set in its business lounge.",
    "cinema": "The company rented a cinema for the private product screening.",
    "clay": "The design team used clay to create a model of the new product.",
    "clever": "The engineer found a clever way to reduce packaging waste.",
    "client": "The client approved the revised proposal.",
    "clinic": "The clinic records every workplace injury in a secure system.",
    "clip": "The manager attached a short video clip to the training email.",
    "clue": "The audit provided a clue about the source of the duplicate payment.",
}

JA_1201_1300 = {
    "announcement": "会社はオフィス移転について告知を出した。",
    "glance": "議題をざっと見ると、次が予算確認だと分かった。",
    "contest": "会社は新しいパンフレットのデザインを選ぶコンテストを開催した。",
    "brush": "清掃員はブラシで機器のほこりを取り除いた。",
    "embarrass": "マネージャーのミスで新入社員が恥ずかしい思いをすることはなかった。",
    "gallery": "会社は新製品発表イベントのためにギャラリーを借りた。",
    "aggressive": "営業チームは新市場で積極的な戦略を採用した。",
    "chest": "救急用品は受付近くの箱に保管されている。",
    "format": "報告書を指定された形式で保存してください。",
    "celebration": "部署は年間目標を達成した後、祝賀会を開いた。",
    "golf": "ホテルには法人客向けのゴルフコースがある。",
    "flash": "カメラのフラッシュが発表者の気を散らした。",
    "friendship": "創業者同士の提携は長く続く友情へ発展した。",
    "entertain": "主催者は会議の来賓を楽しませる短い演目を用意した。",
    "fantastic": "チームは顧客から素晴らしい評価を受けた。",
    "disagree": "マネージャーたちは最適な配送方法について意見が一致しない。",
    "forever": "会社は臨時システムを永遠に使い続けることはできない。",
    "gear": "技術者は現場に入る前に安全装備を点検した。",
    "click": "メニュー項目をクリックして社内費用で昼食代を支払ってください。",
    "creature": "安全チームは倉庫から小さな生き物を追い出した。",
    "chat": "従業員は社内アプリでサポートチームと雑談できる。",
    "clothing": "会社は倉庫作業員に保護服を支給している。",
    "curious": "顧客は値上げの理由を知りたがった。",
    "cow": "その農場は地元ホテルに牛乳を供給している。",
    "fold": "カウンターに置く前にパンフレットを折ってください。",
    "bin": "空のコーヒーカップは入口近くのごみ箱に入れてください。",
    "damn": "技術者は、あのプリンターはまた止まったと言った。",
    "carbon": "報告書は炭素排出が近隣地域に及ぼす影響を説明した。",
    "cheese": "食堂は昼食メニューにグリルチーズサンドを加えた。",
    "flag": "会議場の入口に国旗が掲げられた。",
    "bless": "取締役は開会式で新しい提携を祝福した。",
    "airline": "航空会社は出発時刻の変更を乗客に通知した。",
    "grandmother": "彼女の祖母は地域オフィスの近くで小さな店を経営している。",
    "cooperation": "2つの部署の協力によってプロジェクトは成功した。",
    "coin": "自動販売機は硬貨とカードの両方に対応している。",
    "bunch": "アシスタントは開業イベント用に花をひと束注文した。",
    "greet": "受付係が正面入口で来訪者を迎える。",
    "chocolate": "ホテルは各客室にチョコレートの箱を置いた。",
    "belt": "朝の勤務中に搬送ベルトが停止した。",
    "championship": "会社は地域のテニス選手権を後援した。",
    "differently": "2つの支店は顧客の苦情に異なる方法で対応する。",
    "catalog": "仕入先は最新のオフィス家具のカタログを送った。",
    "golden": "会社は成長市場へ参入する絶好の機会を見つけた。",
    "envelope": "署名済みの契約書を封筒に入れてください。",
    "bite": "従業員は会議に戻る前に少し食事を取った。",
    "firstly": "第一に請求書を確認し、次に支払いを承認してください。",
    "adventure": "旅行会社は法人グループ向けに冒険旅行パッケージを提供している。",
    "fence": "請負業者は建設現場の周囲の柵を修理した。",
    "castle": "ホテルは来訪者向けに歴史的な城のツアーを企画した。",
    "altogether": "3つの支店で合計50人を採用した。",
    "carpet": "ホテルは会議室のじゅうたんを交換した。",
    "confusion": "不明確な通知が顧客の混乱を招いた。",
    "grammar": "編集者は顧客向けニュースレターの文法を確認した。",
    "bell": "顧客が店に入るとベルが鳴る。",
    "comedy": "会社はスタッフイベントにコメディーグループを招いた。",
    "chase": "警備員は店から泥棒を追い出さなければならなかった。",
    "filter": "技術者は空調装置のフィルターを交換した。",
    "distant": "支店は遠い町にあるため、配送に時間がかかる。",
    "grain": "会社は北部の港から穀物を輸出している。",
    "excitement": "製品が賞を取ったとき、オフィスは興奮に包まれた。",
    "gentle": "看護師は負傷した従業員に優しく対応した。",
    "athlete": "会社は健康キャンペーンのためプロの運動選手を雇った。",
    "fool": "安全担当者の警告を無視するのは愚かなことだ。",
    "gently": "機器を傷つけないよう、キャビネットをそっと閉めてください。",
    "fade": "屋外看板の色は直射日光で薄れる可能性がある。",
    "cough": "長引くせきは職場の診療所に報告してください。",
    "curtain": "会社の発表後、劇場の幕が下りた。",
    "darkness": "廊下が暗くなると非常灯が点いた。",
    "aunt": "彼女のおばは空港近くで小さなレストランを経営している。",
    "autumn": "会社は秋にサービスを開始する予定だ。",
    "cheek": "従業員は軽い事故の後、頬にあざができた。",
    "alright": "変更後の納品日は顧客にとって問題ない。",
    "absorb": "研修は新入社員が会社の手順を理解するのに役立つ。",
    "accent": "コールセンター担当者のアクセントは明瞭で聞き取りやすかった。",
    "airplane": "営業チームを乗せた飛行機は時間どおりに着陸した。",
    "apple": "食堂は従業員の昼食にリンゴを1個添えている。",
    "arrow": "標識の矢印に従うと荷積み場に着く。",
    "artificial": "会社は地下の保管エリアで人工照明を使っている。",
    "assignment": "マネージャーは各従業員に明確な作業を割り当てた。",
    "backward": "トラックは荷積み場から出る際、ゆっくり後退した。",
    "bang": "保守室から大きな音が聞こえた。",
    "bargain": "購買マネージャーはオフィス椅子をお買い得価格で見つけた。",
    "barrel": "工場は油を安全な樽に保管している。",
    "bat": "倉庫にコウモリが入ったため、早く閉鎖した。",
    "beam": "技術者は入口の上にある鋼鉄の梁を点検した。",
    "blank": "フォームの必須項目を空欄のままにしないでください。",
    "bleed": "看護師は傷から再び出血する前に手当てした。",
    "bubble": "包装の気泡は封が不良であることを示していた。",
    "bucket": "清掃員は水の入ったバケツを保管エリアへ運んだ。",
    "calculator": "経理担当者は電卓で請求書の合計を確認した。",
    "cheat": "従業員はコンプライアンス試験で不正をしてはいけない。",
    "cheer": "スタッフは会社のチームに声援を送るため集まった。",
    "chess": "ホテルはビジネスラウンジにチェスセットを用意している。",
    "cinema": "会社は新製品の試写会のため映画館を借りた。",
    "clay": "デザインチームは新製品の模型を粘土で作った。",
    "clever": "技術者は包装廃棄物を減らす巧妙な方法を見つけた。",
    "client": "顧客は改訂版の提案書を承認した。",
    "clinic": "診療所はすべての職場でのけがを安全なシステムに記録する。",
    "clip": "マネージャーは研修メールに短い動画を添付した。",
    "clue": "監査で二重支払いの原因を示す手がかりが見つかった。",
}

JA_1101_1200 = {
    "attraction": "新しい博物館は出張者にとって大きな見どころだ。",
    "veteran": "ベテランのマネージャーが新しい顧客サービス担当者を指導した。",
    "reflection": "その報告書は会社の業績改善を反映している。",
    "determination": "彼女の決意がチームの期限内のプロジェクト完了を支えた。",
    "cluster": "会社は空港近くに集まる複数のビルにオフィスを開いた。",
    "logic": "その提案は取締役会にも理解できる明確な論理に基づいている。",
    "controversial": "取締役会は物議を醸す方針変更を延期した。",
    "revise": "チームは顧客に送る前に契約書を改訂する。",
    "genuine": "顧客は迅速な対応に心から感謝を示した。",
    "vessel": "船は島の支店へ機器を輸送する。",
    "harbor": "会社は港の近くに倉庫を建設した。",
    "storage": "新しい保管エリアには来月の在庫を置くスペースがある。",
    "supplement": "パンフレットには最新価格を載せた補足資料が含まれている。",
    "adjustment": "経理担当者は最終請求書を調整した。",
    "flexible": "会社は正社員に柔軟な勤務時間を提供している。",
    "abstract": "報告書は提案された調査の要約から始まる。",
    "precise": "配送入口の正確な場所を教えてください。",
    "situate": "建築家は受付を正面入口の近くに配置した。",
    "summarize": "顧客会議の主な点を要約してください。",
    "probability": "出荷品が明日到着する可能性は高い。",
    "uncertainty": "マネージャーは発売日をめぐる不確実性を説明した。",
    "refugee": "会社は難民の就職を支援する事業を支援している。",
    "comprise": "プロジェクトチームは技術者、デザイナー、営業スタッフで構成されている。",
    "experimental": "会社は実験的な支払いシステムを試している。",
    "institutional": "その方針はデータセキュリティに対する組織の責任を扱っている。",
    "subsequently": "仕入先はその後、訂正した請求書を送った。",
    "ownership": "契約書はソフトウェアの所有権者を明確に定めている。",
    "qualification": "その職には会計または財務の資格が必要だ。",
    "suspend": "会社は休業期間中、配送を一時停止する。",
    "functional": "新しいオフィスは共同作業に機能的なレイアウトになっている。",
    "voluntary": "従業員調査への参加は任意だ。",
    "organic": "スーパーはオフィスの顧客にオーガニックコーヒーを販売している。",
    "server": "ITチームはシステム更新後にサーバーを再起動した。",
    "structural": "技術者は倉庫の構造支持部を点検した。",
    "alongside": "新しい倉庫は既存施設の隣に建設された。",
    "compute": "ソフトウェアは総費用を自動計算できる。",
    "gaze": "来訪者は新製品の展示をじっと見つめ始めた。",
    "theoretical": "研修は理論知識と実務を結びつけている。",
    "fragment": "技術者は機械の中に金属片を見つけた。",
    "immigration": "会社は新入社員に入国手続きの情報を提供している。",
    "tender": "請負業者はオフィス改修の入札を提出した。",
    "density": "倉庫マネージャーは梱包資材の密度を確認した。",
    "module": "オンライン講座には顧客の苦情に関する単元がある。",
    "attachment": "会議前に添付ファイルを開いてください。",
    "dirty": "保守チームは汚れた空気フィルターを交換した。",
    "bread": "ホテルは朝食ビュッフェ用に焼きたてのパンを注文した。",
    "blind": "会社は目の不自由な来訪者を支援する触知案内を設置した。",
    "bloody": "看護師は診療所で血の付いた包帯を交換した。",
    "bend": "金属梁は過度な圧力で曲がる可能性がある。",
    "briefly": "取締役は予定変更の理由を簡潔に説明した。",
    "alarm": "荷積み場に煙が入ると警報が鳴った。",
    "flood": "洪水で倉庫へ続く道路が損傷した。",
    "crazy": "安全警告を無視するのは無謀だ。",
    "boot": "技術者はハードディスクを交換した後、コンピューターを起動する。",
    "accurate": "発送前に顧客の住所が正確か確認してください。",
    "dealer": "販売店は交換車両を割引価格で提供した。",
    "button": "緑のボタンを押して機械を起動してください。",
    "desert": "会社は砂漠に太陽光発電施設を建設した。",
    "bowl": "食堂は入口の近くに果物のボウルを置いた。",
    "discovery": "欠陥の発見により、費用のかかるリコールを防げた。",
    "bath": "ホテルは再開前にすべての浴室を改修した。",
    "criticize": "マネージャーは同僚を批判するより業務改善を促した。",
    "apologize": "仕入先は配送の遅れを謝罪した。",
    "grab": "顧客が来る前に正しいファイルを取ってください。",
    "digital": "会社は紙の使用を減らすためデジタル請求書を導入した。",
    "edit": "アシスタントは公開前に報告書を編集する。",
    "exact": "顧客は正確な納品時刻を求めた。",
    "dig": "建設作業員は新しいケーブル用の溝を掘る。",
    "drag": "承認が1つ欠けるだけで購買手続きが長引くことがある。",
    "angle": "プレゼンテーションは顧客の視点から問題を説明している。",
    "chicken": "レストランは昼食メニューにグリルチキンを加えた。",
    "admire": "チームは取締役の冷静なリーダーシップを称賛している。",
    "charity": "会社は地元の慈善団体に機器を寄付した。",
    "cigarette": "倉庫入口付近での喫煙は禁止されている。",
    "cousin": "彼女のいとこは国際物流会社に勤めている。",
    "eastern": "東支店は隣接する3か国の顧客に対応している。",
    "forecast": "財務チームは売上予測を更新した。",
    "custom": "メーカーは大量注文向けに特注包装を製造できる。",
    "adapt": "チームはリモート勤務者向けに研修資料を適応させた。",
    "cap": "会社は出張費に上限を設けた。",
    "charm": "ホテルは建物の歴史的な魅力を保っている。",
    "dialog": "ソフトウェアは支払いの確認を求めるダイアログを表示する。",
    "cream": "カフェはコーヒーメーカーの横にクリームと砂糖を用意している。",
    "cancel": "航空会社は悪天候のため便を欠航にする可能性がある。",
    "beneath": "非常口は中央階段の下にある。",
    "absolute": "契約は交渉中の完全な秘密保持を求めている。",
    "dare": "安全手順に疑問を呈す勇気のある従業員は少ない。",
    "divorce": "従業員は離婚手続きのため休暇を申請した。",
    "bury": "建設作業員は新しいケーブルを地下に埋める必要があった。",
    "frequent": "その支店は週末配送の依頼を頻繁に受ける。",
    "counter": "マネージャーは競合の割引に対抗する計画を提案した。",
    "float": "会社は最終決定をする前にその案をしばらく保留した。",
    "greatly": "改訂版の手順で顧客満足度が大幅に改善した。",
    "electric": "会社は配送車両に電気自動車を加えた。",
    "acceptable": "改訂された納品日は顧客にとって受け入れ可能だ。",
    "coal": "工場は排出量を削減するため石炭の使用を減らしている。",
    "burst": "パイプが破裂して保守室が水浸しになった。",
    "buyer": "買い手は契約書に署名する前に機器を検査した。",
    "champion": "取締役は柔軟な勤務方針の擁護者だ。",
    "dust": "清掃チームは換気システムからほこりを取り除いた。",
}

JA = {
    "promotion": "彼女は売上目標を上回った後、昇進した。",
    "fulfill": "仕入先は購入契約の条件を履行しなければならない。",
    "dedicate": "会社は顧客サポートチームに追加の人員を専任させる。",
    "province": "会社は北部の州に配送センターを開設した。",
    "evaluation": "マネージャーは新入社員の業績評価を行った。",
    "compromise": "双方は配送スケジュールについて妥協点に達した。",
    "accomplish": "チームは四半期末までに目標を達成した。",
    "literary": "ホテルは地元の作家を招いた文学イベントを開催した。",
    "govern": "取締役会は社内規則に従って会社を統治している。",
    "embrace": "会社は全支店でデジタル決済を採用することにした。",
    "compensation": "従業員は承認された出張経費の補償を受けた。",
    "classical": "ホテルは正式な夕食会でクラシック音楽を流した。",
    "versus": "報告書はオンライン販売と店舗販売を比較している。",
    "deficit": "部署は今年、予算赤字を削減しなければならない。",
    "modify": "技術者は生産費を削減するため設計を修正した。",
    "literally": "指示には、訪問者は全員記帳しなければならないと文字どおり書かれている。",
    "equation": "アナリストは費用見積もりに使った方程式を確認した。",
    "gesture": "マネージャーは来訪した顧客に歓迎の身振りを示した。",
    "assign": "マネージャーは最も経験のある技術者に作業を割り当てた。",
    "inflation": "物価上昇により原材料費が増加した。",
    "historic": "会社は初の海外取引先と歴史的な合意に署名した。",
    "therapy": "会社は従業員支援制度を通じて治療の支援を提供している。",
    "personnel": "許可された職員だけが保管エリアに入れる。",
    "insight": "調査は顧客の好みについて貴重な洞察をもたらした。",
    "tackle": "新しいマネージャーはまず人員問題に取り組む予定だ。",
    "exceed": "製品は発売初月に売上予測を上回った。",
    "expenditure": "財務チームは来四半期の設備投資を確認した。",
    "fortune": "会社は老朽化した設備の更新に大金を費やした。",
    "ceremony": "会社は長年勤めた従業員を表彰する式典を開いた。",
    "automatically": "システムは支払い後に自動的に領収書を送る。",
    "scholar": "会社は貿易の歴史について学者を招いて講演してもらった。",
    "psychological": "研修では職場のストレスが及ぼす心理的影響を扱う。",
    "dramatically": "新しい手順で注文承認に必要な時間が大幅に短縮された。",
    "stake": "その投資家は会社の大きな利害関係を持っている。",
    "partnership": "提携により会社の配送ネットワークが拡大する。",
    "participation": "従業員は安全研修に参加しなければならない。",
    "clause": "契約書には延滞料金に関する条項がある。",
    "penalty": "仕入先は合意した締め切りに遅れると罰金を払う。",
    "chamber": "会議はコンベンションセンター最大の会議室で行われた。",
    "fancy": "顧客は来訪する役員のために凝った夕食を希望した。",
    "evolve": "サービスは顧客のニーズの変化に合わせて発展し続けている。",
    "boost": "そのキャンペーンは休暇シーズンの売上を押し上げるはずだ。",
    "abortion": "診療所は生殖に関する健康サービスについて秘密厳守で情報提供している。",
    "boom": "新空港の開港後、その地域では建設が急成長した。",
    "democratic": "委員会は議長を選ぶため民主的な手続きを用いた。",
    "maintenance": "定期的な保守が配送車両を安全で信頼できる状態に保つ。",
    "consequently": "仕入先が締め切りに遅れ、その結果、出荷も遅れた。",
    "strengthen": "会社はデータセキュリティの手順を強化した。",
    "constraint": "プロジェクトの主な制約は限られた予算だ。",
    "undergo": "機器は来週、安全検査を受ける。",
    "potentially": "新しいルートで配送時間が短縮される可能性がある。",
    "scope": "プロジェクトの範囲には研修、設置、フォローアップ支援が含まれる。",
    "diversity": "会社は職場の多様性を重視している。",
    "allege": "顧客は請求書に承認していない料金が含まれていると主張した。",
    "intense": "営業チームは海外市場で激しい競争に直面した。",
    "inquiry": "担当者は1営業日以内に問い合わせへ返答する。",
    "resign": "取締役は会計年度末に辞任することにした。",
    "craft": "職人は会社の賞を飾る展示ケースを製作した。",
    "concrete": "顧客は配送計画について具体的な詳細を求めた。",
    "distinct": "2つのブランドには明確な個性があり、対象顧客も異なる。",
    "limitation": "報告書は現在のソフトウェアの限界を説明している。",
    "indication": "リピート注文の増加は顧客満足度の兆候だ。",
    "stability": "新しい契約は地域オフィスに安定性をもたらす。",
    "neglect": "会社は定期的な安全点検を怠ってはいけない。",
    "compose": "アシスタントは仕入先への短いメールを作成した。",
    "mere": "その遅れは単なる不便ではなく、生産に影響した。",
    "regulate": "当局は危険物の輸送を規制している。",
    "trigger": "発表がオンライン注文の急増を引き起こした。",
    "destruction": "嵐で複数の保管施設が破壊された。",
    "mystery": "技術者はシステム障害が繰り返される謎を解いた。",
    "rear": "裏口は配送専用だ。",
    "presumably": "荷物はおそらく誤った支店へ送られた。",
    "amendment": "弁護士はサービス契約の修正案を作成した。",
    "civilian": "緊急計画は民間の来訪者を守る方法を説明している。",
    "composition": "マネージャーはプロジェクトチームの構成を確認した。",
    "regardless": "サービスは天候にかかわらず運営される。",
    "racial": "会社は職場での人種差別を禁じている。",
    "sanction": "施設は規制当局の認可なしには開業できない。",
    "stimulate": "減税は地域企業への投資を促進する可能性がある。",
    "narrative": "年次報告書は会社の成長を明確に説明している。",
    "tissue": "診療所は厳格な安全規則に従って組織サンプルを保管する。",
    "barely": "その支店は今四半期、かろうじて売上目標を達成した。",
    "tourism": "観光業は沿岸地域の多くの企業を支えている。",
    "motivation": "ボーナスが目標達成への従業員の意欲を高めた。",
    "firmly": "箱を封じる間、荷物をしっかり押さえてください。",
    "interior": "請負業者は受付エリアの内装を改修した。",
    "immigrant": "会社は移民の従業員に語学支援を提供している。",
    "excess": "倉庫は余剰在庫を仕入先に返送した。",
    "complexity": "コンサルタントは新しい税規則の複雑さを説明した。",
    "liability": "契約書は破損品に対する仕入先の法的責任を定めている。",
    "extract": "アナリストはデータベースから売上数値を抽出した。",
    "implementation": "新方針の実施は来月始まる。",
    "bias": "採用委員会は無意識の偏見を減らす研修を受けた。",
    "continuous": "工場では温度を継続的に監視する必要がある。",
    "guideline": "マニュアルは顧客の苦情に対応する指針を示している。",
    "biological": "研究室は生物学的試料について厳格な規則に従っている。",
    "consume": "新しい機器は旧モデルより電力消費が少ない。",
    "luxury": "ホテルは法人客向けに高級パッケージを提供している。",
    "anxious": "応募者は就職面接の前に不安を感じた。",
    "exhaust": "技術者は車両の排気システムを点検した。",
}

JA.update(JA_1101_1200)
JA.update(JA_1201_1300)

def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 2][1000:1300]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        source = EN[word]
        item["example"] = source
        example = translations.setdefault(f"builtin:{item['id']}", {}).setdefault("example", {})
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if example.get(field) != value:
                example[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 600+ English examples batch 5: {len(level_rows)} terms, {changed} fields")

if __name__ == "__main__":
    main()
