#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PHRASE_PATH=ROOT/"app/src/main/assets/vocabulary_phrase_translations.json"
L={
"zh":{"immunize":"诊所将为前往受影响地区的员工接种疫苗。","sociologist":"公司聘请社会学家研究职场沟通。","reassess":"检查后，经理将重新评估配送计划。","dictatorship":"博物馆展览介绍了独裁统治对当地企业的影响。","pandemic":"疫情后，公司修订了远程办公政策。","spontaneity":"研讨会鼓励在创意解决问题时发挥自发性。","inevitability":"报告讨论了施工期间部分延误的不可避免性。","completeness":"审计员检查了财务记录的完整性。","subtlety":"设计师在新的品牌色彩中运用了细腻感。","ecologist":"生态学家评估了项目对湿地的影响。","self-sustaining":"新设施的能源使用设计为自给自足。","nonrenewable":"公司正在减少对不可再生能源的使用。","immunization":"诊所保存所有员工的免疫接种记录。","rallying":"产品发布前，董事发表了鼓舞士气的讲话。","inoculate":"诊所将在运输前为牲畜接种疫苗。","metropolis":"公司在该地区的大都市开设了最大的办公室。"},
"hi":{"immunize":"क्लिनिक प्रभावित क्षेत्र की यात्रा करने वाले कर्मचारियों का टीकाकरण करेगा।","sociologist":"कंपनी ने कार्यस्थल संचार का अध्ययन करने के लिए समाजशास्त्री नियुक्त किया।","reassess":"निरीक्षण के बाद प्रबंधक डिलीवरी योजना का फिर से मूल्यांकन करेगा।","dictatorship":"संग्रहालय की प्रदर्शनी बताती है कि तानाशाही ने स्थानीय व्यवसायों को कैसे प्रभावित किया।","pandemic":"महामारी के बाद कंपनी ने दूरस्थ कार्य नीति में बदलाव किया।","spontaneity":"कार्यशाला रचनात्मक समस्या-समाधान में स्वाभाविकता को प्रोत्साहित करती है।","inevitability":"रिपोर्ट निर्माण के दौरान कुछ देरी की अनिवार्यता पर चर्चा करती है।","completeness":"ऑडिटर ने वित्तीय रिकॉर्ड की पूर्णता जाँची।","subtlety":"डिज़ाइनर ने नए ब्रांड रंगों में सूक्ष्मता का उपयोग किया।","ecologist":"एक पारिस्थितिकीविद् ने आर्द्रभूमि पर परियोजना के प्रभाव की समीक्षा की।","self-sustaining":"नई सुविधा को ऊर्जा के मामले में आत्मनिर्भर बनाया गया है।","nonrenewable":"कंपनी गैर-नवीकरणीय ऊर्जा का उपयोग कम कर रही है।","immunization":"क्लिनिक सभी कर्मचारियों के टीकाकरण रिकॉर्ड रखता है।","rallying":"उत्पाद लॉन्च से पहले निदेशक ने उत्साहवर्धक भाषण दिया।","inoculate":"क्लिनिक परिवहन से पहले पशुओं का टीकाकरण करेगा।","metropolis":"कंपनी ने क्षेत्र के महानगर में अपना सबसे बड़ा कार्यालय खोला।"},
"vi":{"immunize":"Phòng khám sẽ tiêm chủng cho nhân viên đi đến khu vực bị ảnh hưởng.","sociologist":"Công ty thuê một nhà xã hội học nghiên cứu giao tiếp nơi làm việc.","reassess":"Quản lý sẽ đánh giá lại kế hoạch giao hàng sau cuộc kiểm tra.","dictatorship":"Triển lãm giải thích chế độ độc tài đã ảnh hưởng đến doanh nghiệp địa phương thế nào.","pandemic":"Sau đại dịch, công ty sửa đổi chính sách làm việc từ xa.","spontaneity":"Hội thảo khuyến khích sự tự phát khi giải quyết vấn đề sáng tạo.","inevitability":"Báo cáo thảo luận tính không thể tránh khỏi của một số trì hoãn trong xây dựng.","completeness":"Kiểm toán viên kiểm tra tính đầy đủ của hồ sơ tài chính.","subtlety":"Nhà thiết kế sử dụng sự tinh tế trong màu sắc thương hiệu mới.","ecologist":"Một nhà sinh thái học xem xét tác động của dự án lên vùng đất ngập nước.","self-sustaining":"Cơ sở mới được thiết kế để tự chủ về năng lượng.","nonrenewable":"Công ty đang giảm sử dụng năng lượng không tái tạo.","immunization":"Phòng khám lưu hồ sơ tiêm chủng của mọi nhân viên.","rallying":"Giám đốc phát biểu khích lệ trước khi ra mắt sản phẩm.","inoculate":"Phòng khám sẽ tiêm phòng cho gia súc trước khi vận chuyển.","metropolis":"Công ty mở văn phòng lớn nhất tại đô thị của khu vực."},
"ko":{"immunize":"클리닉은 해당 지역으로 여행하는 직원들에게 예방 접종을 실시할 예정이다.","sociologist":"회사는 직장 내 의사소통을 연구하기 위해 사회학자를 고용했다.","reassess":"관리자는 검사 후 배송 계획을 재평가할 예정이다.","dictatorship":"박물관 전시는 독재 정권이 지역 기업에 미친 영향을 설명한다.","pandemic":"회사는 팬데믹 이후 재택근무 정책을 수정했다.","spontaneity":"워크숍은 창의적인 문제 해결에서 자발성을 장려한다.","inevitability":"보고서는 건설 중 일부 지연의 불가피성을 다룬다.","completeness":"감사자는 재무 기록의 완전성을 확인했다.","subtlety":"디자이너는 새 브랜드 색상에 섬세함을 더했다.","ecologist":"생태학자가 프로젝트가 습지에 미치는 영향을 검토했다.","self-sustaining":"새 시설은 에너지 면에서 자립하도록 설계되었다.","nonrenewable":"회사는 재생 불가능한 에너지 사용을 줄이고 있다.","immunization":"클리닉은 모든 직원의 예방 접종 기록을 보관한다.","rallying":"이사는 제품 출시 전에 사기를 북돋는 연설을 했다.","inoculate":"클리닉은 운송 전에 가축에 예방 접종을 할 예정이다.","metropolis":"회사는 이 지역의 대도시에 가장 큰 사무실을 열었다."},
"id":{"immunize":"Klinik akan memvaksinasi karyawan yang bepergian ke wilayah terdampak.","sociologist":"Perusahaan mempekerjakan sosiolog untuk mempelajari komunikasi di tempat kerja.","reassess":"Manajer akan menilai ulang rencana pengiriman setelah pemeriksaan.","dictatorship":"Pameran museum menjelaskan dampak kediktatoran terhadap bisnis setempat.","pandemic":"Setelah pandemi, perusahaan merevisi kebijakan kerja jarak jauh.","spontaneity":"Lokakarya mendorong spontanitas dalam pemecahan masalah kreatif.","inevitability":"Laporan membahas tidak terhindarkannya beberapa penundaan selama pembangunan.","completeness":"Auditor memeriksa kelengkapan catatan keuangan.","subtlety":"Desainer menggunakan kehalusan dalam warna merek yang baru.","ecologist":"Ahli ekologi meninjau dampak proyek terhadap lahan basah.","self-sustaining":"Fasilitas baru dirancang agar mandiri dalam penggunaan energi.","nonrenewable":"Perusahaan sedang mengurangi penggunaan energi tak terbarukan.","immunization":"Klinik menyimpan catatan imunisasi semua karyawan.","rallying":"Direktur menyampaikan pidato penyemangat sebelum peluncuran produk.","inoculate":"Klinik akan memvaksinasi ternak sebelum pengangkutan.","metropolis":"Perusahaan membuka kantor terbesarnya di kota metropolitan tersebut."},
"th":{"immunize":"คลินิกจะฉีดวัคซีนให้พนักงานที่เดินทางไปยังพื้นที่ที่ได้รับผลกระทบ","sociologist":"บริษัทจ้างนักสังคมวิทยาเพื่อศึกษาการสื่อสารในที่ทำงาน","reassess":"ผู้จัดการจะประเมินแผนการจัดส่งใหม่หลังการตรวจสอบ","dictatorship":"นิทรรศการอธิบายว่าระบอบเผด็จการส่งผลต่อธุรกิจท้องถิ่นอย่างไร","pandemic":"บริษัทปรับนโยบายการทำงานระยะไกลหลังการระบาดใหญ่","spontaneity":"เวิร์กช็อปส่งเสริมความเป็นธรรมชาติในการแก้ปัญหาเชิงสร้างสรรค์","inevitability":"รายงานกล่าวถึงความหลีกเลี่ยงไม่ได้ของความล่าช้าบางส่วนระหว่างการก่อสร้าง","completeness":"ผู้ตรวจสอบตรวจสอบความครบถ้วนของบันทึกทางการเงิน","subtlety":"นักออกแบบใช้ความละเอียดอ่อนในสีแบรนด์ใหม่","ecologist":"นักนิเวศวิทยาตรวจสอบผลกระทบของโครงการต่อพื้นที่ชุ่มน้ำ","self-sustaining":"อาคารแห่งใหม่ออกแบบให้พึ่งพาตนเองด้านพลังงาน","nonrenewable":"บริษัทกำลังลดการใช้พลังงานที่ไม่หมุนเวียน","immunization":"คลินิกเก็บบันทึกการฉีดวัคซีนของพนักงานทุกคน","rallying":"ผู้อำนวยการกล่าวสุนทรพจน์สร้างกำลังใจก่อนเปิดตัวสินค้า","inoculate":"คลินิกจะฉีดวัคซีนให้ปศุสัตว์ก่อนขนส่ง","metropolis":"บริษัทเปิดสำนักงานที่ใหญ่ที่สุดในมหานครของภูมิภาค"},
"es":{"immunize":"La clínica vacunará a los empleados que viajen a la zona afectada.","sociologist":"La empresa contrató a un sociólogo para estudiar la comunicación laboral.","reassess":"El gerente reevaluará el plan de entrega después de la inspección.","dictatorship":"La exposición explica cómo la dictadura afectó a las empresas locales.","pandemic":"La empresa revisó su política de trabajo remoto después de la pandemia.","spontaneity":"El taller fomenta la espontaneidad al resolver problemas creativos.","inevitability":"El informe analiza la inevitabilidad de algunos retrasos durante la construcción.","completeness":"El auditor comprobó la integridad de los registros financieros.","subtlety":"El diseñador empleó sutileza en los nuevos colores de la marca.","ecologist":"Un ecólogo revisó el impacto del proyecto en los humedales.","self-sustaining":"La nueva instalación está diseñada para ser autosuficiente en energía.","nonrenewable":"La empresa está reduciendo el uso de energía no renovable.","immunization":"La clínica conserva los registros de vacunación de todos los empleados.","rallying":"El director pronunció un discurso motivador antes del lanzamiento.","inoculate":"La clínica vacunará al ganado antes del transporte.","metropolis":"La empresa abrió su oficina más grande en la metrópoli de la región."}}
def main():
    p=json.loads(PHRASE_PATH.read_text(encoding='utf-8')); t=p.setdefault('translations',{}); v=json.load(open(ROOT/'app/src/main/assets/vocabulary.json')); rows=[x for x in v if int(x.get('level',0))==4][:16]; expected={x['word'] for x in rows}; assert all(expected <= set(d) for d in L.values())
    for x in rows:
        ex=t.setdefault(f"builtin:{x['id']}",{}).setdefault('example',{})
        for lang,d in L.items(): ex[lang]=d[x['word']]
    PHRASE_PATH.write_text(json.dumps(p,ensure_ascii=False,indent=1)+'\n',encoding='utf-8'); print(f'added multilingual examples 800+ 1-16: {len(rows)} terms')
if __name__=='__main__': main()
