#!/usr/bin/env python3
"""Review 300 TOEIC 600+ examples (items 401-700) in English and Japanese."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"


EN = {
    "respond": "The customer service team will respond to the inquiry before the deadline.",
    "slow": "The slow approval process delayed the equipment order.",
    "regular": "The manager scheduled regular meetings with the regional offices.",
    "physical": "The warehouse requires a physical count of inventory each month.",
    "suit": "The dark suit is suitable for the client presentation.",
    "reveal": "The audit may reveal errors in the expense report.",
    "percentage": "The sales report shows a higher percentage of repeat customers.",
    "peace": "The agreement helped restore peace between the two business partners.",
    "status": "The administrator updated the status of the purchase order.",
    "warn": "The notice warns customers about possible delivery delays.",
    "partner": "Our business partner signed the revised agreement.",
    "spot": "The inspector found a damaged spot on the product packaging.",
    "reader": "The card reader stopped working at the reception desk.",
    "taxi": "The assistant booked a taxi for the visiting executive.",
    "pain": "The employee reported back pain after lifting the package.",
    "sector": "The report compares growth in the technology sector.",
    "mistake": "The clerk corrected a mistake on the invoice.",
    "satisfy": "The new service must satisfy the needs of our customers.",
    "wave": "The company expects a new wave of orders after the product launch.",
    "south": "The company opened a warehouse in the south of the country.",
    "surface": "The technician cleaned the surface before applying the label.",
    "procedure": "All employees must follow the safety procedure.",
    "struggle": "The small branch struggled to meet the quarterly sales target.",
    "select": "Please select a delivery option on the order form.",
    "surround": "Trees surround the hotel where the conference will be held.",
    "river": "The warehouse beside the river floods after heavy rain.",
    "roll": "Please roll the posters carefully before shipping them.",
    "reality": "The manager explained the reality of the current labor shortage.",
    "photograph": "Please attach a photograph of the damaged item to the claim.",
    "presence": "The director's presence helped reassure the new client.",
    "shift": "The factory added a night shift to meet demand.",
    "net": "The net price includes the seasonal discount.",
    "secretary": "The secretary arranged the director's appointments.",
    "quick": "The support team gave the customer a quick response.",
    "spread": "The company plans to spread the new procedure across all branches.",
    "nuclear": "The supplier must meet strict standards for the nuclear facility.",
    "scale": "The company plans to scale production next year.",
    "requirement": "A valid identification card is a requirement for visitors.",
    "north": "The company operates three distribution centers in the north.",
    "senior": "A senior manager approved the revised hiring plan.",
    "photo": "The application requires a recent photo of each applicant.",
    "refuse": "The carrier may refuse the shipment if the package is unsafe.",
    "transport": "The logistics team arranged transport from the port to the warehouse.",
    "map": "The delivery driver checked the map before leaving the depot.",
    "reform": "The company introduced reforms to improve workplace safety.",
    "neither": "Neither proposal included a realistic delivery schedule.",
    "survive": "The new branch must control costs to survive its first year.",
    "solve": "The technician solved the network problem before the meeting.",
    "neighbor": "The neighboring business agreed to share the parking area.",
    "technique": "The trainer demonstrated a technique for handling complaints.",
    "traffic": "Heavy traffic delayed the courier's arrival.",
    "tool": "The technician selected the right tool for the repair.",
    "smoke": "The safety officer reported smoke near the loading area.",
    "reaction": "The marketing team measured customer reaction to the new advertisement.",
    "rain": "The delivery was delayed because of heavy rain.",
    "lesson": "The safety lesson is required for all new employees.",
    "mass": "The factory can produce a mass of orders during the holiday season.",
    "schedule": "The assistant updated the delivery schedule this morning.",
    "speaker": "The guest speaker will discuss customer retention at the conference.",
    "mountain": "The resort hired a company to maintain the mountain road.",
    "waste": "The cafeteria reduced food waste by donating unused meals.",
    "marriage": "The employee requested leave for her marriage ceremony.",
    "ticket": "The assistant booked a train ticket for the business trip.",
    "meal": "The hotel provides a meal for conference participants.",
    "repeat": "Please repeat the order number so I can confirm it.",
    "plus": "The package includes installation plus one year of support.",
    "owner": "The store owner approved the renovation plan.",
    "plane": "The executive took a plane to the overseas branch.",
    "strength": "The proposal highlights the strength of our customer support team.",
    "scheme": "The finance department rejected the payment scheme.",
    "payment": "Payment is due within thirty days of the invoice date.",
    "unfortunately": "Unfortunately, the supplier cannot meet the original deadline.",
    "secret": "The agreement requires employees to keep the pricing information secret.",
    "novel": "The company developed a novel approach to reducing delivery costs.",
    "union": "The union and management reached an agreement on working hours.",
    "trend": "The latest trend is toward shorter and more flexible work schedules.",
    "pleasure": "It was a pleasure to meet the new distributor.",
    "suggestion": "The manager accepted my suggestion to simplify the form.",
    "mostly": "The audience was mostly made up of local business owners.",
    "pop": "The company used pop music in its summer advertisement.",
    "promote": "The campaign will promote the company's new delivery service.",
    "path": "The training program provides a clear path to promotion.",
    "topic": "The main topic of the meeting was next quarter's budget.",
    "powerful": "The new software is a powerful tool for analyzing sales data.",
    "settle": "The two companies settled the dispute without going to court.",
    "twice": "The safety equipment is inspected twice a year.",
    "safety": "Employee safety is the company's highest priority.",
    "quiet": "The team reserved a quiet room for the negotiations.",
    "nurse": "The nurse checked the employee's condition at the workplace clinic.",
    "package": "The carrier delivered the package to the correct department.",
    "somewhere": "The missing contract must be stored somewhere in the archive.",
    "obvious": "It was obvious that the quotation did not include shipping costs.",
    "weapon": "The security team found a weapon in a visitor's bag.",
    "relatively": "The new process is relatively easy to implement.",
    "winter": "The company orders extra heating fuel before winter.",
    "tire": "The office shuttle stopped because it had a flat tire.",
    "spring": "The company plans to launch the service in spring.",
    "spirit": "The team showed a strong spirit of cooperation during the project.",
    "pool": "The company created a pool of candidates for future openings.",
    "tradition": "The company has a tradition of recognizing long-serving employees.",
    "experiment": "The engineering team ran an experiment on the new material.",
    "strange": "The technician noticed a strange sound from the new machine.",
    "possibly": "The shipment may possibly arrive one day early.",
    "threat": "The report identifies cyberattacks as a serious threat to the company.",
    "revenue": "The company reported higher revenue in the third quarter.",
    "religious": "The company respects religious holidays when planning the work schedule.",
    "vary": "Delivery times vary depending on the destination.",
    "sun": "The solar panels produce more power when the sun is strong.",
    "volume": "The warehouse manager checked the volume of the shipment.",
    "proceed": "The negotiations may proceed after both sides review the contract.",
    "wash": "Please wash the reusable containers before returning them.",
    "tape": "Use packing tape to seal the box securely.",
    "whereas": "The old model is inexpensive, whereas the new model uses less energy.",
    "opposite": "The loading dock is on the opposite side of the building.",
    "stone": "The contractor ordered stone for the entrance renovation.",
    "sum": "The invoice shows the sum due for the completed work.",
    "murder": "The security company reviewed the report after the murder near the facility.",
    "monitor": "The IT team will monitor the system before the deadline.",
    "soldier": "The company donated supplies to soldiers stationed overseas.",
    "shock": "The sudden resignation came as a shock to the entire team.",
    "usual": "The supplier delivered the order later than usual.",
    "pack": "Please pack the samples separately from the documents.",
    "recall": "The manufacturer issued a recall for the defective product.",
    "wine": "The restaurant ordered wine for the client's dinner.",
    "swim": "The hotel has a pool where guests can swim after the conference.",
    "manufacture": "The factory manufactures parts for medical equipment.",
    "theater": "The company rented a theater for the annual awards ceremony.",
    "totally": "The revised plan is totally different from the original proposal.",
    "museum": "The tour operator arranged a visit to the museum for the guests.",
    "visitor": "Every visitor must sign in at the reception desk.",
    "objective": "The main objective of the project is to reduce delivery times.",
    "moreover": "The proposal is affordable; moreover, it can be implemented quickly.",
    "onto": "The technician placed the replacement part onto the workbench.",
    "oppose": "Several board members oppose the proposed increase in fees.",
    "vehicle": "The company added an electric vehicle to its delivery fleet.",
    "scientist": "The company hired a scientist to develop a safer product.",
    "route": "The driver changed the delivery route because of roadwork.",
    "taste": "The restaurant asked customers to rate the taste of the new menu.",
    "tonight": "The visiting executives will attend a dinner tonight.",
    "normally": "The branch normally receives its supplies on Monday.",
    "sight": "The hotel has a clear sight of the harbor.",
    "quote": "The supplier sent a quote for the replacement equipment.",
    "violence": "The company has a policy against violence in the workplace.",
    "minister": "The minister visited the factory during the trade delegation.",
    "mouth": "The technician cleaned the mouth of the storage tank.",
    "noise": "The factory installed insulation to reduce machine noise.",
    "square": "The office has a floor area of five hundred square meters.",
    "occasion": "The company prepared a special event for the occasion.",
    "temperature": "The warehouse maintains a stable temperature for the products.",
    "troop": "The company supplied equipment to the troop during the emergency.",
    "technical": "The customer needs technical support with the installation.",
    "remind": "Please remind the supplier about Friday's delivery.",
    "skin": "The safety gloves protect workers' skin from the cleaning solution.",
    "prison": "The contractor completed the security upgrade at the prison.",
    "switch": "The engineering department will switch to digital manuals next quarter.",
    "wood": "The furniture company sources wood from certified suppliers.",
    "participate": "Employees may participate in the customer-service workshop.",
    "tough": "The team faced tough negotiations over the contract terms.",
    "tear": "Please do not tear the shipping label when opening the package.",
    "representative": "A sales representative will visit the client next week.",
    "shake": "Please shake the container before using the cleaning solution.",
    "shoe": "The warehouse requires closed-toe shoes for safety reasons.",
    "ought": "The supplier ought to notify us before changing the delivery date.",
    "regulation": "The factory must comply with the latest safety regulation.",
    "studio": "The design studio prepared the images for the new catalog.",
    "proper": "Please use the proper form when requesting reimbursement.",
    "relax": "The hotel provides a lounge where conference guests can relax.",
    "tourist": "The hotel offers a shuttle service for tourists and business travelers.",
    "suspect": "The auditor suspects that the invoice was submitted twice.",
    "perspective": "The consultant offered a new perspective on the sales strategy.",
    "register": "Please register for the safety workshop by Friday.",
    "signal": "The warning signal appeared before the machine stopped.",
    "relevant": "Please include only relevant information in the proposal.",
    "wake": "The alarm will wake the night-shift worker at six o'clock.",
    "necessarily": "A higher price does not necessarily mean better quality.",
    "slowly": "The loading gate opened slowly because of the cold weather.",
    "tie": "The contract ties payment to the successful completion of the work.",
    "victim": "The company offered support to the victim of the workplace accident.",
    "threaten": "The supplier threatened to cancel the contract over the unpaid invoice.",
    "secure": "Please secure the boxes before the truck leaves.",
    "root": "The manager investigated the root cause of the delay.",
    "recommendation": "The consultant's recommendation improved the hiring process.",
    "rank": "The product ranked first in the customer satisfaction survey.",
    "typical": "A typical customer places an order through the website.",
    "west": "The company opened a branch in the west of the country.",
    "resident": "Local residents received a notice about the construction work.",
    "provision": "The contract includes a provision for late deliveries.",
    "plenty": "There is plenty of time to review the proposal before the meeting.",
    "strongly": "I strongly recommend confirming the booking today.",
    "moral": "The ethics committee discussed the moral responsibilities of the company.",
    "principal": "The principal reason for the delay was a shortage of materials.",
    "master": "The technician hopes to master the new inventory system this month.",
    "session": "The training session will begin at nine o'clock.",
    "nevertheless": "The delivery was delayed; nevertheless, the client accepted it.",
    "predict": "Analysts predict that demand will increase next quarter.",
    "previously": "The software had previously been used by the finance department.",
    "protection": "The company added extra protection for customer data.",
    "wed": "The employee will wed in October and take two weeks off.",
    "rent": "The branch pays rent for its office near the station.",
    "shot": "The marketing team shot a video for the new product.",
    "reasonable": "The client considered the revised price reasonable.",
    "till": "The office will remain open till six o'clock.",
    "theme": "The theme of the conference is sustainable business.",
    "odd": "The technician noticed an odd error in the payment system.",
    "rely": "The branch relies on the central warehouse for supplies.",
    "narrow": "The delivery truck could not enter the narrow street.",
    "succeed": "The project will succeed if every department meets its deadline.",
    "permit": "The city issued a permit for the warehouse expansion.",
    "seriously": "The manager takes every customer complaint seriously.",
    "wild": "The resort protects wild birds that nest near the property.",
    "unique": "The product has a unique design that appeals to younger customers.",
    "practical": "The consultant proposed a practical solution to the staffing problem.",
    "tea": "The hotel provides coffee and tea in the meeting room.",
    "soft": "The company ordered soft lighting for the reception area.",
    "row": "The new desks are arranged in a row near the window.",
    "youth": "The company supports a training program for local youth.",
    "sexual": "The company has a strict policy against sexual harassment.",
    "shoulder": "The workplace clinic treated Maya after she injured her shoulder.",
    "ourselves": "We introduced ourselves to the new client at the meeting.",
    "sheet": "Each new employee received a sheet explaining the training schedule.",
    "notion": "The manager rejected the notion that lower prices always increase sales.",
    "opposition": "The proposal faced opposition from several department heads.",
    "relief": "The new schedule brought relief to employees with long commutes.",
    "outcome": "The manager explained the expected outcome of the negotiations.",
    "musical": "The hotel hired a musical group for the company event.",
    "recover": "Sales may recover after the system is updated.",
    "stretch": "The team will stretch the training program over two weeks.",
    "retire": "The director plans to retire at the end of the year.",
    "tiny": "The technician found a tiny crack in the package.",
    "suitable": "The conference room is suitable for a meeting of ten people.",
    "native": "The guide explained which plants are native to the region.",
    "witness": "The witness provided a statement to the safety officer.",
    "terrible": "The storm caused terrible damage to the warehouse roof.",
    "researcher": "The company hired a researcher to analyze customer data.",
    "ordinary": "The replacement part looks ordinary but meets the required standard.",
    "selection": "The store offers a wide selection of office supplies.",
    "mental": "The company provides support for employees' mental health.",
    "participant": "Each participant completed a short survey after the workshop.",
    "vision": "The president shared the company's vision for the next five years.",
    "personality": "Her friendly personality helps her build relationships with clients.",
    "specifically": "The contract specifically identifies who pays the shipping fee.",
    "tip": "The trainer gave us a useful tip for handling difficult calls.",
    "peak": "The store hires extra staff during the peak shopping season.",
    "proportion": "A large proportion of orders now arrive through the website.",
    "shout": "Employees should not shout at customers or coworkers.",
    "yard": "The shipping containers are stored in the yard behind the factory.",
    "significantly": "The new process significantly reduced processing time.",
    "surely": "Surely the supplier can provide a revised quote today.",
    "somewhat": "The revised schedule is somewhat shorter than the original.",
    "presentation": "The sales manager gave a presentation on the revised strategy.",
    "poll": "The company conducted a poll about employees' preferred benefits.",
    "weak": "The audit found a weak control over expense approvals.",
    "reduction": "The reduction in shipping costs improved the profit margin.",
    "reserve": "Please reserve a meeting room for the visiting clients.",
    "mission": "The company's mission is to make delivery more reliable.",
    "somehow": "Somehow, the package arrived without a delivery label.",
    "tone": "The manager used a respectful tone in the customer email.",
    "neighborhood": "The supervisor helped new employees find a quiet neighborhood near the office.",
    "passenger": "Each passenger must show identification before boarding.",
    "phase": "The project has entered the final phase of testing.",
    "thin": "The thin protective film prevents scratches on the screen.",
    "rush": "Please do not rush the inspection process.",
    "religion": "The company respects every employee's religion and beliefs.",
    "reject": "The purchasing manager rejected the damaged shipment.",
    "plate": "The technician replaced the metal plate inside the machine.",
    "steal": "The security cameras help prevent visitors from stealing equipment.",
    "protest": "Several employees organized a protest against the policy change.",
    "sad": "The team was sad to hear that the branch would close.",
    "sick": "Employees who feel sick should inform their supervisor.",
    "unable": "The carrier was unable to deliver the package on time.",
    "sky": "The aircraft could not take off because the sky was stormy.",
    "properly": "Please label each box properly before loading the truck.",
    "multiple": "The customer submitted multiple requests through the website.",
    "yield": "The new process should yield better results next quarter.",
    "via": "The invoice was sent via email to the accounting department.",
    "unlike": "Unlike the old model, the new printer uses less ink.",
    "mobile": "The sales team uses a mobile app to update orders.",
    "acknowledge": "The operations team will acknowledge the customer's complaint today.",
    "reward": "The company gave her a reward for excellent customer service.",
    "academic": "The company offers academic support to employees pursuing professional qualifications.",
    "voter": "The city sent every registered voter information about the public meeting.",
    "meanwhile": "The repair will take two days; meanwhile, we will use a spare machine.",
    "scientific": "The team used a scientific method to test the new material.",
    "wage": "The union asked the company to raise the minimum wage.",
    "remark": "The client made a helpful remark about the proposed layout.",
    "medicine": "The clinic recorded the medicine in the patient's medical file.",
    "rare": "It is rare for the supplier to miss a confirmed delivery date.",
    "settlement": "The two companies reached a settlement after weeks of negotiation.",
    "widely": "The new payment system is widely used by local retailers.",
    "minimum": "The order must meet the minimum quantity for free delivery.",
    "northern": "The company operates several stores in the northern region.",
    "shut": "The factory will shut for maintenance next Monday.",
    "victory": "Winning the contract was a major victory for the sales team.",
    "resolve": "The team will resolve the issue before the deadline.",
    "variable": "Delivery time is a variable that affects the total cost.",
    "sweet": "The bakery prepared a sweet gift for the visiting clients.",
    "permanent": "The company offered her a permanent position after the trial period.",
    "pursue": "The employee plans to pursue a professional certification.",
    "tall": "The warehouse has tall shelves for storing large cartons.",
    "urge": "The manager urged employees to submit their reports on time.",
}


JA = {
    "respond": "顧客サービスチームは締め切り前に問い合わせに対応する。",
    "slow": "承認手続きの遅さが機器の注文を遅らせた。",
    "regular": "マネージャーは地域オフィスとの定例会議を設定した。",
    "physical": "倉庫では毎月、在庫の実数を確認する必要がある。",
    "suit": "その濃い色のスーツは顧客とのプレゼンテーションに適している。",
    "reveal": "監査で経費報告書の誤りが明らかになる可能性がある。",
    "percentage": "売上報告書はリピーターの割合が高まったことを示している。",
    "peace": "その合意は2社の取引先の間に平穏を取り戻すのに役立った。",
    "status": "管理者は発注書の状況を更新した。",
    "warn": "その通知は配送が遅れる可能性を顧客に警告している。",
    "partner": "当社の取引先は改訂版の契約書に署名した。",
    "spot": "検査員は製品の包装に傷のある箇所を見つけた。",
    "reader": "受付のカード読み取り機が動かなくなった。",
    "taxi": "アシスタントは来訪する役員のためにタクシーを予約した。",
    "pain": "従業員は荷物を持ち上げた後、背中の痛みを訴えた。",
    "sector": "報告書はテクノロジー部門の成長を比較している。",
    "mistake": "事務員は請求書の誤りを修正した。",
    "satisfy": "新しいサービスは顧客のニーズを満たさなければならない。",
    "wave": "製品発売後、注文の新たな波が来ると会社は見込んでいる。",
    "south": "会社は国の南部に倉庫を開設した。",
    "surface": "技術者はラベルを貼る前に表面を清掃した。",
    "procedure": "全従業員は安全手順に従わなければならない。",
    "struggle": "小さな支店は四半期の売上目標の達成に苦戦した。",
    "select": "注文フォームで配送方法を選択してください。",
    "surround": "会議が開かれるホテルは木々に囲まれている。",
    "river": "川沿いの倉庫は大雨の後に浸水する。",
    "roll": "ポスターは発送前に慎重に丸めてください。",
    "reality": "マネージャーは現在の人手不足の実情を説明した。",
    "photograph": "損害請求には破損品の写真を添付してください。",
    "presence": "取締役の出席が新しい顧客を安心させた。",
    "shift": "工場は需要に応えるため夜勤を追加した。",
    "net": "正味価格には季節割引が含まれている。",
    "secretary": "秘書は取締役の予定を調整した。",
    "quick": "サポートチームは顧客にすぐ返答した。",
    "spread": "会社は新しい手順を全支店に広げる予定だ。",
    "nuclear": "仕入先は原子力施設向けの厳格な基準を満たさなければならない。",
    "scale": "会社は来年、生産規模を拡大する予定だ。",
    "requirement": "訪問者には有効な身分証明書が必要だ。",
    "north": "会社は北部で3つの配送センターを運営している。",
    "senior": "上級マネージャーが改訂版の採用計画を承認した。",
    "photo": "応募者は最近撮影した写真を提出する必要がある。",
    "refuse": "運送会社は荷物が安全でなければ発送を拒否することがある。",
    "transport": "物流チームは港から倉庫までの輸送を手配した。",
    "map": "配送担当者は出発前に地図を確認した。",
    "reform": "会社は職場の安全を改善する改革を導入した。",
    "neither": "どちらの提案にも現実的な納品スケジュールが含まれていなかった。",
    "survive": "新しい支店は初年度を乗り切るために経費を管理しなければならない。",
    "solve": "技術者は会議前にネットワークの問題を解決した。",
    "neighbor": "隣の会社は駐車場を共有することに同意した。",
    "technique": "研修担当者は苦情に対応する方法を実演した。",
    "traffic": "交通渋滞で宅配便の到着が遅れた。",
    "tool": "技術者は修理に適した工具を選んだ。",
    "smoke": "安全担当者は荷積み場の近くで煙を報告した。",
    "reaction": "マーケティングチームは新しい広告への顧客の反応を測定した。",
    "rain": "大雨のため配送が遅れた。",
    "lesson": "安全研修は全新入社員に必須だ。",
    "mass": "工場は休暇シーズンに大量の注文を生産できる。",
    "schedule": "アシスタントは今朝、配送予定を更新した。",
    "speaker": "招待講演者は会議で顧客維持について話す。",
    "mountain": "リゾートは山道の整備を会社に依頼した。",
    "waste": "食堂は余った食事を施設に寄付して食品廃棄を減らした。",
    "marriage": "従業員は結婚式のため休暇を申請した。",
    "ticket": "アシスタントは出張用の列車の切符を予約した。",
    "meal": "ホテルは会議参加者に食事を提供する。",
    "repeat": "確認できるよう注文番号を繰り返してください。",
    "plus": "そのパッケージには設置と1年間のサポートが含まれる。",
    "owner": "店主は改装計画を承認した。",
    "plane": "役員は海外支店へ飛行機で向かった。",
    "strength": "提案書は顧客サポートチームの強みを強調している。",
    "scheme": "財務部はその支払い計画を却下した。",
    "payment": "支払い期限は請求書の日付から30日以内だ。",
    "unfortunately": "残念ながら、仕入先は当初の締め切りを守れない。",
    "secret": "契約では従業員に価格情報を秘密にするよう求めている。",
    "novel": "会社は配送費を削減する新しい方法を開発した。",
    "union": "労働組合と経営陣は勤務時間について合意に達した。",
    "trend": "最近の傾向は、より短く柔軟な勤務時間へ向かっている。",
    "pleasure": "新しい販売代理店にお会いできて光栄です。",
    "suggestion": "マネージャーはフォームを簡素化するという私の提案を受け入れた。",
    "mostly": "聴衆の大半は地元の事業主だった。",
    "pop": "会社は夏の広告にポップ音楽を使った。",
    "promote": "そのキャンペーンは会社の新しい配送サービスを宣伝する。",
    "path": "研修プログラムは昇進への明確な道筋を示す。",
    "topic": "会議の主な話題は来四半期の予算だった。",
    "powerful": "新しいソフトウェアは売上データの分析に強力なツールだ。",
    "settle": "2社は裁判に進まずに紛争を解決した。",
    "twice": "安全設備は年に2回点検される。",
    "safety": "従業員の安全は会社の最優先事項だ。",
    "quiet": "チームは交渉のため静かな部屋を予約した。",
    "nurse": "看護師は職場の診療所で従業員の状態を確認した。",
    "package": "運送会社は荷物を正しい部署に届けた。",
    "somewhere": "紛失した契約書は書庫のどこかに保管されているはずだ。",
    "obvious": "見積書に送料が含まれていないことは明らかだった。",
    "weapon": "警備チームは来訪者のかばんから武器を見つけた。",
    "relatively": "新しい手順は比較的簡単に導入できる。",
    "winter": "会社は冬に備えて暖房燃料を追加注文する。",
    "tire": "オフィスの送迎車はタイヤがパンクして止まった。",
    "spring": "会社は春にサービスを開始する予定だ。",
    "spirit": "チームはプロジェクト中、強い協力の精神を示した。",
    "pool": "会社は将来の求人に備えて候補者の人材プールを作った。",
    "tradition": "会社には長年勤めた従業員を表彰する伝統がある。",
    "experiment": "技術チームは新素材について実験を行った。",
    "strange": "技術者は新しい機械から奇妙な音がすることに気づいた。",
    "possibly": "出荷品は予定より1日早く到着する可能性がある。",
    "threat": "報告書はサイバー攻撃を会社への深刻な脅威として特定している。",
    "revenue": "会社は第3四半期の収益が増加したと報告した。",
    "religious": "会社は勤務予定を立てる際、宗教上の祝日を尊重している。",
    "vary": "配送時間は宛先によって異なる。",
    "sun": "太陽が強く照ると太陽光パネルはより多くの電力を生む。",
    "volume": "倉庫マネージャーは出荷品の容積を確認した。",
    "proceed": "双方が契約書を確認した後、交渉を続けることができる。",
    "wash": "再利用する容器は返却前に洗ってください。",
    "tape": "箱をしっかり封じるために梱包テープを使ってください。",
    "whereas": "旧モデルは安価である一方、新モデルは消費電力が少ない。",
    "opposite": "荷積み場は建物の反対側にある。",
    "stone": "請負業者は入口の改修用に石材を注文した。",
    "sum": "請求書には完了した作業の支払総額が記載されている。",
    "murder": "警備会社は施設近くで起きた殺人の後、報告書を確認した。",
    "monitor": "ITチームは締め切り前にシステムを監視する。",
    "soldier": "会社は海外に駐留する兵士に物資を寄付した。",
    "shock": "突然の辞任はチーム全体にとって衝撃だった。",
    "usual": "仕入先はいつもより遅く注文品を納品した。",
    "pack": "サンプルは書類と分けて梱包してください。",
    "recall": "メーカーは欠陥製品のリコールを発表した。",
    "wine": "レストランは顧客との夕食用にワインを注文した。",
    "swim": "ホテルには会議の後に宿泊客が泳げるプールがある。",
    "manufacture": "その工場は医療機器用の部品を製造している。",
    "theater": "会社は年次表彰式のために劇場を借りた。",
    "totally": "改訂版の計画は元の提案とまったく異なる。",
    "museum": "旅行会社は来訪者のために博物館見学を手配した。",
    "visitor": "訪問者は全員、受付で記帳しなければならない。",
    "objective": "プロジェクトの主な目的は配送時間を短縮することだ。",
    "moreover": "その提案は手頃なうえ、すぐに実施できる。",
    "onto": "技術者は交換部品を作業台の上に置いた。",
    "oppose": "数人の取締役が提案された料金値上げに反対している。",
    "vehicle": "会社は配送車両に電気自動車を1台加えた。",
    "scientist": "会社はより安全な製品を開発するため科学者を雇った。",
    "route": "運転手は道路工事のため配送ルートを変更した。",
    "taste": "レストランは新メニューの味を顧客に評価してもらった。",
    "tonight": "来訪する役員は今夜、夕食会に参加する。",
    "normally": "その支店には通常、月曜日に用品が届く。",
    "sight": "ホテルからは港がよく見える。",
    "quote": "仕入先は交換機器の見積書を送った。",
    "violence": "会社には職場での暴力を禁じる方針がある。",
    "minister": "大臣は貿易使節団の一員として工場を訪問した。",
    "mouth": "技術者は貯蔵タンクの開口部を清掃した。",
    "noise": "工場は機械音を減らすため断熱材を設置した。",
    "square": "オフィスの床面積は500平方メートルだ。",
    "occasion": "会社はその機会のために特別なイベントを準備した。",
    "temperature": "倉庫は製品のために一定の温度を保っている。",
    "troop": "会社は緊急時に部隊へ機器を供給した。",
    "technical": "顧客は設置について技術サポートを必要としている。",
    "remind": "金曜日の納品について仕入先に念を押してください。",
    "skin": "安全手袋は作業員の皮膚を洗浄液から守る。",
    "prison": "請負業者は刑務所の警備設備を更新した。",
    "switch": "技術部門は来四半期にデジタルマニュアルへ切り替える。",
    "wood": "家具会社は認証を受けた仕入先から木材を調達している。",
    "participate": "従業員は顧客サービス研修に参加できる。",
    "tough": "チームは契約条件をめぐる厳しい交渉に直面した。",
    "tear": "箱を開けるとき配送ラベルを破らないでください。",
    "representative": "営業担当者が来週、顧客を訪問する。",
    "shake": "洗浄液を使う前に容器を振ってください。",
    "shoe": "安全上の理由から、倉庫ではつま先が覆われた靴が必要だ。",
    "ought": "仕入先は納品日を変更する前に当社へ知らせるべきだ。",
    "regulation": "工場は最新の安全規則を守らなければならない。",
    "studio": "デザインスタジオは新しいカタログ用の画像を準備した。",
    "proper": "経費精算を申請するときは適切なフォームを使ってください。",
    "relax": "ホテルには会議の参加者がくつろげるラウンジがある。",
    "tourist": "ホテルは観光客と出張者に送迎サービスを提供している。",
    "suspect": "監査担当者は請求書が二重に提出されたと疑っている。",
    "perspective": "コンサルタントは販売戦略について新たな視点を示した。",
    "register": "金曜日までに安全研修へ登録してください。",
    "signal": "機械が停止する前に警告信号が表示された。",
    "relevant": "提案書には関連する情報だけを含めてください。",
    "wake": "アラームは夜勤の従業員を6時に起こす。",
    "necessarily": "価格が高いからといって、必ずしも品質が高いとは限らない。",
    "slowly": "寒い天候のため荷積みゲートがゆっくり開いた。",
    "tie": "契約は支払いを作業の成功に結びつけている。",
    "victim": "会社は職場事故の被害者を支援した。",
    "threaten": "仕入先は未払いの請求書をめぐり契約を取り消すと脅した。",
    "secure": "トラックが出発する前に箱を固定してください。",
    "root": "マネージャーは遅延の根本原因を調査した。",
    "recommendation": "コンサルタントの推奨案が採用手続きを改善した。",
    "rank": "その製品は顧客満足度調査で1位になった。",
    "typical": "典型的な顧客はウェブサイトで注文する。",
    "west": "会社は国の西部に支店を開設した。",
    "resident": "地域住民は建設工事について通知を受け取った。",
    "provision": "契約には納品遅延に関する規定が含まれている。",
    "plenty": "会議前に提案書を確認する時間は十分にある。",
    "strongly": "今日中に予約を確認することを強く勧めます。",
    "moral": "倫理委員会は会社の道徳的責任について議論した。",
    "principal": "遅延の主な理由は資材不足だった。",
    "master": "技術者は今月、新しい在庫システムを習得したいと考えている。",
    "session": "研修会は9時に始まる。",
    "nevertheless": "配送は遅れたが、それでも顧客は受け入れた。",
    "predict": "アナリストは来四半期に需要が増えると予測している。",
    "previously": "そのソフトウェアは以前、財務部が使用していた。",
    "protection": "会社は顧客データの保護を強化した。",
    "wed": "従業員は10月に結婚し、2週間休暇を取る予定だ。",
    "rent": "支店は駅近くのオフィスの家賃を支払っている。",
    "shot": "マーケティングチームは新製品の動画を撮影した。",
    "reasonable": "顧客は改訂後の価格を妥当だと考えた。",
    "till": "オフィスは6時まで営業する。",
    "theme": "会議のテーマは持続可能なビジネスだ。",
    "odd": "技術者は支払いシステムに奇妙なエラーがあることに気づいた。",
    "rely": "その支店は用品を中央倉庫に頼っている。",
    "narrow": "配送トラックは狭い通りに入れなかった。",
    "succeed": "各部署が締め切りを守れば、プロジェクトは成功する。",
    "permit": "市は倉庫拡張の許可証を発行した。",
    "seriously": "マネージャーは顧客の苦情をすべて真剣に受け止めている。",
    "wild": "リゾートは敷地の近くに巣を作る野鳥を保護している。",
    "unique": "その製品には若い顧客を引きつける独特なデザインがある。",
    "practical": "コンサルタントは人員問題への実用的な解決策を提案した。",
    "tea": "ホテルは会議室でコーヒーと紅茶を提供している。",
    "soft": "会社は受付エリア用に柔らかな照明を注文した。",
    "row": "新しい机は窓の近くに一列に並べられている。",
    "youth": "会社は地域の若者向け研修プログラムを支援している。",
    "sexual": "会社にはセクシュアルハラスメントを禁じる厳格な方針がある。",
    "shoulder": "職場の診療所は肩を痛めたマヤを治療した。",
    "ourselves": "私たちは会議で新しい顧客に自己紹介した。",
    "sheet": "新入社員はそれぞれ研修予定を説明した用紙を受け取った。",
    "notion": "マネージャーは価格を下げれば常に売上が増えるという考えを退けた。",
    "opposition": "その提案は複数の部門長から反対を受けた。",
    "relief": "新しい予定は長距離通勤の従業員に安堵をもたらした。",
    "outcome": "マネージャーは交渉で予想される結果を説明した。",
    "musical": "ホテルは会社のイベントのために音楽グループを雇った。",
    "recover": "システム更新後、売上は回復する可能性がある。",
    "stretch": "チームは研修プログラムを2週間にわたって実施する。",
    "retire": "取締役は年末に退職する予定だ。",
    "tiny": "技術者は荷物に非常に小さなひびを見つけた。",
    "suitable": "会議室は10人の会議に適している。",
    "native": "ガイドはその地域原産の植物を説明した。",
    "witness": "目撃者は安全担当者に供述を提出した。",
    "terrible": "嵐は倉庫の屋根にひどい損害を与えた。",
    "researcher": "会社は顧客データを分析するため研究者を雇った。",
    "ordinary": "交換部品は普通に見えるが、必要な基準を満たしている。",
    "selection": "その店は幅広いオフィス用品を取りそろえている。",
    "mental": "会社は従業員の心の健康を支援している。",
    "participant": "参加者は全員、研修会の後に短い調査へ回答した。",
    "vision": "社長は今後5年間の会社の将来像を共有した。",
    "personality": "彼女の親しみやすい性格は顧客との関係づくりに役立つ。",
    "specifically": "契約書は送料を誰が支払うかを明確に定めている。",
    "tip": "研修担当者は難しい電話への対応について役立つ助言をした。",
    "peak": "店は買い物の最盛期に臨時スタッフを雇う。",
    "proportion": "注文の大部分は現在、ウェブサイト経由で届いている。",
    "shout": "従業員は顧客や同僚に怒鳴ってはいけない。",
    "yard": "輸送コンテナは工場裏の敷地に保管されている。",
    "significantly": "新しい手順によって処理時間が大幅に短縮された。",
    "surely": "仕入先は今日中に改訂版の見積書を出せるはずだ。",
    "somewhat": "改訂版の予定は元の予定よりやや短い。",
    "presentation": "営業部長は改訂版の戦略についてプレゼンテーションを行った。",
    "poll": "会社は従業員が希望する福利厚生について世論調査を行った。",
    "weak": "監査で経費承認の管理が不十分だと判明した。",
    "reduction": "配送費の削減で利益率が改善した。",
    "reserve": "来訪する顧客のために会議室を予約してください。",
    "mission": "会社の使命は配送をより確実にすることだ。",
    "somehow": "どういうわけか、荷物は配送ラベルなしで届いた。",
    "tone": "マネージャーは顧客へのメールで礼儀正しい口調を使った。",
    "neighborhood": "上司は新入社員がオフィス近くの静かな地域を見つけるのを手伝った。",
    "passenger": "乗客は全員、搭乗前に身分証明書を提示しなければならない。",
    "phase": "プロジェクトは試験の最終段階に入った。",
    "thin": "薄い保護フィルムが画面を傷から守る。",
    "rush": "検査手続きを急いではいけない。",
    "religion": "会社はすべての従業員の宗教と信仰を尊重している。",
    "reject": "購買マネージャーは破損した出荷品を拒否した。",
    "plate": "技術者は機械内部の金属板を交換した。",
    "steal": "防犯カメラは来訪者による機器の盗難防止に役立つ。",
    "protest": "複数の従業員が方針変更に抗議した。",
    "sad": "支店が閉鎖されると聞いて、チームは悲しんだ。",
    "sick": "具合が悪い従業員は上司に知らせてください。",
    "unable": "運送会社は荷物を時間どおりに届けられなかった。",
    "sky": "空が嵐模様だったため、航空機は離陸できなかった。",
    "properly": "トラックに積む前に各箱へ適切にラベルを貼ってください。",
    "multiple": "顧客はウェブサイトから複数の依頼を送った。",
    "yield": "新しい手順は来四半期により良い結果を生むはずだ。",
    "via": "請求書はメールで経理部に送られた。",
    "unlike": "旧モデルと違い、新しいプリンターはインクの使用量が少ない。",
    "mobile": "営業チームは携帯アプリで注文を更新している。",
    "acknowledge": "運用チームは今日、顧客の苦情を受け付ける。",
    "reward": "会社は優れた顧客サービスに対して彼女に報酬を与えた。",
    "academic": "会社は専門資格を目指す従業員に学習支援を提供している。",
    "voter": "市は登録有権者全員に公開会議の情報を送った。",
    "meanwhile": "修理には2日かかる。その間、予備の機械を使う。",
    "scientific": "チームは新素材を試験するため科学的な方法を用いた。",
    "wage": "労働組合は会社に最低賃金の引き上げを求めた。",
    "remark": "顧客は提案されたレイアウトについて有益な意見を述べた。",
    "medicine": "診療所は患者の医療記録に薬を記載した。",
    "rare": "仕入先が確定した納品日を守れないのは珍しい。",
    "settlement": "2社は数週間の交渉の末、和解に達した。",
    "widely": "新しい支払いシステムは地域の小売店で広く使われている。",
    "minimum": "無料配送には最低注文数量を満たす必要がある。",
    "northern": "会社は北部地域で複数の店舗を運営している。",
    "shut": "工場は来週月曜日、保守のため閉鎖する。",
    "victory": "契約を獲得したことは営業チームの大きな勝利だった。",
    "resolve": "チームは締め切り前に問題を解決する。",
    "variable": "配送時間は総費用に影響する変動要因だ。",
    "sweet": "パン店は来訪する顧客のために甘い贈り物を用意した。",
    "permanent": "会社は試用期間の後、彼女に正社員の職を提示した。",
    "pursue": "従業員は専門資格の取得を目指している。",
    "tall": "倉庫には大きな箱を保管する高い棚がある。",
    "urge": "マネージャーは従業員に報告書を期限内に提出するよう強く促した。",
}


def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 2][400:700]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        item["example"] = EN[word]
        key = f"builtin:{item['id']}"
        example = translations.setdefault(key, {}).setdefault("example", {})
        source = EN[word]
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if example.get(field) != value:
                example[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 600+ English examples batch 3: {len(level_rows)} terms, {changed} fields")


if __name__ == "__main__":
    main()
