#!/usr/bin/env python3
"""Review the remaining 157 TOEIC 600+ examples (items 1301-1457)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"
PHRASE_PATH = ROOT / "app/src/main/assets/vocabulary_phrase_translations.json"

EN = {
    "comma": "Please add a comma between the two items in the address.",
    "commonly": "This payment method is commonly used by our overseas clients.",
    "cone": "The safety team placed a cone beside the wet floor.",
    "container": "The container was sealed before it left the warehouse.",
    "continent": "The company exports products to every continent except Antarctica.",
    "cord": "The technician replaced the damaged power cord.",
    "correctly": "Please enter the account number correctly before submitting the form.",
    "cure": "The new treatment may provide a cure for the equipment problem.",
    "destination": "The courier confirmed the package's destination.",
    "diary": "The manager used a diary to record appointments with clients.",
    "dictionary": "The editor checked the technical term in a dictionary.",
    "drain": "The maintenance team will drain the tank before cleaning it.",
    "erase": "Please erase the outdated figures from the report.",
    "ex": "Her ex-colleague recommended her for the position.",
    "exit": "Please use the emergency exit if the alarm sounds.",
    "fabric": "The manufacturer selected durable fabric for the office chairs.",
    "feedback": "The manager requested feedback after the training session.",
    "fever": "Employees with a fever should contact the workplace clinic.",
    "fiber": "The company uses recycled fiber in its packaging.",
    "fin": "The engineer inspected the fin on the cooling unit.",
    "flesh": "The food supplier checks the flesh of each fish for quality.",
    "flip": "Flip the switch after the indicator turns green.",
    "fluid": "The engineer modeled how fluid pressure changes inside the pipe.",
    "fraction": "Only a small fraction of orders require manual review.",
    "ghost": "The IT team found a ghost entry in the old database.",
    "goat": "The hotel buys goat cheese from a nearby farm.",
    "goodness": "The manager thanked the team for the goodness of its work.",
    "goods": "The warehouse checks all goods before shipment.",
    "gram": "The package label states that the sample weighs 200 grams.",
    "graph": "The graph shows monthly changes in customer demand.",
    "cooperate": "The two departments must cooperate to meet the deadline.",
    "globe": "The company operates offices across the globe.",
    "assemble": "The technician will assemble the new desks tomorrow.",
    "exploration": "The company funded exploration for new sources of raw materials.",
    "diploma": "The applicant included a copy of her diploma with the application.",
    "controlling": "The manager has a controlling interest in the subsidiary.",
    "conjunction": "The contract was revised in conjunction with the legal team.",
    "challenging": "The client gave the team a challenging but realistic deadline.",
    "convenience": "Online payment adds convenience for busy customers.",
    "anniversary": "The company held an event for its fiftieth anniversary.",
    "experienced": "The company is looking for an experienced logistics manager.",
    "certificate": "The technician presented a safety certificate before starting work.",
    "discourage": "The penalty is intended to discourage late payment.",
    "curiosity": "The customer's curiosity led to a useful question about the product.",
    "awkward": "The new employee felt awkward when the meeting started late.",
    "desirable": "A flexible schedule is a desirable benefit for many employees.",
    "duplicate": "The accounting system detected a duplicate payment.",
    "disturbed": "The client was disturbed by the sudden change in the contract.",
    "behaviour": "The code of conduct explains acceptable workplace behaviour.",
    "converted": "The company converted the empty store into a training center.",
    "creativity": "The design project requires creativity and careful planning.",
    "ambition": "Her ambition is to lead the company's international sales team.",
    "animated": "The manager gave an animated presentation about the new service.",
    "guidance": "New employees receive guidance from a senior colleague.",
    "gambling": "The company prohibits gambling on its premises.",
    "detailed": "The supplier provided a detailed quotation for the equipment.",
    "costume": "Employees wore a costume for the company's charity event.",
    "antenna": "The technician replaced the antenna on the communication device.",
    "funeral": "The employee requested leave to attend a family funeral.",
    "defence": "The security team improved the defence of the main entrance.",
    "forbid": "Company rules forbid employees from sharing passwords.",
    "enroll": "Employees may enroll in the advanced safety course online.",
    "depart": "The train will depart from platform three at noon.",
    "costly": "The mistake caused a costly delay in production.",
    "absurd": "It would be absurd to ignore the signed agreement.",
    "favour": "Could you do me a favour and forward this email to the client?",
    "diesel": "The company is replacing its diesel trucks with electric vehicles.",
    "completion": "The final payment is due upon completion of the work.",
    "failing": "The audit identified a failing control in the payment process.",
    "adapted": "The team used adapted training materials for remote staff.",
    "acquired": "The company acquired a smaller distributor last year.",
    "disable": "The administrator will disable the account after repeated failed logins.",
    "devoted": "The devoted customer-service team handled the complaint patiently.",
    "enquiry": "We received an enquiry about delivery to the regional office.",
    "courier": "The courier collected the documents before noon.",
    "fighter": "The company hired a skilled fighter pilot for the aviation project.",
    "demanding": "The demanding client requested daily progress reports.",
    "defensive": "The manager took a defensive position during the negotiation.",
    "adapter": "The technician packed an adapter for the overseas presentation.",
    "accessible": "The new website is accessible on mobile devices.",
    "advisor": "The financial advisor explained the investment options.",
    "cooperative": "The supplier was cooperative when the delivery date changed.",
    "banking": "The company uses online banking to pay overseas suppliers.",
    "fantasy": "The publisher released a fantasy novel for the holiday market.",
    "amateur": "The amateur photographer took pictures at the company event.",
    "applied": "The course focuses on applied skills for office communication.",
    "ballet": "The hotel arranged ballet tickets for the visiting clients.",
    "galaxy": "The company launched a campaign featuring a galaxy of local brands.",
    "destiny": "The manager believes the team's destiny depends on careful planning.",
    "abrupt": "An abrupt change in demand forced the factory to adjust production.",
    "computing": "The IT department improved computing capacity for the new database.",
    "anchor": "The long-term contract is an anchor for the regional business.",
    "frozen": "The cafeteria served frozen meals during the renovation.",
    "folding": "The conference room has folding tables for flexible layouts.",
    "defined": "The contract contains a clearly defined delivery schedule.",
    "disguise": "The security officer recognized the disguise at the entrance.",
    "distract": "Please silence your phone so it does not distract the speaker.",
    "enclose": "Please enclose a copy of the receipt with your application.",
    "fierce": "The company faces fierce competition in the overseas market.",
    "fragile": "Mark the box as fragile before handing it to the courier.",
    "deputy": "The deputy manager approved the revised staffing plan.",
    "casual": "The company allows casual clothing on Fridays.",
    "enrollment": "Enrollment in the company's new training program increased this quarter.",
    "roommate": "Her roommate works at the company's regional office.",
    "auditorium": "The facilities team inspected the auditorium before the event.",
    "commute": "Many employees commute by train to the city office.",
    "search engine": "The marketing team improved how the website appears in a search engine.",
    "keyword": "The IT department added a keyword filter to the support database.",
    "greenhouse effect": "The report explains how the greenhouse effect affects energy policy.",
    "prehistoric": "The museum prepared a prehistoric exhibit for school visitors.",
    "pottery": "The museum displayed pottery found near the ancient trade route.",
    "burial": "The city approved a plan to protect the historic burial site.",
    "monument": "The company donated funds to restore the local monument.",
    "dwelling": "The survey records the condition of every dwelling in the area.",
    "food chain": "The environmental report explains how pollution affects the food chain.",
    "extinction": "The report discusses how habitat loss can cause extinction.",
    "emissions": "The factory reduced emissions by installing new filters.",
    "fossil fuel": "The company plans to reduce its use of fossil fuel.",
    "melting": "The report measures melting in the mountain snowpack.",
    "census": "The city used census data to plan new transportation services.",
    "primary source": "The researcher cited a primary source in the historical report.",
    "seminar paper": "The student submitted a seminar paper before the academic deadline.",
    "attendee": "Each attendee received a name badge at the conference.",
    "contributor": "Each contributor was recognized in the project report.",
    "minutes": "The assistant circulated the meeting minutes before lunch.",
    "headquarters": "The company moved its headquarters to Tokyo.",
    "supervisor": "Ask your supervisor before changing the delivery schedule.",
    "resignation": "The manager accepted the employee's resignation.",
    "payroll": "The payroll team processed the salaries on Friday.",
    "vacancy": "The company posted a vacancy on its website.",
    "workload": "The supervisor adjusted the workload for the team.",
    "receipt": "Please keep the receipt for your expense report.",
    "refund": "The store issued a refund after the customer returned the product.",
    "cash flow": "The report shows that cash flow improved this quarter.",
    "vendor": "The purchasing team selected a new vendor.",
    "shipment": "The shipment arrived at the warehouse on time.",
    "warehouse": "The warehouse stores products before delivery.",
    "itinerary": "The assistant confirmed the itinerary before the business trip.",
    "departure": "The departure time was changed because of the delay.",
    "hardware": "The IT team replaced the damaged hardware.",
    "notify": "Please notify the client about the delay.",
    "postpone": "The manager decided to postpone the meeting.",
    "profitable": "The new service became profitable within a year.",
    "onboarding": "The HR team prepared an onboarding plan for new employees.",
    "deliverable": "The team submitted the deliverable before the deadline.",
    "turnover": "The company is working to reduce employee turnover.",
    "outsourcing": "Outsourcing reduced the cost of customer support.",
    "retailer": "The retailer placed a large order before the holiday season.",
    "distributor": "The distributor delivered the products to local stores.",
    "consignment": "The consignment arrived at the port on Monday.",
    "customs": "The shipment was held at customs for two days.",
    "forecasting": "Accurate forecasting helps the company plan its budget.",
    "quarterly": "The company publishes a quarterly financial report.",
    "optional": "The advanced training session is optional for employees.",
    "delegate": "The manager will delegate the task to an experienced employee.",
    "incur": "The company may incur additional shipping costs.",
    "verify": "Please verify the invoice before making payment.",
}

JA = {
    "comma": "住所の2つの項目の間にコンマを入れてください。",
    "commonly": "この支払い方法は海外の顧客によく使われている。",
    "cone": "安全チームは濡れた床のそばにコーンを置いた。",
    "container": "容器は倉庫を出る前に封をされた。",
    "continent": "会社は南極を除くすべての大陸へ製品を輸出している。",
    "cord": "技術者は破損した電源コードを交換した。",
    "correctly": "フォームを提出する前に口座番号を正しく入力してください。",
    "cure": "新しい治療法で機器の問題が解決する可能性がある。",
    "destination": "宅配業者は荷物の配送先を確認した。",
    "diary": "マネージャーは顧客との予定を日記に記録した。",
    "dictionary": "編集者は専門用語を辞書で確認した。",
    "drain": "保守チームは清掃前にタンクの水を抜く。",
    "erase": "報告書から古い数値を消してください。",
    "ex": "彼女の元同僚がその職を推薦した。",
    "exit": "警報が鳴ったら非常口を使ってください。",
    "fabric": "メーカーはオフィス椅子に丈夫な布地を選んだ。",
    "feedback": "マネージャーは研修後に意見を求めた。",
    "fever": "発熱した従業員は職場の診療所に連絡してください。",
    "fiber": "会社は包装に再生繊維を使っている。",
    "fin": "技術者は冷却装置のフィンを点検した。",
    "flesh": "食品仕入先は魚の身を品質検査している。",
    "flip": "表示が緑になったらスイッチを反転させてください。",
    "fluid": "技術者はパイプ内の液体圧力の変化をモデル化した。",
    "fraction": "手作業で確認が必要な注文はごく一部だ。",
    "ghost": "ITチームは古いデータベースに残る幽霊データを見つけた。",
    "goat": "ホテルは近隣農家からヤギのチーズを仕入れている。",
    "goodness": "マネージャーは仕事の良さについてチームに感謝した。",
    "goods": "倉庫はすべての商品を出荷前に確認する。",
    "gram": "荷札にはサンプルの重量が200グラムと記載されている。",
    "graph": "グラフは顧客需要の月ごとの変化を示している。",
    "cooperate": "2つの部署は締め切りを守るため協力しなければならない。",
    "globe": "会社は世界中でオフィスを運営している。",
    "assemble": "技術者は明日、新しい机を組み立てる。",
    "exploration": "会社は原材料の新たな供給源の探査に資金を出した。",
    "diploma": "応募者は申請書に卒業証書の写しを添付した。",
    "controlling": "マネージャーは子会社の支配的な持分を持っている。",
    "conjunction": "契約書は法務チームと連携して改訂された。",
    "challenging": "顧客は難しいが現実的な締め切りを設定した。",
    "convenience": "オンライン決済は忙しい顧客に利便性をもたらす。",
    "anniversary": "会社は創立50周年のイベントを開催した。",
    "experienced": "会社は経験豊富な物流マネージャーを探している。",
    "certificate": "技術者は作業開始前に安全証明書を提示した。",
    "discourage": "その罰則は支払い遅延を思いとどまらせることを目的としている。",
    "curiosity": "顧客の好奇心が製品について役立つ質問につながった。",
    "awkward": "会議が遅れて始まり、新入社員は気まずく感じた。",
    "desirable": "柔軟な勤務時間は多くの従業員にとって望ましい福利厚生だ。",
    "duplicate": "経理システムが二重支払いを検出した。",
    "disturbed": "契約の突然の変更で顧客は動揺した。",
    "behaviour": "行動規範は受け入れられる職場での振る舞いを説明している。",
    "converted": "会社は空き店舗を研修センターに転換した。",
    "creativity": "デザインプロジェクトには創造性と綿密な計画が必要だ。",
    "ambition": "彼女の野望は会社の国際営業チームを率いることだ。",
    "animated": "マネージャーは新サービスについて活気のある発表を行った。",
    "guidance": "新入社員は先輩から指導を受ける。",
    "gambling": "会社は敷地内でのギャンブルを禁止している。",
    "detailed": "仕入先は機器の詳細な見積書を提出した。",
    "costume": "従業員は会社の慈善イベントで衣装を着た。",
    "antenna": "技術者は通信機器のアンテナを交換した。",
    "funeral": "従業員は家族の葬儀に出席するため休暇を申請した。",
    "defence": "警備チームは正面入口の防御を強化した。",
    "forbid": "社内規則は従業員がパスワードを共有することを禁じている。",
    "enroll": "従業員はオンラインで上級安全講座に登録できる。",
    "depart": "列車は正午に3番ホームを出発する。",
    "costly": "そのミスで生産に費用のかかる遅れが生じた。",
    "absurd": "署名済みの契約を無視するのはばかげている。",
    "favour": "お願いがあります。このメールを顧客へ転送してもらえますか。",
    "diesel": "会社はディーゼルトラックを電気自動車に置き換えている。",
    "completion": "最終支払いは作業完了時に支払う。",
    "failing": "監査で支払い手続きの管理に欠陥が見つかった。",
    "adapted": "チームはリモート勤務者向けに調整した研修資料を使った。",
    "acquired": "会社は昨年、小規模な販売代理店を買収した。",
    "disable": "管理者はログイン失敗が続くとアカウントを無効にする。",
    "devoted": "献身的な顧客サービスチームが辛抱強く苦情に対応した。",
    "enquiry": "地域オフィスへの配送について問い合わせを受けた。",
    "courier": "宅配業者は正午前に書類を集荷した。",
    "fighter": "会社は航空プロジェクトのため熟練した戦闘機パイロットを雇った。",
    "demanding": "要求の多い顧客は毎日の進捗報告を求めた。",
    "defensive": "マネージャーは交渉中に防御的な態度を取った。",
    "adapter": "技術者は海外でのプレゼンテーション用に変換アダプターを梱包した。",
    "accessible": "新しいウェブサイトは携帯端末から利用しやすい。",
    "advisor": "財務顧問は投資の選択肢を説明した。",
    "cooperative": "納品日が変わったとき、仕入先は協力的だった。",
    "banking": "会社はオンラインバンキングで海外の仕入先に支払っている。",
    "fantasy": "出版社は休暇市場向けにファンタジー小説を発売した。",
    "amateur": "アマチュア写真家が会社のイベントを撮影した。",
    "applied": "講座はオフィスでのコミュニケーションに応用できる技能を扱う。",
    "ballet": "ホテルは来訪した顧客のためにバレエのチケットを手配した。",
    "galaxy": "会社は地元ブランドの豪華な集まりを紹介するキャンペーンを開始した。",
    "destiny": "マネージャーはチームの運命が綿密な計画にかかっていると考えている。",
    "abrupt": "需要の急な変化で工場は生産を調整した。",
    "computing": "IT部門は新しいデータベースの計算処理能力を高めた。",
    "anchor": "長期契約は地域事業の支えになっている。",
    "frozen": "改修中、食堂は冷凍食品を提供した。",
    "folding": "会議室には柔軟な配置ができる折りたたみ式の机がある。",
    "defined": "契約書には明確に定められた配送スケジュールがある。",
    "disguise": "警備員は入口で変装を見破った。",
    "distract": "発表者の気を散らさないよう、電話を消音してください。",
    "enclose": "申請書に領収書の写しを同封してください。",
    "fierce": "会社は海外市場で激しい競争に直面している。",
    "fragile": "宅配業者に渡す前に箱へ壊れ物と表示してください。",
    "deputy": "副マネージャーは改訂版の人員計画を承認した。",
    "casual": "会社は金曜日にカジュアルな服装を認めている。",
    "enrollment": "会社の新研修プログラムへの登録者数は今四半期に増えた。",
    "roommate": "彼女のルームメートは会社の地域オフィスで働いている。",
    "auditorium": "施設チームはイベント前に講堂を点検した。",
    "commute": "多くの従業員は市内オフィスへ電車で通勤する。",
    "search engine": "マーケティングチームは検索エンジンでサイトが表示される方法を改善した。",
    "keyword": "IT部門はサポートデータベースにキーワードフィルターを追加した。",
    "greenhouse effect": "報告書は温室効果がエネルギー政策に及ぼす影響を説明している。",
    "prehistoric": "博物館は学生向けに先史時代の展示を準備した。",
    "pottery": "博物館は古代の交易路の近くで見つかった陶器を展示した。",
    "burial": "市は歴史的な埋葬地を保護する計画を承認した。",
    "monument": "会社は地域の記念碑の修復に資金を寄付した。",
    "dwelling": "調査は地域の各住宅の状態を記録している。",
    "food chain": "環境報告書は汚染が食物連鎖に及ぼす影響を説明した。",
    "extinction": "報告書は生息地の喪失が絶滅を引き起こす仕組みを扱っている。",
    "emissions": "工場は新しいフィルターを設置して排出量を削減した。",
    "fossil fuel": "会社は化石燃料の使用を減らす予定だ。",
    "melting": "報告書は山の積雪の融解を測定している。",
    "census": "市は新しい交通サービスの計画に国勢調査のデータを使った。",
    "primary source": "研究者は歴史報告書で一次資料を引用した。",
    "seminar paper": "学生は学術上の締め切り前にゼミ論文を提出した。",
    "attendee": "出席者は全員、会議で名札を受け取った。",
    "contributor": "各貢献者はプロジェクト報告書で表彰された。",
    "minutes": "アシスタントは昼食前に会議議事録を回覧した。",
    "headquarters": "会社は本社を東京へ移転した。",
    "supervisor": "配送予定を変える前に上司に相談してください。",
    "resignation": "マネージャーは従業員の辞職を受理した。",
    "payroll": "給与担当チームは金曜日に給与を処理した。",
    "vacancy": "会社はウェブサイトに求人を掲載した。",
    "workload": "上司はチームの仕事量を調整した。",
    "receipt": "経費報告書のため領収書を保管してください。",
    "refund": "顧客が商品を返品した後、店は払い戻しを行った。",
    "cash flow": "報告書は今四半期に資金繰りが改善したと示している。",
    "vendor": "購買チームは新しい販売業者を選定した。",
    "shipment": "出荷品は時間どおり倉庫に到着した。",
    "warehouse": "倉庫は配送前の製品を保管している。",
    "itinerary": "アシスタントは出張前に旅程を確認した。",
    "departure": "遅延のため出発時刻が変更された。",
    "hardware": "ITチームは破損したハードウェアを交換した。",
    "notify": "遅延について顧客に通知してください。",
    "postpone": "マネージャーは会議を延期することにした。",
    "profitable": "新サービスは1年以内に利益を生むようになった。",
    "onboarding": "人事チームは新入社員向けの受け入れ計画を準備した。",
    "deliverable": "チームは締め切り前に納品物を提出した。",
    "turnover": "会社は従業員の離職率を下げるため取り組んでいる。",
    "outsourcing": "外注によって顧客サポートの費用が削減された。",
    "retailer": "小売業者は休暇シーズン前に大量注文を出した。",
    "distributor": "販売代理店は地域の店舗へ製品を届けた。",
    "consignment": "委託貨物は月曜日に港へ到着した。",
    "customs": "出荷品は税関で2日間留め置かれた。",
    "forecasting": "正確な予測は会社の予算計画に役立つ。",
    "quarterly": "会社は四半期ごとの財務報告書を発行している。",
    "optional": "上級研修会への参加は任意だ。",
    "delegate": "マネージャーは経験豊富な従業員に作業を委任する。",
    "incur": "会社は追加の配送費を負担する可能性がある。",
    "verify": "支払いをする前に請求書を検証してください。",
}

def main() -> None:
    vocabulary = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    phrase_root = json.loads(PHRASE_PATH.read_text(encoding="utf-8"))
    translations = phrase_root.setdefault("translations", {})
    level_rows = [item for item in vocabulary if int(item.get("level", 0)) == 2][1300:]
    assert {str(item["word"]).casefold() for item in level_rows} == set(EN)
    assert set(EN) == set(JA)
    changed = 0
    for item in level_rows:
        word = str(item["word"]).casefold()
        source = EN[word]
        item["example"] = source
        example = translations.setdefault(f"builtin:{item['id']}", {}).setdefault("example", {})
        for field, value in (("source", source), ("en", source), ("ja", JA[word])):
            if example.get(field) != value:
                example[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(vocabulary, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    PHRASE_PATH.write_text(json.dumps(phrase_root, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed 600+ English examples batch 6: {len(level_rows)} terms, {changed} fields")

if __name__ == "__main__":
    main()
