#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; VOCAB=ROOT/"app/src/main/assets/vocabulary.json"; PHRASE=ROOT/"app/src/main/assets/vocabulary_phrase_translations.json"
EN={"inferiority":"The test did not show any inferiority in the new material.","seamless":"The upgrade created a seamless connection between the systems.","unthinkable":"A complete loss of the records was once unthinkable.","wholesaler":"The retailer buys office supplies from a regional wholesaler.","dissimilarity":"The report highlights the dissimilarity between the two markets.","ambiguously":"The contract was written ambiguously and caused a dispute.","unevenness":"The inspector found unevenness in the warehouse floor.","cutback":"The budget cutback delayed the equipment purchase.","compensated":"The airline compensated passengers for the cancellation.","meaningfulness":"The survey measures the meaningfulness of employees' work.","conceivable":"It is conceivable that demand will increase next quarter.","conceivably":"The new route could conceivably reduce delivery time.","unpredictability":"The unpredictability of the weather makes scheduling difficult.","analytically":"The consultant examined the data analytically.","abstraction":"The training explains the concept without unnecessary abstraction.","powerlessness":"The support plan helps employees avoid a feeling of powerlessness.","predictability":"The software improves the predictability of inventory demand.","ecologically":"The company is ecologically responsible in its use of packaging.","fabricated":"The inspector rejected the fabricated safety certificate.","decency":"The employee treated every customer with decency."}
JA={"inferiority":"試験では新素材の劣位は示されなかった。","seamless":"更新によりシステム間の円滑な接続が実現した。","unthinkable":"記録が完全に失われることは以前は考えられなかった。","wholesaler":"小売業者は事務用品を地域の卸売業者から仕入れる。","dissimilarity":"報告書は2つの市場の相違点を強調している。","ambiguously":"契約が曖昧に書かれていたため紛争が起きた。","unevenness":"検査員は倉庫の床の凹凸を見つけた。","cutback":"予算削減で機器購入が遅れた。","compensated":"航空会社は欠航について乗客に補償した。","meaningfulness":"調査は従業員の仕事の意義を測定する。","conceivable":"次の四半期に需要が増えることは考えられる。","conceivably":"新経路で配送時間を短縮できる可能性がある。","unpredictability":"天候の予測不能性が日程調整を難しくする。","analytically":"コンサルタントはデータを分析的に調べた。","abstraction":"研修は不要な抽象論を避けて概念を説明する。","powerlessness":"支援計画は従業員の無力感を和らげる。","predictability":"ソフトウェアは在庫需要の予測可能性を高める。","ecologically":"会社は包装の使用で環境に配慮している。","fabricated":"検査員は偽造された安全証明書を拒否した。","decency":"従業員は全顧客に礼節をもって接した。"}
def main():
    v=json.loads(VOCAB.read_text(encoding='utf-8')); p=json.loads(PHRASE.read_text(encoding='utf-8')); t=p.setdefault('translations',{}); rows=[x for x in v if int(x.get('level',0))==4][110:130]; assert {x['word'] for x in rows}==set(EN)==set(JA)
    for x in rows:
        w=x['word']; x['example']=EN[w]; t.setdefault(f"builtin:{x['id']}",{}).setdefault('example',{}).update(source=EN[w],en=EN[w],ja=JA[w])
    VOCAB.write_text(json.dumps(v,ensure_ascii=False,indent=1)+'\n',encoding='utf-8'); PHRASE.write_text(json.dumps(p,ensure_ascii=False,indent=1)+'\n',encoding='utf-8'); print('reviewed 800+ English/Japanese examples batch 1c: 20 terms')
if __name__=='__main__': main()
