#!/usr/bin/env python3
"""Apply the native-style wording pass to the added TOEIC business terms."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "app/src/main/assets/vocabulary.json"


# These are the source-language explanations shown in the app. The localized
# meaning fields are maintained in fill_missing_meanings.py.
UPDATES = {
    "onboarding": {
        "meaning": "新入社員の受け入れ・適応支援",
        "meaningEn": "the process of helping a new employee learn about and settle into an organization",
    },
    "deliverable": {
        "meaning": "納品物、成果物",
        "meaningEn": "a product or result that a person or team is expected to provide",
    },
    "turnover": {
        "meaning": "従業員の離職率、または売上高",
        "meaningEn": "the rate at which employees leave a company, or the total sales generated by a business",
    },
    "customs": {
        "meaningEn": "the government agency that controls goods entering a country",
    },
    "incur": {
        "meaning": "費用や義務を負う",
        "meaningEn": "to become responsible for a cost or obligation",
    },
}


def main() -> None:
    items = json.loads(VOCAB_PATH.read_text(encoding="utf-8"))
    by_word = {str(item.get("word", "")).casefold(): item for item in items}
    changed = 0
    for word, updates in UPDATES.items():
        item = by_word.get(word.casefold())
        if item is None:
            raise KeyError(f"missing added business term: {word}")
        for field, value in updates.items():
            if item.get(field) != value:
                item[field] = value
                changed += 1
    VOCAB_PATH.write_text(json.dumps(items, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"reviewed added business source meanings: {changed}")


if __name__ == "__main__":
    main()
